	td_containertd[0] = TextDrawCreate(203.806732, 146.416702, "ld_beat:chit");
	TextDrawLetterSize(td_containertd[0], 0.000000, 0.000000);
	TextDrawTextSize(td_containertd[0], 23.426069, 25.666658);
	TextDrawAlignment(td_containertd[0], 1);
	TextDrawColor(td_containertd[0], -10270721);
	TextDrawSetShadow(td_containertd[0], 0);
	TextDrawSetOutline(td_containertd[0], 0);
	TextDrawFont(td_containertd[0], 4);
	TextDrawSetPreviewModel(td_containertd[0], 2729);
	TextDrawSetPreviewRot(td_containertd[0], 0.000000, 0.000000, 0.000000, 1.000000);

	td_containertd[1] = TextDrawCreate(203.869689, 278.666809, "ld_beat:chit");
	TextDrawLetterSize(td_containertd[1], 0.000000, 0.000000);
	TextDrawTextSize(td_containertd[1], 23.426069, 25.666658);
	TextDrawAlignment(td_containertd[1], 1);
	TextDrawColor(td_containertd[1], -10270721);
	TextDrawSetShadow(td_containertd[1], 0);
	TextDrawSetOutline(td_containertd[1], 0);
	TextDrawFont(td_containertd[1], 4);
	TextDrawSetPreviewModel(td_containertd[1], 2729);
	TextDrawSetPreviewRot(td_containertd[1], 0.000000, 0.000000, 0.000000, 1.000000);

	td_containertd[2] = TextDrawCreate(426.012145, 147.250106, "ld_beat:chit");
	TextDrawLetterSize(td_containertd[2], 0.000000, 0.000000);
	TextDrawTextSize(td_containertd[2], 23.426069, 25.666658);
	TextDrawAlignment(td_containertd[2], 1);
	TextDrawColor(td_containertd[2], -10270721);
	TextDrawSetShadow(td_containertd[2], 0);
	TextDrawSetOutline(td_containertd[2], 0);
	TextDrawFont(td_containertd[2], 4);
	TextDrawSetPreviewModel(td_containertd[2], 2729);
	TextDrawSetPreviewRot(td_containertd[2], 0.000000, 0.000000, 0.000000, 1.000000);

	td_containertd[3] = TextDrawCreate(425.606750, 278.916961, "ld_beat:chit");
	TextDrawLetterSize(td_containertd[3], 0.000000, 0.000000);
	TextDrawTextSize(td_containertd[3], 23.426069, 25.666658);
	TextDrawAlignment(td_containertd[3], 1);
	TextDrawColor(td_containertd[3], -10270721);
	TextDrawSetShadow(td_containertd[3], 0);
	TextDrawSetOutline(td_containertd[3], 0);
	TextDrawFont(td_containertd[3], 4);
	TextDrawSetPreviewModel(td_containertd[3], 2729);
	TextDrawSetPreviewRot(td_containertd[3], 0.000000, 0.000000, 0.000000, 1.000000);

	td_containertd[4] = TextDrawCreate(447.095214, 160.750000, "usebox");
	TextDrawLetterSize(td_containertd[4], 0.000000, 14.414258);
	TextDrawTextSize(td_containertd[4], 206.023437, 0.000000);
	TextDrawAlignment(td_containertd[4], 1);
	TextDrawColor(td_containertd[4], 0);
	TextDrawUseBox(td_containertd[4], true);
	TextDrawBoxColor(td_containertd[4], -10270721);
	TextDrawSetShadow(td_containertd[4], 0);
	TextDrawSetOutline(td_containertd[4], 0);
	TextDrawFont(td_containertd[4], 0);

	td_containertd[5] = TextDrawCreate(441.004394, 153.166656, "usebox");
	TextDrawLetterSize(td_containertd[5], 0.000000, 16.081483);
	TextDrawTextSize(td_containertd[5], 213.519775, 0.000000);
	TextDrawAlignment(td_containertd[5], 1);
	TextDrawColor(td_containertd[5], 134744217);
	TextDrawUseBox(td_containertd[5], true);
	TextDrawBoxColor(td_containertd[5], 286529023);
	TextDrawSetShadow(td_containertd[5], 0);
	TextDrawSetOutline(td_containertd[5], 0);
	TextDrawFont(td_containertd[5], 0);

	td_containertd[6] = TextDrawCreate(268.931243, 155.166687, "CONTAINER");
	TextDrawLetterSize(td_containertd[6], 0.331932, 1.524166);
	TextDrawAlignment(td_containertd[6], 1);
	TextDrawColor(td_containertd[6], -1);
	TextDrawSetShadow(td_containertd[6], 0);
	TextDrawSetOutline(td_containertd[6], 0);
	TextDrawBackgroundColor(td_containertd[6], 51);
	TextDrawFont(td_containertd[6], 1);
	TextDrawSetProportional(td_containertd[6], 1);

	td_containertd[7] = TextDrawCreate(328.496795, 155.000045, "");
	TextDrawLetterSize(td_containertd[7], 0.331932, 1.524166);
	TextDrawAlignment(td_containertd[7], 1);
	TextDrawColor(td_containertd[7], -10205185);
	TextDrawSetShadow(td_containertd[7], 0);
	TextDrawSetOutline(td_containertd[7], 0);
	TextDrawBackgroundColor(td_containertd[7], 51);
	TextDrawFont(td_containertd[7], 1);
	TextDrawSetProportional(td_containertd[7], 1);
	
	td_container[playerid][0] = CreatePlayerTextDraw(playerid, 239.414352, 182.583343, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_container[playerid][0], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_container[playerid][0], 45.915084, 50.166656);
	PlayerTextDrawAlignment(playerid, td_container[playerid][0], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][0], 80);
	PlayerTextDrawUseBox(playerid, td_container[playerid][0], true);
	PlayerTextDrawBoxColor(playerid, td_container[playerid][0], -256);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][0], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][0], 0);
	PlayerTextDrawFont(playerid, td_container[playerid][0], 5);
	PlayerTextDrawSetSelectable(playerid, td_container[playerid][0], true);
	PlayerTextDrawSetPreviewModel(playerid, td_container[playerid][0], 2729);
	PlayerTextDrawSetPreviewRot(playerid, td_container[playerid][0], 0.000000, 0.000000, 0.000000, 1.000000);

	td_container[playerid][1] = CreatePlayerTextDraw(playerid, 303.665100, 182.416671, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_container[playerid][1], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_container[playerid][1], 45.915084, 50.166656);
	PlayerTextDrawAlignment(playerid, td_container[playerid][1], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][1], 80);
	PlayerTextDrawUseBox(playerid, td_container[playerid][1], true);
	PlayerTextDrawBoxColor(playerid, td_container[playerid][1], -256);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][1], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][1], 0);
	PlayerTextDrawFont(playerid, td_container[playerid][1], 5);
	PlayerTextDrawSetSelectable(playerid, td_container[playerid][1], true);
	PlayerTextDrawSetPreviewModel(playerid, td_container[playerid][1], 2729);
	PlayerTextDrawSetPreviewRot(playerid, td_container[playerid][1], 0.000000, 0.000000, 0.000000, 1.000000);

	td_container[playerid][2] = CreatePlayerTextDraw(playerid, 368.853332, 182.250000, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_container[playerid][2], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_container[playerid][2], 45.915084, 50.166656);
	PlayerTextDrawAlignment(playerid, td_container[playerid][2], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][2], 80);
	PlayerTextDrawUseBox(playerid, td_container[playerid][2], true);
	PlayerTextDrawBoxColor(playerid, td_container[playerid][2], -256);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][2], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][2], 0);
	PlayerTextDrawFont(playerid, td_container[playerid][2], 5);
	PlayerTextDrawSetSelectable(playerid, td_container[playerid][2], true);
	PlayerTextDrawSetPreviewModel(playerid, td_container[playerid][2], 2729);
	PlayerTextDrawSetPreviewRot(playerid, td_container[playerid][2], 0.000000, 0.000000, 0.000000, 1.000000);

	td_container[playerid][3] = CreatePlayerTextDraw(playerid, 239.072052, 242.333282, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_container[playerid][3], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_container[playerid][3], 45.915084, 50.166656);
	PlayerTextDrawAlignment(playerid, td_container[playerid][3], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][3], 80);
	PlayerTextDrawUseBox(playerid, td_container[playerid][3], true);
	PlayerTextDrawBoxColor(playerid, td_container[playerid][3], -256);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][3], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][3], 0);
	PlayerTextDrawFont(playerid, td_container[playerid][3], 5);
	PlayerTextDrawSetSelectable(playerid, td_container[playerid][3], true);
	PlayerTextDrawSetPreviewModel(playerid, td_container[playerid][3], 2729);
	PlayerTextDrawSetPreviewRot(playerid, td_container[playerid][3], 0.000000, 0.000000, 0.000000, 1.000000);

	td_container[playerid][4] = CreatePlayerTextDraw(playerid, 303.791168, 240.999954, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_container[playerid][4], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_container[playerid][4], 45.915084, 50.166656);
	PlayerTextDrawAlignment(playerid, td_container[playerid][4], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][4], 80);
	PlayerTextDrawUseBox(playerid, td_container[playerid][4], true);
	PlayerTextDrawBoxColor(playerid, td_container[playerid][4], -256);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][4], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][4], 0);
	PlayerTextDrawFont(playerid, td_container[playerid][4], 5);
	PlayerTextDrawSetSelectable(playerid, td_container[playerid][4], true);
	PlayerTextDrawSetPreviewModel(playerid, td_container[playerid][4], 2729);
	PlayerTextDrawSetPreviewRot(playerid, td_container[playerid][4], 0.000000, 0.000000, 0.000000, 1.000000);

	td_container[playerid][5] = CreatePlayerTextDraw(playerid, 368.979461, 240.833312, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, td_container[playerid][5], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_container[playerid][5], 45.915084, 50.166656);
	PlayerTextDrawAlignment(playerid, td_container[playerid][5], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][5], 80);
	PlayerTextDrawUseBox(playerid, td_container[playerid][5], true);
	PlayerTextDrawBoxColor(playerid, td_container[playerid][5], -256);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][5], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][5], 0);
	PlayerTextDrawFont(playerid, td_container[playerid][5], 5);
	PlayerTextDrawSetSelectable(playerid, td_container[playerid][5], true);
	PlayerTextDrawSetPreviewModel(playerid, td_container[playerid][5], 2729);
	PlayerTextDrawSetPreviewRot(playerid, td_container[playerid][5], 0.000000, 0.000000, 0.000000, 1.000000);

	td_container[playerid][6] = CreatePlayerTextDraw(playerid, 286.455261, 187.916656, "prize1");
	PlayerTextDrawLetterSize(playerid, td_container[playerid][6], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_container[playerid][6], -46.852119, 43.749980);
	PlayerTextDrawAlignment(playerid, td_container[playerid][6], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][6], -1);
	PlayerTextDrawUseBox(playerid, td_container[playerid][6], true);
	PlayerTextDrawBoxColor(playerid, td_container[playerid][6], -256);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][6], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][6], 0);
	PlayerTextDrawFont(playerid, td_container[playerid][6], 5);
	PlayerTextDrawSetPreviewModel(playerid, td_container[playerid][6], 0);
	PlayerTextDrawSetPreviewRot(playerid, td_container[playerid][6], 0.000000, 0.000000, 0.000000, 1.000000);

	td_container[playerid][7] = CreatePlayerTextDraw(playerid, 306.476104, 185.916671, "prize2");
	PlayerTextDrawLetterSize(playerid, td_container[playerid][7], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_container[playerid][7], 39.824295, 43.749980);
	PlayerTextDrawAlignment(playerid, td_container[playerid][7], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][7], -1);
	PlayerTextDrawUseBox(playerid, td_container[playerid][7], true);
	PlayerTextDrawBoxColor(playerid, td_container[playerid][7], -256);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][7], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][7], 0);
	PlayerTextDrawFont(playerid, td_container[playerid][7], 5);
	PlayerTextDrawSetPreviewModel(playerid, td_container[playerid][7], 0);
	PlayerTextDrawSetPreviewRot(playerid, td_container[playerid][7], 0.000000, 0.000000, 0.000000, 1.000000);

	td_container[playerid][8] = CreatePlayerTextDraw(playerid, 372.132232, 185.750000, "prize3");
	PlayerTextDrawLetterSize(playerid, td_container[playerid][8], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_container[playerid][8], 39.824295, 43.749980);
	PlayerTextDrawAlignment(playerid, td_container[playerid][8], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][8], -1);
	PlayerTextDrawUseBox(playerid, td_container[playerid][8], true);
	PlayerTextDrawBoxColor(playerid, td_container[playerid][8], -256);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][8], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][8], 0);
	PlayerTextDrawFont(playerid, td_container[playerid][8], 5);
	PlayerTextDrawSetPreviewModel(playerid, td_container[playerid][8], 0);
	PlayerTextDrawSetPreviewRot(playerid, td_container[playerid][8], 0.000000, 0.000000, 0.000000, 1.000000);

	td_container[playerid][9] = CreatePlayerTextDraw(playerid, 242.414688, 245.083282, "prize4");
	PlayerTextDrawLetterSize(playerid, td_container[playerid][9], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_container[playerid][9], 39.824295, 43.749980);
	PlayerTextDrawAlignment(playerid, td_container[playerid][9], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][9], -1);
	PlayerTextDrawUseBox(playerid, td_container[playerid][9], true);
	PlayerTextDrawBoxColor(playerid, td_container[playerid][9], -256);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][9], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][9], 0);
	PlayerTextDrawFont(playerid, td_container[playerid][9], 5);
	PlayerTextDrawSetPreviewModel(playerid, td_container[playerid][9], 0);
	PlayerTextDrawSetPreviewRot(playerid, td_container[playerid][9], 0.000000, 0.000000, 0.000000, 1.000000);

	td_container[playerid][10] = CreatePlayerTextDraw(playerid, 307.133819, 244.916610, "prize5");
	PlayerTextDrawLetterSize(playerid, td_container[playerid][10], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_container[playerid][10], 39.824295, 43.749980);
	PlayerTextDrawAlignment(playerid, td_container[playerid][10], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][10], -1);
	PlayerTextDrawUseBox(playerid, td_container[playerid][10], true);
	PlayerTextDrawBoxColor(playerid, td_container[playerid][10], -256);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][10], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][10], 0);
	PlayerTextDrawFont(playerid, td_container[playerid][10], 5);
	PlayerTextDrawSetPreviewModel(playerid, td_container[playerid][10], 0);
	PlayerTextDrawSetPreviewRot(playerid, td_container[playerid][10], 0.000000, 0.000000, 0.000000, 1.000000);

	td_container[playerid][11] = CreatePlayerTextDraw(playerid, 372.321472, 244.166610, "prize6");
	PlayerTextDrawLetterSize(playerid, td_container[playerid][11], 0.000000, 0.000000);
	PlayerTextDrawTextSize(playerid, td_container[playerid][11], 39.824295, 43.749980);
	PlayerTextDrawAlignment(playerid, td_container[playerid][11], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][11], -1);
	PlayerTextDrawUseBox(playerid, td_container[playerid][11], true);
	PlayerTextDrawBoxColor(playerid, td_container[playerid][11], -256);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][11], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][11], 0);
	PlayerTextDrawFont(playerid, td_container[playerid][11], 5);
	PlayerTextDrawSetPreviewModel(playerid, td_container[playerid][11], 0);
	PlayerTextDrawSetPreviewRot(playerid, td_container[playerid][11], 0.000000, 0.000000, 0.000000, 1.000000);

	td_container[playerid][12] = CreatePlayerTextDraw(playerid, 239.882873, 221.083343, "");//text1
	PlayerTextDrawLetterSize(playerid, td_container[playerid][12], 0.101888, 0.865000);
	PlayerTextDrawAlignment(playerid, td_container[playerid][12], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][12], 0x19ff00FF);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][12], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][12], 1);
	PlayerTextDrawBackgroundColor(playerid, td_container[playerid][12], 51);
	PlayerTextDrawFont(playerid, td_container[playerid][12], 1);
	PlayerTextDrawSetProportional(playerid, td_container[playerid][12], 1);

	td_container[playerid][13] = CreatePlayerTextDraw(playerid, 304.133422, 220.916656, "");//text2
	PlayerTextDrawLetterSize(playerid, td_container[playerid][13], 0.101888, 0.865000);
	PlayerTextDrawAlignment(playerid, td_container[playerid][13], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][13], 0x19ff00FF);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][13], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][13], 1);
	PlayerTextDrawBackgroundColor(playerid, td_container[playerid][13], 51);
	PlayerTextDrawFont(playerid, td_container[playerid][13], 1);
	PlayerTextDrawSetProportional(playerid, td_container[playerid][13], 1);

	td_container[playerid][14] = CreatePlayerTextDraw(playerid, 372.600830, 220.749938, "");//text3
	PlayerTextDrawLetterSize(playerid, td_container[playerid][14], 0.101888, 0.865000);
	PlayerTextDrawAlignment(playerid, td_container[playerid][14], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][14], 0x19ff00FF);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][14], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][14], 1);
	PlayerTextDrawBackgroundColor(playerid, td_container[playerid][14], 51);
	PlayerTextDrawFont(playerid, td_container[playerid][14], 1);
	PlayerTextDrawSetProportional(playerid, td_container[playerid][14], 1);

	td_container[playerid][15] = CreatePlayerTextDraw(playerid, 241.477523, 281.833435, "");//text4
	PlayerTextDrawLetterSize(playerid, td_container[playerid][15], 0.101888, 0.865000);
	PlayerTextDrawAlignment(playerid, td_container[playerid][15], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][15], 0x19ff00FF);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][15], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][15], 1);
	PlayerTextDrawBackgroundColor(playerid, td_container[playerid][15], 51);
	PlayerTextDrawFont(playerid, td_container[playerid][15], 1);
	PlayerTextDrawSetProportional(playerid, td_container[playerid][15], 1);

	td_container[playerid][16] = CreatePlayerTextDraw(playerid, 305.727874, 280.500061, "");//text5
	PlayerTextDrawLetterSize(playerid, td_container[playerid][16], 0.101888, 0.865000);
	PlayerTextDrawAlignment(playerid, td_container[playerid][16], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][16], 0x19ff00FF);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][16], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][16], 1);
	PlayerTextDrawBackgroundColor(playerid, td_container[playerid][16], 51);
	PlayerTextDrawFont(playerid, td_container[playerid][16], 1);
	PlayerTextDrawSetProportional(playerid, td_container[playerid][16], 1);

	td_container[playerid][17] = CreatePlayerTextDraw(playerid, 369.978454, 280.916717, "");//text6
	PlayerTextDrawLetterSize(playerid, td_container[playerid][17], 0.101888, 0.865000);
	PlayerTextDrawAlignment(playerid, td_container[playerid][17], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][17], 0x19ff00FF);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][17], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][17], 1);
	PlayerTextDrawBackgroundColor(playerid, td_container[playerid][17], 51);
	PlayerTextDrawFont(playerid, td_container[playerid][17], 1);
	PlayerTextDrawSetProportional(playerid, td_container[playerid][17], 1);

	td_container[playerid][18] = CreatePlayerTextDraw(playerid, 428.697174, 155.166687, "X");
	PlayerTextDrawLetterSize(playerid, td_container[playerid][18], 0.266339, 1.115833);
	PlayerTextDrawTextSize(playerid, td_container[playerid][18], 435.725006, 0.583333);
	PlayerTextDrawAlignment(playerid, td_container[playerid][18], 1);
	PlayerTextDrawColor(playerid, td_container[playerid][18], -9857025);
	PlayerTextDrawUseBox(playerid, td_container[playerid][18], true);
	PlayerTextDrawBoxColor(playerid, td_container[playerid][18], -256);
	PlayerTextDrawSetShadow(playerid, td_container[playerid][18], 0);
	PlayerTextDrawSetOutline(playerid, td_container[playerid][18], 0);
	PlayerTextDrawBackgroundColor(playerid, td_container[playerid][18], 51);
	PlayerTextDrawFont(playerid, td_container[playerid][18], 2);
	PlayerTextDrawSetProportional(playerid, td_container[playerid][18], 1);
	PlayerTextDrawSetSelectable(playerid, td_container[playerid][18], true);