                donatetd2[playerid][89] = CreatePlayerTextDraw(playerid, 204.733307, 393.933197, "particle:lamp_shad_64");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][89], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][89], 216.000000, -4.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][89], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][89], 0x000000E4);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][89], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][89], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][89], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][89], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][89], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][89], 4);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][89], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][89], 0);

				donatetd2[playerid][88] = CreatePlayerTextDraw(playerid, 214.466705, 130.496201, "LD_SPAC:white");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][88], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][88], 193.570206, 260.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][88], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][88], 0x111111FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][88], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][88], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][88], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][88], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][88], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][88], 4);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][88], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][88], 0);

				donatetd2[playerid][87] = CreatePlayerTextDraw(playerid, 218.365906, 213.262405, "");//Eaoi?a?
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][87], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][87], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][87], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][87], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][87], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][87], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][87], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][87], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][87], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][87], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][87], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][87], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][87], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][87], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][86] = CreatePlayerTextDraw(playerid, 220.433304, 135.088806, "particle:lamp_shad_64");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][86], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][86], 185.000000, -5.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][86], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][86], 0x0000007F);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][86], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][86], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][86], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][86], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][86], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][86], 4);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][86], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][86], 0);

				donatetd2[playerid][85] = CreatePlayerTextDraw(playerid, 225.998901, 215.907104, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][85], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][85], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][85], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][85], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][85], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][85], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][85], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][85], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][85], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][85], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][85], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][85], 0);

				donatetd2[playerid][84] = CreatePlayerTextDraw(playerid, 286.734314, 323.603210, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][84], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][84], 49.000000, 55.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][84], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][84], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][84], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][84], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][84], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][84], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][84], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][84], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][84], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][84], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][84], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][84], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][83] = CreatePlayerTextDraw(playerid, 245.067505, 213.262405, "");//Aa?iue iaaue ai?aaiey
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][83], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][83], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][83], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][83], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][83], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][83], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][83], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][83], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][83], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][83], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][83], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][83], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][83], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][83], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][82] = CreatePlayerTextDraw(playerid, 252.700607, 215.907104, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][82], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][82], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][82], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][82], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][82], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][82], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][82], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][82], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][82], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][82], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][82], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][82], 0);

				donatetd2[playerid][81] = CreatePlayerTextDraw(playerid, 272.069000, 213.262405, "");//Iaaue no?aeuau
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][81], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][81], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][81], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][81], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][81], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][81], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][81], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][81], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][81], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][81], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][81], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][81], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][81], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][81], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][80] = CreatePlayerTextDraw(playerid, 279.702209, 215.907104, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][80], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][80], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][80], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][80], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][80], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][80], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][80], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][80], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][80], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][80], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][80], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][80], 0);

				donatetd2[playerid][79] = CreatePlayerTextDraw(playerid, 298.770813, 213.262405, "");//?aaei oi?aae
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][79], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][79], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][79], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][79], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][79], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][79], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][79], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][79], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][79], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][79], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][79], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][79], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][79], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][79], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][78] = CreatePlayerTextDraw(playerid, 306.403900, 215.907104, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][78], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][78], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][78], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][78], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][78], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][78], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][78], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][78], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][78], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][78], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][78], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][78], 0);

				donatetd2[playerid][77] = CreatePlayerTextDraw(playerid, 325.472412, 213.262405, "");//?aiaii aennanoa?
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][77], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][77], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][77], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][77], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][77], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][77], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][77], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][77], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][77], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][77], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][77], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][77], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][77], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][77], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][76] = CreatePlayerTextDraw(playerid, 333.105408, 215.907104, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][76], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][76], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][76], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][76], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][76], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][76], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][76], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][76], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][76], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][76], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][76], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][76], 0);

				donatetd2[playerid][75] = CreatePlayerTextDraw(playerid, 352.473907, 213.262405, "");//DIAMOND VIP
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][75], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][75], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][75], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][75], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][75], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][75], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][75], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][75], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][75], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][75], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][75], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][75], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][75], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][75], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][74] = CreatePlayerTextDraw(playerid, 360.106995, 215.907104, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][74], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][74], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][74], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][74], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][74], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][74], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][74], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][74], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][74], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][74], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][74], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][74], 0);

				donatetd2[playerid][73] = CreatePlayerTextDraw(playerid, 218.365906, 157.259003, "");//Iaiai ae?oia
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][73], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][73], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][73], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][73], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][73], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][73], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][73], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][73], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][73], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][73], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][73], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][73], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][73], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][73], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][72] = CreatePlayerTextDraw(playerid, 225.998901, 159.903702, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][72], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][72], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][72], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][72], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][72], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][72], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][72], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][72], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][72], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][72], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][72], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][72], 0);

				donatetd2[playerid][71] = CreatePlayerTextDraw(playerid, 224.832306, 158.788803, "$");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][71], 0.467500, 2.209700);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][71], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][71], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][71], 0x008000FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][71], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][71], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][71], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][71], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][71], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][71], 2);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][71], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][71], 0);

				donatetd2[playerid][70] = CreatePlayerTextDraw(playerid, 245.067505, 157.259003, "");//Iieoiea EXP
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][70], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][70], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][70], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][70], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][70], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][70], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][70], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][70], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][70], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][70], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][70], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][70], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][70], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][70], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][69] = CreatePlayerTextDraw(playerid, 252.700607, 159.903702, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][69], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][69], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][69], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][69], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][69], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][69], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][69], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][69], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][69], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][69], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][69], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][69], 0);

				donatetd2[playerid][68] = CreatePlayerTextDraw(playerid, 272.069000, 157.259003, "");//Iaoie n iynii
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][68], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][68], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][68], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][68], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][68], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][68], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][68], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][68], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][68], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][68], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][68], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][68], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][68], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][68], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][67] = CreatePlayerTextDraw(playerid, 279.702209, 159.903702, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][67], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][67], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][67], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][67], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][67], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][67], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][67], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][67], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][67], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][67], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][67], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][67], 0);

				donatetd2[playerid][66] = CreatePlayerTextDraw(playerid, 298.770813, 157.259003, "");//Aennanoa?u
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][66], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][66], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][66], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][66], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][66], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][66], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][66], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][66], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][66], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][66], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][66], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][66], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][66], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][66], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][65] = CreatePlayerTextDraw(playerid, 306.403900, 159.903702, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][65], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][65], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][65], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][65], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][65], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][65], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][65], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][65], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][65], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][65], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][65], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][65], 0);

				donatetd2[playerid][64] = CreatePlayerTextDraw(playerid, 325.472412, 157.259003, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][64], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][64], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][64], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][64], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][64], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][64], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][64], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][64], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][64], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][64], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][64], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][64], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][64], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][64], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][63] = CreatePlayerTextDraw(playerid, 333.105408, 163.903702, "");//oaeaoiiu
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][63], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][63], 10.000000, 12.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][63], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][63], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][63], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][63], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][63], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][63], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][63], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][63], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][63], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][63], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][63], 2684);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][63], 0.000000, 0.000000, 0.000000, 0.635900);

				donatetd2[playerid][62] = CreatePlayerTextDraw(playerid, 352.473907, 157.259003, "");//Naiaeiay ?aiooaoey
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][62], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][62], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][62], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][62], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][62], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][62], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][62], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][62], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][62], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][62], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][62], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][62], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][62], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][62], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][61] = CreatePlayerTextDraw(playerid, 360.106995, 159.903702, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][61], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][61], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][61], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][61], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][61], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][61], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][61], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][61], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][61], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][61], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][61], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][61], 0);

				donatetd2[playerid][60] = CreatePlayerTextDraw(playerid, 248.765701, 163.407303, "EXP");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][60], 0.327600, 1.409100);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][60], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][60], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][60], 0xFFFFFFFF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][60], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][60], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][60], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][60], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][60], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][60], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][60], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][60], 0);

				donatetd2[playerid][59] = CreatePlayerTextDraw(playerid, 282.665710, 166.714706, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][59], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][59], 14.859900, 6.109799);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][59], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][59], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][59], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][59], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][59], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][59], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][59], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][59], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][59], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][59], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][59], 1316);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][59], 86.000000, 135.000000, 0.000000, 0.490000);

				donatetd2[playerid][58] = CreatePlayerTextDraw(playerid, 301.865814, 165.337006, "0-0");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][58], 0.220300, 1.164299);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][58], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][58], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][58], 0xFFFFFFFF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][58], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][58], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][58], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][58], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][58], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][58], 2);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][58], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][58], 0);

				donatetd2[playerid][57] = CreatePlayerTextDraw(playerid, 302.199310, 163.063004, "//");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][57], 0.620500, 0.791100);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][57], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][57], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][57], 0xFFFFFFFF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][57], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][57], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][57], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][57], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][57], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][57], 2);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][57], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][57], 0);

				donatetd2[playerid][56] = CreatePlayerTextDraw(playerid, 328.665710, 166.725906, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][56], 0.125000, 0.587800);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][56], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][56], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][56], 0xFFFFFFFF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][56], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][56], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][56], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][56], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][56], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][56], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][56], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][56], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][56], 18874);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][56], 90.000000, 180.000000, 0.000000, 1.177200);

				donatetd2[playerid][55] = CreatePlayerTextDraw(playerid, 356.498901, 165.970306, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][55], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][55], 10.000000, 12.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][55], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][55], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][55], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][55], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][55], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][55], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][55], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][55], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][55], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][55], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][55], 1316);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][55], 90.000000, 0.000000, 0.000000, 1.079200);

				donatetd2[playerid][54] = CreatePlayerTextDraw(playerid, 353.365906, 239.348907, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][54], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][54], 23.000000, -21.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][54], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][54], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][54], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][54], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][54], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][54], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][54], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][54], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][54], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][54], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][54], 19177);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][54], 323.000000, 0.000000, 48.000000, 0.177200);

				donatetd2[playerid][53] = CreatePlayerTextDraw(playerid, 230.799103, 218.193405, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][53], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][53], 9.000000, 12.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][53], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][53], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][53], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][53], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][53], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][53], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][53], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][53], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][53], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][53], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][53], 19182);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][53], 0.000000, 135.000000, 0.000000, 0.177200);

				donatetd2[playerid][52] = CreatePlayerTextDraw(playerid, 220.799301, 218.193405, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][52], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][52], 9.000000, 12.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][52], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][52], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][52], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][52], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][52], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][52], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][52], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][52], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][52], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][52], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][52], 19182);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][52], 0.000000, 229.000000, 0.000000, 0.177200);

				donatetd2[playerid][51] = CreatePlayerTextDraw(playerid, 226.332306, 235.026703, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][51], 0.432000, -1.154199);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][51], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][51], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][51], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][51], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][51], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][51], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][51], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][51], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][51], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][51], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][51], 0);

				donatetd2[playerid][50] = CreatePlayerTextDraw(playerid, 250.032104, 221.137802, "IIIIII_+");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][50], 0.194000, 0.990100);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][50], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][50], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][50], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][50], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][50], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][50], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][50], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][50], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][50], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][50], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][50], 0);

				donatetd2[playerid][49] = CreatePlayerTextDraw(playerid, 278.298798, 218.034103, "-_-");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][49], 0.375200, 1.488000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][49], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][49], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][49], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][49], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][49], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][49], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][49], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][49], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][49], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][49], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][49], 0);

				donatetd2[playerid][48] = CreatePlayerTextDraw(playerid, 283.632202, 216.919205, "I~n~I");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][48], 0.204600, 1.039800);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][48], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][48], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][48], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][48], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][48], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][48], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][48], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][48], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][48], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][48], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][48], 0);

				donatetd2[playerid][47] = CreatePlayerTextDraw(playerid, 305.498901, 220.352707, "O");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][47], 0.458900, 1.790699);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][47], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][47], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][47], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][47], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][47], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][47], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][47], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][47], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][47], 2);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][47], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][47], 0);

				donatetd2[playerid][46] = CreatePlayerTextDraw(playerid, 309.731995, 235.774704, "i");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][46], 0.356000, -2.514800);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][46], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][46], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][46], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][46], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][46], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][46], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][46], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][46], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][46], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][46], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][46], 0);

				donatetd2[playerid][45] = CreatePlayerTextDraw(playerid, 330.598907, 216.693207, "OOO~n~OOO");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][45], 0.172600, 0.957000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][45], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][45], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][45], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][45], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][45], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][45], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][45], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][45], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][45], 2);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][45], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][45], 0);

				donatetd2[playerid][44] = CreatePlayerTextDraw(playerid, 358.499207, 218.748901, "VIP");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][44], 0.266900, 1.118800);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][44], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][44], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][44], 0x000000C1);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][44], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][44], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][44], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][44], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][44], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][44], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][44], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][44], 0);

				donatetd2[playerid][43] = CreatePlayerTextDraw(playerid, 218.365906, 269.065796, "");//?oeaoea
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][43], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][43], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][43], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][43], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][43], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][43], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][43], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][43], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][43], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][43], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][43], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][43], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][43], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][43], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][42] = CreatePlayerTextDraw(playerid, 225.998901, 271.710510, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][42], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][42], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][42], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][42], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][42], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][42], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][42], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][42], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][42], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][42], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][42], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][42], 0);

				donatetd2[playerid][41] = CreatePlayerTextDraw(playerid, 245.067505, 269.065796, "");//Iieoiea iaoeiu
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][41], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][41], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][41], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][41], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][41], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][41], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][41], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][41], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][41], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][41], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][41], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][41], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][41], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][41], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][40] = CreatePlayerTextDraw(playerid, 252.700607, 271.710510, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][40], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][40], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][40], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][40], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][40], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][40], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][40], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][40], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][40], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][40], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][40], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][40], 0);

				donatetd2[playerid][39] = CreatePlayerTextDraw(playerid, 272.069000, 269.065796, "");//Niaia iiea
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][39], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][39], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][39], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][39], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][39], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][39], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][39], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][39], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][39], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][39], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][39], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][39], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][39], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][39], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][38] = CreatePlayerTextDraw(playerid, 279.702209, 271.710510, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][38], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][38], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][38], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][38], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][38], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][38], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][38], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][38], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][38], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][38], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][38], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][38], 0);

				donatetd2[playerid][37] = CreatePlayerTextDraw(playerid, 298.770813, 269.065796, "");//ia?aiiniay eaaea
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][37], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][37], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][37], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][37], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][37], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][37], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][37], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][37], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][37], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][37], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][37], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][37], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][37], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][37], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][36] = CreatePlayerTextDraw(playerid, 306.403900, 271.710510, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][36], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][36], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][36], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][36], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][36], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][36], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][36], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][36], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][36], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][36], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][36], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][36], 0);

				donatetd2[playerid][35] = CreatePlayerTextDraw(playerid, 325.472412, 269.065796, "");//Iaaue ai?aaiey
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][35], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][35], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][35], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][35], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][35], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][35], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][35], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][35], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][35], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][35], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][35], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][35], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][35], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][35], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][34] = CreatePlayerTextDraw(playerid, 333.105408, 271.710510, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][34], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][34], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][34], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][34], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][34], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][34], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][34], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][34], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][34], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][34], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][34], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][34], 0);

				donatetd2[playerid][33] = CreatePlayerTextDraw(playerid, 352.473907, 269.065796, "");//Na?ineou i?iaaa
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][33], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][33], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][33], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][33], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][33], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][33], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][33], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][33], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][33], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][33], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][33], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][33], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][33], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][33], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][32] = CreatePlayerTextDraw(playerid, 360.106995, 271.710510, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][32], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][32], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][32], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][32], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][32], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][32], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][32], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][32], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][32], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][32], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][32], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][32], 0);

				donatetd2[playerid][31] = CreatePlayerTextDraw(playerid, 221.065704, 269.918396, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][31], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][31], 19.000000, 23.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][31], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][31], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][31], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][31], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][31], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][31], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][31], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][31], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][31], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][31], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][31], 19941);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][31], 334.000000, 0.000000, 0.000000, 0.735000);

				donatetd2[playerid][30] = CreatePlayerTextDraw(playerid, 278.365906, 164.681503, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][30], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][30], 9.000000, 12.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][30], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][30], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][30], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][30], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][30], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][30], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][30], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][30], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][30], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][30], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][30], 19182);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][30], 90.000000, 0.000000, 0.000000, 0.135399);

				donatetd2[playerid][29] = CreatePlayerTextDraw(playerid, 284.265808, 171.218506, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][29], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][29], 5.349800, 4.199900);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][29], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][29], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][29], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][29], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][29], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][29], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][29], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][29], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][29], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][29], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][29], 19182);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][29], 90.000000, 0.000000, 0.000000, 0.135399);

				donatetd2[playerid][28] = CreatePlayerTextDraw(playerid, 288.565796, 162.248306, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][28], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][28], -5.050000, 3.490000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][28], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][28], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][28], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][28], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][28], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][28], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][28], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][28], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][28], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][28], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][28], 19182);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][28], 0.000000, 22.000000, 0.000000, 0.135399);

				donatetd2[playerid][27] = CreatePlayerTextDraw(playerid, 247.965805, 270.418396, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][27], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][27], 19.000000, 23.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][27], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][27], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][27], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][27], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][27], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][27], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][27], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][27], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][27], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][27], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][27], 10281);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][27], 358.000000, 0.000000, 180.000000, 0.510900);

				donatetd2[playerid][26] = CreatePlayerTextDraw(playerid, 274.665802, 270.662903, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][26], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][26], 19.000000, 23.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][26], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][26], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][26], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][26], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][26], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][26], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][26], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][26], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][26], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][26], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][26], 1314);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][26], 358.000000, 0.000000, 180.000000, 1.047799);

				donatetd2[playerid][25] = CreatePlayerTextDraw(playerid, 360.365814, 160.607407, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][25], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][25], 13.000000, 16.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][25], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][25], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][25], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][25], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][25], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][25], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][25], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][25], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][25], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][25], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][25], 1316);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][25], 90.000000, 0.000000, 0.000000, 1.079200);

				donatetd2[playerid][24] = CreatePlayerTextDraw(playerid, 219.399002, 167.503601, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][24], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][24], 15.000000, 15.109900);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][24], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][24], 0xFFBAFFFF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][24], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][24], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][24], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][24], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][24], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][24], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][24], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][24], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][24], 19941);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][24], 0.000000, 134.000000, 0.000000, 0.469099);

				donatetd2[playerid][23] = CreatePlayerTextDraw(playerid, 224.099106, 174.436905, "x2");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][23], 0.142900, 0.749499);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][23], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][23], 2);
				PlayerTextDrawColor(playerid, donatetd2[playerid][23], 0x0000009C);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][23], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][23], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][23], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][23], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][23], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][23], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][23], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][23], 0);

				donatetd2[playerid][22] = CreatePlayerTextDraw(playerid, 302.965912, 265.399902, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][22], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][22], 16.000000, 31.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][22], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][22], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][22], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][22], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][22], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][22], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][22], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][22], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][22], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][22], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][22], 19636);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][22], 333.000000, 0.000000, 68.000000, 1.047799);

				donatetd2[playerid][21] = CreatePlayerTextDraw(playerid, 328.532410, 270.777802, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][21], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][21], 18.000000, 22.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][21], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][21], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][21], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][21], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][21], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][21], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][21], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][21], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][21], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][21], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][21], 1581);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][21], 0.000000, 0.000000, 185.000000, 1.047799);

				donatetd2[playerid][20] = CreatePlayerTextDraw(playerid, 328.532410, 270.777802, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][20], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][20], 18.000000, 22.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][20], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][20], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][20], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][20], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][20], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][20], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][20], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][20], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][20], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][20], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][20], 1581);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][20], 0.000000, 0.000000, 185.000000, 1.047799);

				donatetd2[playerid][19] = CreatePlayerTextDraw(playerid, 357.565796, 274.577911, "hud:skipicon");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][19], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][19], 15.000000, 17.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][19], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][19], 0xFFFFFFFF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][19], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][19], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][19], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][19], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][19], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][19], 4);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][19], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][19], 0);

				donatetd2[playerid][18] = CreatePlayerTextDraw(playerid, 379.675598, 213.262405, "");//TITAN VIP
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][18], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][18], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][18], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][18], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][18], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][18], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][18], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][18], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][18], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][18], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][18], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][18], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][18], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][18], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][17] = CreatePlayerTextDraw(playerid, 387.308807, 215.907104, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][17], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][17], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][17], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][17], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][17], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][17], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][17], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][17], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][17], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][17], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][17], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][17], 0);

				donatetd2[playerid][16] = CreatePlayerTextDraw(playerid, 379.675598, 157.259003, "");//Iyoe cia?iue iiia?
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][16], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][16], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][16], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][16], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][16], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][16], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][16], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][16], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][16], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][16], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][16], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][16], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][16], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][16], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][15] = CreatePlayerTextDraw(playerid, 387.308807, 159.903702, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][15], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][15], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][15], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][15], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][15], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][15], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][15], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][15], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][15], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][15], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][15], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][15], 0);

				donatetd2[playerid][14] = CreatePlayerTextDraw(playerid, 379.675598, 269.065796, "");//Ana eeoaicee
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][14], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][14], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][14], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][14], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][14], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][14], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][14], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][14], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][14], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][14], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][14], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][14], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][14], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][14], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][13] = CreatePlayerTextDraw(playerid, 387.308807, 271.710510, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][13], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][13], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][13], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][13], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][13], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][13], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][13], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][13], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][13], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][13], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][13], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][13], 0);

				donatetd2[playerid][12] = CreatePlayerTextDraw(playerid, 392.233093, 164.710907, "XXXXX~n~NUMBER");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][12], 0.156200, 0.591799);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][12], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][12], 2);
				PlayerTextDrawColor(playerid, donatetd2[playerid][12], 0xFFFFFFFF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][12], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][12], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][12], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][12], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][12], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][12], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][12], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][12], 0);

				donatetd2[playerid][11] = CreatePlayerTextDraw(playerid, 391.566498, 219.881302, "MADEYRA");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][11], 0.156200, 0.591799);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][11], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][11], 2);
				PlayerTextDrawColor(playerid, donatetd2[playerid][11], 0xFFFFFFFF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][11], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][11], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][11], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][11], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][11], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][11], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][11], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][11], 0);

				donatetd2[playerid][10] = CreatePlayerTextDraw(playerid, 391.966614, 222.481506, "VIP");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][10], 0.285600, 1.496099);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][10], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][10], 2);
				PlayerTextDrawColor(playerid, donatetd2[playerid][10], 0xFFFFFFFF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][10], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][10], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][10], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][10], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][10], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][10], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][10], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][10], 0);

				donatetd2[playerid][9] = CreatePlayerTextDraw(playerid, 381.665497, 270.010000, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][9], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][9], 21.000000, 25.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][9], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][9], 0xFFFFFFFF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][9], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][9], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][9], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][9], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][9], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][9], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][9], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][9], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][9], 1318);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][9], 0.000000, 180.000000, 90.000000, 1.000000);

				donatetd2[playerid][8] = CreatePlayerTextDraw(playerid, 257.834106, 323.718201, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][8], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][8], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][8], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][8], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][8], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][8], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][8], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][8], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][8], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][8], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][8], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][8], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][8], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][8], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][7] = CreatePlayerTextDraw(playerid, 341.967499, 324.347809, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][7], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][7], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][7], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][7], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][7], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][7], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][7], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][7], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][7], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][7], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][7], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][7], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][7], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][7], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][6] = CreatePlayerTextDraw(playerid, 218.600891, 323.572815, "");//Niaieou iee
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][6], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][6], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][6], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][6], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][6], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][6], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][6], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][6], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][6], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][6], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][6], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][6], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][6], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][6], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][5] = CreatePlayerTextDraw(playerid, 226.572113, 326.044800, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][5], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][5], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][5], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][5], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][5], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][5], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][5], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][5], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][5], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][5], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][5], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][5], 0);

				donatetd2[playerid][4] = CreatePlayerTextDraw(playerid, 226.465942, 326.600952, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][4], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][4], 9.000000, 12.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][4], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][4], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][4], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][4], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][4], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][4], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][4], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][4], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][4], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][4], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][4], 19182);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][4], 90.000000, 0.000000, 0.000000, 0.130344);

				donatetd2[playerid][3] = CreatePlayerTextDraw(playerid, 224.032562, 344.452667, "");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][3], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][3], 14.000000, -12.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][3], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][3], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][3], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][3], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][3], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][3], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][3], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][3], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][3], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][3], 0);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][3], 19177);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][3], 200.000000, 0.000000, 48.000000, 0.177200);

				donatetd2[playerid][2] = CreatePlayerTextDraw(playerid, 379.869995, 324.287598, "");//Niyou aa?i
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][2], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][2], 24.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][2], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][2], 0x00000070);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][2], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][2], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][2], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][2], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][2], 0x00000000);
				PlayerTextDrawFont(playerid, donatetd2[playerid][2], 5);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][2], 0);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][2], 1);
				PlayerTextDrawSetPreviewModel(playerid, donatetd2[playerid][2], 2729);
				PlayerTextDrawSetPreviewRot(playerid, donatetd2[playerid][2], 0.000000, 0.000000, 0.000000, 0.620400);

				donatetd2[playerid][1] = CreatePlayerTextDraw(playerid, 387.841217, 326.759583, "U");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][1], 0.460900, -1.025599);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][1], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][1], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][1], 0x00000093);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][1], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][1], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][1], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][1], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][1], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][1], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][1], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][1], 0);

				donatetd2[playerid][0] = CreatePlayerTextDraw(playerid, 391.000000, 327.303619, "!");
				PlayerTextDrawLetterSize(playerid, donatetd2[playerid][0], 0.437000, 2.093629);
				PlayerTextDrawTextSize(playerid, donatetd2[playerid][0], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donatetd2[playerid][0], 1);
				PlayerTextDrawColor(playerid, donatetd2[playerid][0], 0xFF0000FF);
				PlayerTextDrawUseBox(playerid, donatetd2[playerid][0], 0);
				PlayerTextDrawBoxColor(playerid, donatetd2[playerid][0], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donatetd2[playerid][0], 0);
				PlayerTextDrawSetOutline(playerid, donatetd2[playerid][0], 0);
				PlayerTextDrawBackgroundColor(playerid, donatetd2[playerid][0], 0x000000FF);
				PlayerTextDrawFont(playerid, donatetd2[playerid][0], 1);
				PlayerTextDrawSetProportional(playerid, donatetd2[playerid][0], 1);
				PlayerTextDrawSetSelectable(playerid, donatetd2[playerid][0], 0);



				donate_player[playerid][41] = CreatePlayerTextDraw(playerid, 344.533173, 376.510986, "LD_BEAT:chit");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][41], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][41], 28.000000, 34.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][41], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][41], 0x555555FF);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][41], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][41], 0xFFFFFFFF80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][41], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][41], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][41], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][41], 4);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][41], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][41], 0);

				donate_player[playerid][40] = CreatePlayerTextDraw(playerid, 380.934784, 376.510986, "LD_BEAT:chit");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][40], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][40], 28.000000, 34.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][40], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][40], 0x555555FF);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][40], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][40], 0xFFFFFFFF80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][40], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][40], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][40], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][40], 4);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][40], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][40], 0);

				donate_player[playerid][39] = CreatePlayerTextDraw(playerid, 357.966675, 382.118347, "LD_SPAC:white");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][39], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][39], 37.859997, 22.699993);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][39], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][39], 0x555555FF);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][39], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][39], 0xFFFFFFFF80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][39], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][39], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][39], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][39], 4);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][39], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][39], 0);

				donate_player[playerid][38] = CreatePlayerTextDraw(playerid, 359.200043, 385.807434, "CLOSE");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][38], 0.400000, 1.600000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][38], 397.200043, 16.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][38], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][38], 0xFFFFFFFFFFFFFFFF);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][38], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][38], 0xFFFFFFFF80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][38], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][38], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][38], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][38], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][38], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][38], 1);

			    donate_player[playerid][37] = CreatePlayerTextDraw(playerid, 211.533203, 119.325699, "LD_BEAT:chit");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][37], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][37], 19.000000, 21.899900);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][37], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][37], PlayerInfo[playerid][pColorInv]);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][37], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][37], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][37], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][37], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][37], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][37], 4);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][37], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][37], 0);

				donate_player[playerid][36] = CreatePlayerTextDraw(playerid, 392.100006, 119.414703, "LD_BEAT:chit");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][36], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][36], 19.000000, 21.899900);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][36], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][36], PlayerInfo[playerid][pColorInv]);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][36], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][36], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][36], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][36], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][36], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][36], 4);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][36], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][36], 0);

				donate_player[playerid][35] = CreatePlayerTextDraw(playerid, 220.733307, 122.844299, "LD_SPAC:white");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][35], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][35], 182.000000, 19.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][35], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][35], PlayerInfo[playerid][pColorInv]);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][35], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][35], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][35], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][35], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][35], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][35], 4);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][35], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][35], 0);

				donate_player[playerid][34] = CreatePlayerTextDraw(playerid, 214.466705, 130.496201, "LD_SPAC:white");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][34], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][34], 193.570206, 12.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][34], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][34], 0x111111FF);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][34], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][34], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][34], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][34], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][34], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][34], 4);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][34], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][34], 0);

				donate_player[playerid][33] = CreatePlayerTextDraw(playerid, 343.699310, 355.756104, "LD_SPAC:WHITE");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][33], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][33], 23.000000, 21.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][33], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][33], PlayerInfo[playerid][pColorInv]);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][33], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][33], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][33], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][33], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][33], 0x00000000);
				PlayerTextDrawFont(playerid, donate_player[playerid][33], 5);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][33], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][33], 1);
				PlayerTextDrawSetPreviewModel(playerid, donate_player[playerid][33], 19177);
				PlayerTextDrawSetPreviewRot(playerid, donate_player[playerid][33], 90.000000, 286.000000, 90.000000, 0.177200);

				donate_player[playerid][32] = CreatePlayerTextDraw(playerid, 257.999207, 355.337708, "LD_SPAC:WHITE");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][32], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][32], 23.000000, 21.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][32], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][32], PlayerInfo[playerid][pColorInv]);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][32], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][32], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][32], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][32], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][32], 0x00000000);
				PlayerTextDrawFont(playerid, donate_player[playerid][32], 5);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][32], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][32], 1);
				PlayerTextDrawSetPreviewModel(playerid, donate_player[playerid][32], 19177);
				PlayerTextDrawSetPreviewRot(playerid, donate_player[playerid][32], 90.000000, 76.000000, 90.000000, 0.177200);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][31] = CreatePlayerTextDraw(playerid, 230.666702, 297.248199, FixText("ÐÓËÅÒÊÀ"));
				}
				else {
				    donate_player[playerid][31] = CreatePlayerTextDraw(playerid, 230.666702, 297.248199, "ROULETTE");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][31], 0.132799, 0.575299);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][31], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][31], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][31], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][31], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][31], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][31], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][31], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][31], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][31], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][31], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][31], 0);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][30] = CreatePlayerTextDraw(playerid, 257.000214, 297.433502, FixText("ÏÎÊÓÏÊÀ~n~ÌÀØÈÍÛ"));
				}
				else {
				    donate_player[playerid][30] = CreatePlayerTextDraw(playerid, 257.000214, 297.433502, "CAR_BUY");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][30], 0.132799, 0.575299);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][30], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][30], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][30], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][30], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][30], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][30], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][30], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][30], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][30], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][30], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][30], 0);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][29] = CreatePlayerTextDraw(playerid, 284.633514, 297.318604, FixText("ÑÌÅÍÈÒÜ~n~ÏÎË"));
				}
				else {
				    donate_player[playerid][29] = CreatePlayerTextDraw(playerid, 284.633514, 297.318604, "SEX");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][29], 0.132799, 0.575299);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][29], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][29], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][29], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][29], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][29], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][29], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][29], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][29], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][29], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][29], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][29], 0);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][28] = CreatePlayerTextDraw(playerid, 311.266907, 297.318604, FixText("ÏÅÐÅÍÎÑÍÛÅ~n~ËÀÂÊÈ"));
				}
				else {
				    donate_player[playerid][28] = CreatePlayerTextDraw(playerid, 311.266907, 297.318604, "PORTABLE~n~SHOP");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][28], 0.132799, 0.575299);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][28], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][28], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][28], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][28], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][28], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][28], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][28], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][28], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][28], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][28], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][28], 0);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][27] = CreatePlayerTextDraw(playerid, 337.766815, 297.333405, FixText("ÍÀÂÛÊ~n~ÂÎÄÈÒÅËß"));
				}
				else {
				    donate_player[playerid][27] = CreatePlayerTextDraw(playerid, 337.766815, 297.333405, "DRIVING~n~SKILL~n~UP");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][27], 0.132799, 0.575299);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][27], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][27], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][27], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][27], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][27], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][27], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][27], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][27], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][27], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][27], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][27], 0);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][26] = CreatePlayerTextDraw(playerid, 364.533508, 297.218506, FixText("ÑÁÐÎÑÈÒÜ~n~ÏÐÎÁÅÃ"));
				}
				else {
				    donate_player[playerid][26] = CreatePlayerTextDraw(playerid, 364.533508, 297.218506, "RESET~n~MILEAGE");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][26], 0.132799, 0.575299);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][26], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][26], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][26], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][26], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][26], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][26], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][26], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][26], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][26], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][26], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][26], 0);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][25] = CreatePlayerTextDraw(playerid, 392.000000, 297.418610, FixText("ÎÑÒÀËÜÍÎÅ"));
				}
				else {
				    donate_player[playerid][25] = CreatePlayerTextDraw(playerid, 392.000000, 297.418610, "OTHER");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][25], 0.132799, 0.575299);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][25], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][25], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][25], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][25], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][25], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][25], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][25], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][25], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][25], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][25], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][25], 0);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][24] = CreatePlayerTextDraw(playerid, 230.666702, 241.444702, FixText("ÒÂÈÍ~n~ÒÓÐÁÎ"));
				}
				else {
				    donate_player[playerid][24] = CreatePlayerTextDraw(playerid, 230.666702, 241.444702, "TWIN~n~TURBO");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][24], 0.132699, 0.575200);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][24], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][24], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][24], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][24], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][24], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][24], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][24], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][24], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][24], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][24], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][24], 0);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][23] = CreatePlayerTextDraw(playerid, 257.000214, 241.630005, FixText("ÂÅ×ÍÛÉ~n~ÍÀÂÛÊ~n~ÂÎÆÄÅÍÈß"));
				}
				else {
				    donate_player[playerid][23] = CreatePlayerTextDraw(playerid, 257.000214, 241.630005, "ETERNAL~n~CAR_SKILL");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][23], 0.132699, 0.575200);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][23], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][23], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][23], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][23], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][23], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][23], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][23], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][23], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][23], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][23], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][23], 0);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][22] = CreatePlayerTextDraw(playerid, 284.833496, 241.515106, FixText("ÑÊÈËËÛ~n~ÎÐÓÆÈß"));
				}
				else {
				    donate_player[playerid][22] = CreatePlayerTextDraw(playerid, 284.833496, 241.515106, "SHOTING~n~SKILLS");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][22], 0.132699, 0.575200);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][22], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][22], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][22], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][22], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][22], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][22], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][22], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][22], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][22], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][22], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][22], 0);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][21] = CreatePlayerTextDraw(playerid, 311.266907, 241.515106, FixText("ÐÀÄÈÎ~n~ÓÏÐÀÂËÅÍÈÅ."));
				}
				else {
				    donate_player[playerid][21] = CreatePlayerTextDraw(playerid, 311.266907, 241.515106, "RADIO~n~CONTROLLED");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][21], 0.132699, 0.575200);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][21], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][21], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][21], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][21], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][21], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][21], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][21], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][21], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][21], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][21], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][21], 0);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][20] = CreatePlayerTextDraw(playerid, 337.866791, 241.529907, FixText("6~n~ß×ÅÅÊ~n~ÈÍÂÅÍÒÀÐß"));
				}
				else {
				    donate_player[playerid][20] = CreatePlayerTextDraw(playerid, 337.866791, 241.529907, "OPEN 6~n~CELLS IN~n~INVENTORY");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][20], 0.132699, 0.575200);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][20], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][20], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][20], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][20], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][20], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][20], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][20], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][20], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][20], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][20], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][20], 0);

				donate_player[playerid][19] = CreatePlayerTextDraw(playerid, 364.533508, 241.415100, "PREMIUM~n~VIP");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][19], 0.132699, 0.575200);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][19], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][19], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][19], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][19], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][19], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][19], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][19], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][19], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][19], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][19], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][19], 0);

				donate_player[playerid][18] = CreatePlayerTextDraw(playerid, 392.000000, 241.615204, "MADEYRA~n~VIP");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][18], 0.132699, 0.575200);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][18], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][18], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][18], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][18], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][18], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][18], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][18], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][18], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][18], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][18], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][18], 0);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][17] = CreatePlayerTextDraw(playerid, 230.666702, 185.641296, FixText("ÄÅÍÜÃÈ"));
				}
				else {
				    donate_player[playerid][17] = CreatePlayerTextDraw(playerid, 230.666702, 185.641296, "MONEY");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][17], 0.132699, 0.575200);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][17], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][17], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][17], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][17], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][17], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][17], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][17], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][17], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][17], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][17], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][17], 0);

                if(PlayerInfo[playerid][pLanguage]) donate_player[playerid][16] = CreatePlayerTextDraw(playerid, 257.000214, 185.826599, FixText("ÈÃÐÎÂÎÉ ÎÏÛÒ"));
				donate_player[playerid][16] = CreatePlayerTextDraw(playerid, 257.000214, 185.826599, "EXP");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][16], 0.132699, 0.575200);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][16], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][16], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][16], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][16], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][16], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][16], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][16], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][16], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][16], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][16], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][16], 0);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][15] = CreatePlayerTextDraw(playerid, 284.833496, 185.711700, FixText("ÒÅËÅÔÎÍÛ"));
				}
				else {
				    donate_player[playerid][15] = CreatePlayerTextDraw(playerid, 284.833496, 185.711700, "PHONE");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][15], 0.132699, 0.575200);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][15], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][15], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][15], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][15], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][15], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][15], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][15], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][15], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][15], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][15], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][15], 0);

				if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][14] = CreatePlayerTextDraw(playerid, 311.266907, 185.711700, FixText("ÀÊÑÅÑÑÓÀÐÛ"));
				}
				else {
				    donate_player[playerid][14] = CreatePlayerTextDraw(playerid, 311.266907, 185.711700, "ACCESSORIES");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][14], 0.132699, 0.575200);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][14], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][14], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][14], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][14], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][14], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][14], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][14], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][14], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][14], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][14], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][14], 0);

                if(PlayerInfo[playerid][pLanguage]) {
				    donate_player[playerid][13] = CreatePlayerTextDraw(playerid, 337.866791, 185.726501, FixText("ËÈÖÅÍÇÈÈ"));
				}
				else {
				    donate_player[playerid][13] = CreatePlayerTextDraw(playerid, 337.866791, 185.726501, "LICENSES");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][13], 0.132699, 0.575200);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][13], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][13], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][13], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][13], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][13], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][13], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][13], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][13], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][13], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][13], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][13], 0);

				if(PlayerInfo[playerid][pLanguage]) {
        		donate_player[playerid][12] = CreatePlayerTextDraw(playerid, 364.533508, 185.611603, FixText("ÑÅÌÅÉÍÀß~n~ÐÅÏÓÒÀÖÈß"));
				}
				else {
				    donate_player[playerid][12] = CreatePlayerTextDraw(playerid, 364.533508, 185.611603, "FAMILY~n~REPUTATION");
				}
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][12], 0.132699, 0.575200);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][12], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][12], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][12], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][12], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][12], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][12], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][12], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][12], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][12], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][12], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][12], 0);

				if(PlayerInfo[playerid][pLanguage]) donate_player[playerid][11] = CreatePlayerTextDraw(playerid, 392.000000, 185.811707, FixText("5-ÇÍÀ×ÍÛÉ~n~ÍÎÌÅÐ"));
				else donate_player[playerid][11] = CreatePlayerTextDraw(playerid, 392.000000, 185.811707, "5-DIGIT~n~NUMBER");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][11], 0.132699, 0.575200);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][11], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][11], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][11], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][11], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][11], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][11], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][11], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][11], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][11], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][11], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][11], 0);

				if(PlayerInfo[playerid][pLanguage]) donate_player[playerid][10] = CreatePlayerTextDraw(playerid, 311.166595, 134.626007, FixText("ÄÎÍÀÒ_ÌÀÃÀÇÈÍ"));
				else donate_player[playerid][10] = CreatePlayerTextDraw(playerid, 311.166595, 134.626007, "DONATE_MENU");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][10], 0.324000, 1.243100);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][10], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][10], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][10], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][10], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][10], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][10], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][10], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][10], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][10], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][10], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][10], 0);

				if(PlayerInfo[playerid][pLanguage]) donate_player[playerid][9] = CreatePlayerTextDraw(playerid, 231.066711, 351.718719, FixText("ÑÌÅÍÈÒÜ_ÈÌß"));
				else donate_player[playerid][9] = CreatePlayerTextDraw(playerid, 231.066711, 351.718719, "CHANGE_NAME");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][9], 0.132798, 0.575299);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][9], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][9], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][9], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][9], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][9], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][9], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][9], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][9], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][9], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][9], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][9], 0);

				if(PlayerInfo[playerid][pLanguage]) donate_player[playerid][8] = CreatePlayerTextDraw(playerid, 392.335815, 352.433502, FixText("ÑÍßÒÜ_ÂÀÐÍ"));
				else donate_player[playerid][8] = CreatePlayerTextDraw(playerid, 392.335815, 352.433502, "REMOVE_WARN");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][8], 0.132798, 0.575299);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][8], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][8], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][8], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][8], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][8], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][8], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][8], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][8], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][8], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][8], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][8], 0);

				donate_player[playerid][7] = CreatePlayerTextDraw(playerid, 259.634094, 323.421906, "");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][7], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][7], 21.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][7], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][7], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][7], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][7], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][7], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][7], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][7], 0x00000000);
				PlayerTextDrawFont(playerid, donate_player[playerid][7], 5);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][7], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][7], 0);
				PlayerTextDrawSetPreviewModel(playerid, donate_player[playerid][7], 1649);
				PlayerTextDrawSetPreviewRot(playerid, donate_player[playerid][7], 0.000000, 0.000000, 90.000000, 2.000000);

				donate_player[playerid][6] = CreatePlayerTextDraw(playerid, 290.334106, 324.566406, "");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][6], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][6], 43.000000, 52.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][6], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][6], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][6], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][6], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][6], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][6], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][6], 0x00000000);
				PlayerTextDrawFont(playerid, donate_player[playerid][6], 5);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][6], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][6], 0);
				PlayerTextDrawSetPreviewModel(playerid, donate_player[playerid][6], 1649);
				PlayerTextDrawSetPreviewRot(playerid, donate_player[playerid][6], 0.000000, 0.000000, 90.000000, 2.000000);

				donate_player[playerid][5] = CreatePlayerTextDraw(playerid, 343.800903, 323.851501, "");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][5], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][5], 21.000000, 26.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][5], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][5], 0xC0C0C0FF);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][5], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][5], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][5], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][5], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][5], 0x00000000);
				PlayerTextDrawFont(playerid, donate_player[playerid][5], 5);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][5], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][5], 0);
				PlayerTextDrawSetPreviewModel(playerid, donate_player[playerid][5], 1649);
				PlayerTextDrawSetPreviewRot(playerid, donate_player[playerid][5], 0.000000, 0.000000, 90.000000, 2.000000);

				donate_player[playerid][4] = CreatePlayerTextDraw(playerid, 284.533173, 376.510986, "LD_BEAT:chit");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][4], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][4], 28.000000, 34.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][4], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][4], PlayerInfo[playerid][pColorInv]);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][4], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][4], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][4], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][4], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][4], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][4], 4);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][4], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][4], 0);

				donate_player[playerid][3] = CreatePlayerTextDraw(playerid, 310.934784, 376.510986, "LD_BEAT:chit");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][3], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][3], 28.000000, 34.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][3], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][3], PlayerInfo[playerid][pColorInv]);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][3], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][3], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][3], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][3], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][3], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][3], 4);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][3], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][3], 0);

				donate_player[playerid][2] = CreatePlayerTextDraw(playerid, 297.966675, 382.118347, "LD_SPAC:white");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][2], 0.000000, 0.000000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][2], 27.859997, 22.699993);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][2], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][2], PlayerInfo[playerid][pColorInv]);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][2], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][2], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][2], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][2], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][2], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][2], 4);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][2], 0);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][2], 0);

				donate_player[playerid][1] = CreatePlayerTextDraw(playerid, 301.200043, 385.807434, "BUY");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][1], 0.400000, 1.600000);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][1], 327.200043, 16.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][1], 1);
				PlayerTextDrawColor(playerid, donate_player[playerid][1], 0xFFFFFFFF);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][1], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][1], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][1], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][1], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][1], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][1], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][1], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][1], 1);

				donate_player[playerid][0] = CreatePlayerTextDraw(playerid, 311.666595, 314.404266, "");
				PlayerTextDrawLetterSize(playerid, donate_player[playerid][0], 0.176033, 0.977569);
				PlayerTextDrawTextSize(playerid, donate_player[playerid][0], 1280.000000, 1280.000000);
				PlayerTextDrawAlignment(playerid, donate_player[playerid][0], 2);
				PlayerTextDrawColor(playerid, donate_player[playerid][0], 0xC0C0C068);
				PlayerTextDrawUseBox(playerid, donate_player[playerid][0], 0);
				PlayerTextDrawBoxColor(playerid, donate_player[playerid][0], 0x80808080);
				PlayerTextDrawSetShadow(playerid, donate_player[playerid][0], 0);
				PlayerTextDrawSetOutline(playerid, donate_player[playerid][0], 0);
				PlayerTextDrawBackgroundColor(playerid, donate_player[playerid][0], 0x000000FF);
				PlayerTextDrawFont(playerid, donate_player[playerid][0], 1);
				PlayerTextDrawSetProportional(playerid, donate_player[playerid][0], 1);
				PlayerTextDrawSetSelectable(playerid, donate_player[playerid][0], 0);