	debugglobal[1] = TextDrawCreate(203.133362, 347.448883, "LD_SPAC:white");
	TextDrawLetterSize(debugglobal[1], 0.000000, 0.000000);
	TextDrawTextSize(debugglobal[1], 215.500061, 87.318527);
	TextDrawAlignment(debugglobal[1], 1);
	TextDrawColor(debugglobal[1], 0x555555FF);
	TextDrawUseBox(debugglobal[1], 0);
	TextDrawBoxColor(debugglobal[1], 0x80808080);
	TextDrawSetShadow(debugglobal[1], 0);
	TextDrawSetOutline(debugglobal[1], 0);
	TextDrawBackgroundColor(debugglobal[1], 0x00000000);
	TextDrawFont(debugglobal[1], 4);
	TextDrawSetProportional(debugglobal[1], 1);
	TextDrawSetSelectable(debugglobal[1], 0);

	debugglobal[0] = TextDrawCreate(204.699997, 349.527405, "LD_SPAC:white");
	TextDrawLetterSize(debugglobal[0], 0.000000, 0.000000);
	TextDrawTextSize(debugglobal[0], 211.866669, 83.792595);
	TextDrawAlignment(debugglobal[0], 1);
	TextDrawColor(debugglobal[0], 0x111111FF);
	TextDrawUseBox(debugglobal[0], 0);
	TextDrawBoxColor(debugglobal[0], 0x80808080);
	TextDrawSetShadow(debugglobal[0], 0);
	TextDrawSetOutline(debugglobal[0], 0);
	TextDrawBackgroundColor(debugglobal[0], 0x00000000);
	TextDrawFont(debugglobal[0], 4);
	TextDrawSetProportional(debugglobal[0], 1);
	TextDrawSetSelectable(debugglobal[0], 0);
	
	HungerFon[0] = TextDrawCreate(547.500000, 58.000000, "_");TextDrawBackgroundColor(HungerFon[0], 255);TextDrawFont(HungerFon[0], 1);TextDrawLetterSize(HungerFon[0], 0.500000, 0.399999);
	TextDrawColor(HungerFon[0], -1);TextDrawSetOutline(HungerFon[0], 0);TextDrawSetProportional(HungerFon[0], 1);TextDrawSetShadow(HungerFon[0], 1);
	TextDrawUseBox(HungerFon[0], 1);TextDrawBoxColor(HungerFon[0], 255);TextDrawTextSize(HungerFon[0], 606.000000, 40.000000);TextDrawSetSelectable(HungerFon[0], 0);

	HungerFon[1] = TextDrawCreate(549.500000, 60.000000, "_");TextDrawBackgroundColor(HungerFon[1], 255);TextDrawFont(HungerFon[1], 1);
	TextDrawLetterSize(HungerFon[1], 0.490000, -0.000000);TextDrawColor(HungerFon[1], -1);TextDrawSetOutline(HungerFon[1], 0);TextDrawSetProportional(HungerFon[1], 1);
	TextDrawSetShadow(HungerFon[1], 1);TextDrawUseBox(HungerFon[1], 1);TextDrawBoxColor(HungerFon[1], 1787344480);TextDrawTextSize(HungerFon[1], 604.000000, 40.000000);TextDrawSetSelectable(HungerFon[1], 0);
	
	Map[0] = TextDrawCreate(0.0, 0.0, "samaps:gtasamapbit1");
	TextDrawFont(Map[0], 4);
	TextDrawBoxColor(Map[0], 0xFFFFFFAA);
	TextDrawTextSize(Map[0], 320.0, 224.0);

	Map[1] = TextDrawCreate(320.0, 0.0, "samaps:gtasamapbit2");
	TextDrawFont(Map[1], 4);
	TextDrawBoxColor(Map[0], 0xFFFFFFAA);
	TextDrawTextSize(Map[1], 320.0, 224.0);

	Map[2] = TextDrawCreate(0.0, 224.0, "samaps:gtasamapbit3");
	TextDrawFont(Map[2], 4);
	TextDrawBoxColor(Map[0], 0xFFFFFFAA);
	TextDrawTextSize(Map[2], 320.0, 224.0);

	Map[3] = TextDrawCreate(320.0, 224.0, "samaps:gtasamapbit4");
	TextDrawFont(Map[3], 4);
	TextDrawBoxColor(Map[0], 0xFFFFFFAA);
	TextDrawTextSize(Map[3], 320.0, 224.0);

	others[6] = TextDrawCreate(336.269989, 123.099998, "usebox");
	TextDrawLetterSize(others[6], 0.000000, 8.752383);
	TextDrawTextSize(others[6], 283.079315, 0.000000);
	TextDrawAlignment(others[6], 1);
	TextDrawColor(others[6], 0xE1E1E1FF);
	TextDrawUseBox(others[6], 1);
	TextDrawBoxColor(others[6], 0x1A1A1AFF);
	TextDrawSetShadow(others[6], 2);
	TextDrawSetOutline(others[6], 0);
	TextDrawBackgroundColor(others[6], 0x000000FF);
	TextDrawFont(others[6], 0);
	TextDrawSetProportional(others[6], 1);
	TextDrawSetSelectable(others[6], 0);

	others[5] = TextDrawCreate(287.579315, 124.599998, "_");
	TextDrawLetterSize(others[5], 0.480000, 1.120000);
	TextDrawTextSize(others[5], 21.720343, 24.629631);
	TextDrawAlignment(others[5], 1);
	TextDrawColor(others[5], 0xFFFFFFFF);
	TextDrawUseBox(others[5], 0);
	TextDrawBoxColor(others[5], 0x80808080);
	TextDrawSetShadow(others[5], 2);
	TextDrawSetOutline(others[5], 0);
	TextDrawBackgroundColor(others[5], 0x333333FF);
	TextDrawFont(others[5], 5);
	TextDrawSetProportional(others[5], 1);
	TextDrawSetSelectable(others[5], 1);
	TextDrawSetPreviewModel(others[5], 1649);
	TextDrawSetPreviewRot(others[5], 0.000000, 0.000000, 90.000000, 2.000000);

	others[4] = TextDrawCreate(287.579315, 150.229630, "_");
	TextDrawLetterSize(others[4], 0.480000, 1.120000);
	TextDrawTextSize(others[4], 21.720343, 24.629631);
	TextDrawAlignment(others[4], 1);
	TextDrawColor(others[4], 0xFFFFFFFF);
	TextDrawUseBox(others[4], 0);
	TextDrawBoxColor(others[4], 0x80808080);
	TextDrawSetShadow(others[4], 2);
	TextDrawSetOutline(others[4], 0);
	TextDrawBackgroundColor(others[4], 0x333333FF);
	TextDrawFont(others[4], 5);
	TextDrawSetProportional(others[4], 1);
	TextDrawSetSelectable(others[4], 1);
	TextDrawSetPreviewModel(others[4], 1649);
	TextDrawSetPreviewRot(others[4], 0.000000, 0.000000, 90.000000, 2.000000);

	others[3] = TextDrawCreate(287.579315, 175.859253, "_");
	TextDrawLetterSize(others[3], 0.480000, 1.120000);
	TextDrawTextSize(others[3], 21.720343, 24.629631);
	TextDrawAlignment(others[3], 1);
	TextDrawColor(others[3], 0xFFFFFFFF);
	TextDrawUseBox(others[3], 0);
	TextDrawBoxColor(others[3], 0x80808080);
	TextDrawSetShadow(others[3], 2);
	TextDrawSetOutline(others[3], 0);
	TextDrawBackgroundColor(others[3], 0x333333FF);
	TextDrawFont(others[3], 5);
	TextDrawSetProportional(others[3], 1);
	TextDrawSetSelectable(others[3], 1);
	TextDrawSetPreviewModel(others[3], 1649);
	TextDrawSetPreviewRot(others[3], 0.000000, 0.000000, 90.000000, 2.000000);
	
	others[2] = TextDrawCreate(310.299652, 124.599998, "_");
	TextDrawLetterSize(others[2], 0.480000, 1.120000);
	TextDrawTextSize(others[2], 21.720343, 24.629631);
	TextDrawAlignment(others[2], 1);
	TextDrawColor(others[2], 0xFFFFFFFF);
	TextDrawUseBox(others[2], 0);
	TextDrawBoxColor(others[2], 0x80808080);
	TextDrawSetShadow(others[2], 2);
	TextDrawSetOutline(others[2], 0);
	TextDrawBackgroundColor(others[2], 0x333333FF);
	TextDrawFont(others[2], 5);
	TextDrawSetProportional(others[2], 1);
	TextDrawSetSelectable(others[2], 1);
	TextDrawSetPreviewModel(others[2], 1649);
	TextDrawSetPreviewRot(others[2], 0.000000, 0.000000, 90.000000, 2.000000);

	others[1] = TextDrawCreate(310.299652, 150.229630, "_");
	TextDrawLetterSize(others[1], 0.480000, 1.120000);
	TextDrawTextSize(others[1], 21.720343, 24.629631);
	TextDrawAlignment(others[1], 1);
	TextDrawColor(others[1], 0xFFFFFFFF);
	TextDrawUseBox(others[1], 0);
	TextDrawBoxColor(others[1], 0x80808080);
	TextDrawSetShadow(others[1], 2);
	TextDrawSetOutline(others[1], 0);
	TextDrawBackgroundColor(others[1], 0x333333FF);
	TextDrawFont(others[1], 5);
	TextDrawSetProportional(others[1], 1);
	TextDrawSetSelectable(others[1], 1);
	TextDrawSetPreviewModel(others[1], 1649);
	TextDrawSetPreviewRot(others[1], 0.000000, 0.000000, 90.000000, 2.000000);

	others[0] = TextDrawCreate(310.299652, 175.859253, "_");
	TextDrawLetterSize(others[0], 0.480000, 1.120000);
	TextDrawTextSize(others[0], 21.720343, 24.629631);
	TextDrawAlignment(others[0], 1);
	TextDrawColor(others[0], 0xFFFFFFFF);
	TextDrawUseBox(others[0], 0);
	TextDrawBoxColor(others[0], 0x80808080);
	TextDrawSetShadow(others[0], 2);
	TextDrawSetOutline(others[0], 0);
	TextDrawBackgroundColor(others[0], 0x333333FF);
	TextDrawFont(others[0], 5);
	TextDrawSetProportional(others[0], 1);
	TextDrawSetSelectable(others[0], 1);
	TextDrawSetPreviewModel(others[0], 1649);
	TextDrawSetPreviewRot(others[0], 0.000000, 0.000000, 90.000000, 2.000000);
	
	launch[8] = TextDrawCreate(260.100098, 438.877289, "particle:lamp_shad_64");
	TextDrawLetterSize(launch[8], 0.000000, 0.000000);
	TextDrawTextSize(launch[8], 127.000000, -2.000000);
	TextDrawAlignment(launch[8], 1);
	TextDrawColor(launch[8], 0x00000091);
	TextDrawUseBox(launch[8], 0);
	TextDrawBoxColor(launch[8], 0x80808080);
	TextDrawSetShadow(launch[8], 0);
	TextDrawSetOutline(launch[8], 0);
	TextDrawBackgroundColor(launch[8], 0x000000FF);
	TextDrawFont(launch[8], 4);
	TextDrawSetProportional(launch[8], 0);
	TextDrawSetSelectable(launch[8], 0);

	launch[7] = TextDrawCreate(262.600189, 417.162903, "LD_BEAT:chit");
	TextDrawLetterSize(launch[7], 0.000000, 0.000000);
	TextDrawTextSize(launch[7], 19.290001, 24.000000);
	TextDrawAlignment(launch[7], 1);
	TextDrawColor(launch[7], 0x191919FF);
	TextDrawUseBox(launch[7], 0);
	TextDrawBoxColor(launch[7], 0x80808080);
	TextDrawSetShadow(launch[7], 0);
	TextDrawSetOutline(launch[7], 0);
	TextDrawBackgroundColor(launch[7], 0x000000FF);
	TextDrawFont(launch[7], 4);
	TextDrawSetProportional(launch[7], 0);
	TextDrawSetSelectable(launch[7], 0);

	launch[6] = TextDrawCreate(272.166687, 420.940613, "LD_SPAC:white");
	TextDrawLetterSize(launch[6], 0.000000, 0.000000);
	TextDrawTextSize(launch[6], 102.000000, 16.250000);
	TextDrawAlignment(launch[6], 1);
	TextDrawColor(launch[6], 0x191919FF);
	TextDrawUseBox(launch[6], 0);
	TextDrawBoxColor(launch[6], 0x80808080);
	TextDrawSetShadow(launch[6], 0);
	TextDrawSetOutline(launch[6], 0);
	TextDrawBackgroundColor(launch[6], 0x000000FF);
	TextDrawFont(launch[6], 4);
	TextDrawSetProportional(launch[6], 0);
	TextDrawSetSelectable(launch[6], 0);

	launch[5] = TextDrawCreate(264.733490, 419.207611, "LD_BEAT:chit");
	TextDrawLetterSize(launch[5], 0.000000, 0.000000);
	TextDrawTextSize(launch[5], 17.000000, 20.000000);
	TextDrawAlignment(launch[5], 1);
	TextDrawColor(launch[5], 0xA52A2AFF);
	TextDrawUseBox(launch[5], 0);
	TextDrawBoxColor(launch[5], 0x80808080);
	TextDrawSetShadow(launch[5], 0);
	TextDrawSetOutline(launch[5], 0);
	TextDrawBackgroundColor(launch[5], 0x000000FF);
	TextDrawFont(launch[5], 4);
	TextDrawSetProportional(launch[5], 0);
	TextDrawSetSelectable(launch[5], 0);

	launch[4] = TextDrawCreate(273.266510, 422.670105, "LD_SPAC:white");
	TextDrawLetterSize(launch[4], 0.000000, 0.000000);
	TextDrawTextSize(launch[4], 99.530098, 13.039899);
	TextDrawAlignment(launch[4], 1);
	TextDrawColor(launch[4], 0xA52A2AFF);
	TextDrawUseBox(launch[4], 0);
	TextDrawBoxColor(launch[4], 0x80808080);
	TextDrawSetShadow(launch[4], 0);
	TextDrawSetOutline(launch[4], 0);
	TextDrawBackgroundColor(launch[4], 0x000000FF);
	TextDrawFont(launch[4], 4);
	TextDrawSetProportional(launch[4], 0);
	TextDrawSetSelectable(launch[4], 0);

	launch[3] = TextDrawCreate(272.133301, 424.558990, "LD_SPAC:white");
	TextDrawLetterSize(launch[3], 0.000000, 0.000000);
	TextDrawTextSize(launch[3], 101.000000, 9.010000);
	TextDrawAlignment(launch[3], 1);
	TextDrawColor(launch[3], 0x191919FF);
	TextDrawUseBox(launch[3], 0);
	TextDrawBoxColor(launch[3], 0x80808080);
	TextDrawSetShadow(launch[3], 0);
	TextDrawSetOutline(launch[3], 0);
	TextDrawBackgroundColor(launch[3], 0x000000FF);
	TextDrawFont(launch[3], 4);
	TextDrawSetProportional(launch[3], 0);
	TextDrawSetSelectable(launch[3], 0);

	launch[2] = TextDrawCreate(273.933289, 426.803497, "LD_SPAC:white");
	TextDrawLetterSize(launch[2], 0.000000, 0.000000);
	TextDrawTextSize(launch[2], 54.159901, 4.059999);
	TextDrawAlignment(launch[2], 1);
	TextDrawColor(launch[2], 0x0000006E);
	TextDrawUseBox(launch[2], 0);
	TextDrawBoxColor(launch[2], 0x80808080);
	TextDrawSetShadow(launch[2], 0);
	TextDrawSetOutline(launch[2], 0);
	TextDrawBackgroundColor(launch[2], 0x000000FF);
	TextDrawFont(launch[2], 4);
	TextDrawSetProportional(launch[2], 0);
	TextDrawSetSelectable(launch[2], 0);

	launch[1] = TextDrawCreate(262.833405, 432.481415, "particle:lamp_shad_64");
	TextDrawLetterSize(launch[1], 0.000000, 0.000000);
	TextDrawTextSize(launch[1],113.000000, -11.479999);
	TextDrawAlignment(launch[1], 1);
	TextDrawColor(launch[1], 0xC0C0C05D);
	TextDrawUseBox(launch[1], 0);
	TextDrawBoxColor(launch[1], 0x80808080);
	TextDrawSetShadow(launch[1], 0);
	TextDrawSetOutline(launch[1], 0);
	TextDrawBackgroundColor(launch[1], 0x000000FF);
	TextDrawFont(launch[1], 4);
	TextDrawSetProportional(launch[1], 0);
	TextDrawSetSelectable(launch[1], 0);

	launch[0] = TextDrawCreate(370.533386, 424.696411, "LAUNCH_-_CONTROL");
	TextDrawLetterSize(launch[0], 0.143600, 0.898899);
	TextDrawTextSize(launch[0], 1280.000000, 1280.000000);
	TextDrawAlignment(launch[0], 3);
	TextDrawColor(launch[0], 0xC0C0C0FF);
	TextDrawUseBox(launch[0], 0);
	TextDrawBoxColor(launch[0], 0x80808080);
	TextDrawSetShadow(launch[0], 0);
	TextDrawSetOutline(launch[0], 0);
	TextDrawBackgroundColor(launch[0], 0x191919FF);
	TextDrawFont(launch[0], 1);
	TextDrawSetProportional(launch[0], 1);
	TextDrawSetSelectable(launch[0], 0);

	selectmenu[27] = TextDrawCreate(272.333191, 269.073914, "particle:lamp_shad_64");
	TextDrawLetterSize(selectmenu[27], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[27], 97.000000, -47.000000);
	TextDrawAlignment(selectmenu[27], 1);
	TextDrawColor(selectmenu[27], 0x00000060);
	TextDrawUseBox(selectmenu[27], 0);
	TextDrawBoxColor(selectmenu[27], 0x80808080);
	TextDrawSetShadow(selectmenu[27], 0);
	TextDrawSetOutline(selectmenu[27], 0);
	TextDrawBackgroundColor(selectmenu[27], 0x000000FF);
	TextDrawFont(selectmenu[27], 4);
	TextDrawSetProportional(selectmenu[27], 0);
	TextDrawSetSelectable(selectmenu[27], 0);

	selectmenu[26] = TextDrawCreate(273.666595, 164.125702, "particle:lamp_shad_64");
	TextDrawLetterSize(selectmenu[26], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[26], 91.000000, 57.979900);
	TextDrawAlignment(selectmenu[26], 1);
	TextDrawColor(selectmenu[26], 0x00000060);
	TextDrawUseBox(selectmenu[26], 0);
	TextDrawBoxColor(selectmenu[26], 0x80808080);
	TextDrawSetShadow(selectmenu[26], 0);
	TextDrawSetOutline(selectmenu[26], 0);
	TextDrawBackgroundColor(selectmenu[26], 0x000000FF);
	TextDrawFont(selectmenu[26], 4);
	TextDrawSetProportional(selectmenu[26], 0);
	TextDrawSetSelectable(selectmenu[26], 0);

	selectmenu[25] = TextDrawCreate(292.200012, 143.125793, "");
	TextDrawLetterSize(selectmenu[25], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[25], 57.000000, 63.000000);
	TextDrawAlignment(selectmenu[25], 1);
	TextDrawColor(selectmenu[25], 0x00000078);
	TextDrawUseBox(selectmenu[25], 0);
	TextDrawBoxColor(selectmenu[25], 0x80808080);
	TextDrawSetShadow(selectmenu[25], 0);
	TextDrawSetOutline(selectmenu[25], 0);
	TextDrawBackgroundColor(selectmenu[25], 0x00000000);
	TextDrawFont(selectmenu[25], 5);
	TextDrawSetProportional(selectmenu[25], 0);
	TextDrawSetSelectable(selectmenu[25], 0);
	TextDrawSetPreviewModel(selectmenu[25], 19738);
	TextDrawSetPreviewRot(selectmenu[25], 119.000000, 0.000000, 90.000000, 1.000000);

	selectmenu[24] = TextDrawCreate(318.366486, 153.110992, "");
	TextDrawLetterSize(selectmenu[24], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[24], 56.000000, 70.000000);
	TextDrawAlignment(selectmenu[24], 1);
	TextDrawColor(selectmenu[24], 0x00000078);
	TextDrawUseBox(selectmenu[24], 0);
	TextDrawBoxColor(selectmenu[24], 0x80808080);
	TextDrawSetShadow(selectmenu[24], 0);
	TextDrawSetOutline(selectmenu[24], 0);
	TextDrawBackgroundColor(selectmenu[24], 0x00000000);
	TextDrawFont(selectmenu[24], 5);
	TextDrawSetProportional(selectmenu[24], 0);
	TextDrawSetSelectable(selectmenu[24], 0);
	TextDrawSetPreviewModel(selectmenu[24], 19738);
	TextDrawSetPreviewRot(selectmenu[24], 116.000000, 20.000000, 132.000000, 1.000000);

	selectmenu[23] = TextDrawCreate(321.966705, 153.710999, "");
	TextDrawLetterSize(selectmenu[23], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[23], -52.000000, 68.000000);
	TextDrawAlignment(selectmenu[23], 1);
	TextDrawColor(selectmenu[23], 0x00000078);
	TextDrawUseBox(selectmenu[23], 0);
	TextDrawBoxColor(selectmenu[23], 0x80808080);
	TextDrawSetShadow(selectmenu[23], 0);
	TextDrawSetOutline(selectmenu[23], 0);
	TextDrawBackgroundColor(selectmenu[23], 0x00000000);
	TextDrawFont(selectmenu[23], 5);
	TextDrawSetProportional(selectmenu[23], 0);
	TextDrawSetSelectable(selectmenu[23], 0);
	TextDrawSetPreviewModel(selectmenu[23], 19738);
	TextDrawSetPreviewRot(selectmenu[23], 116.000000, 20.000000, 132.000000, 1.000000);

	selectmenu[22] = TextDrawCreate(328.333313, 187.670395, "");
	TextDrawLetterSize(selectmenu[22], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[22], 55.000000, 63.000000);
	TextDrawAlignment(selectmenu[22], 1);
	TextDrawColor(selectmenu[22], 0x80000078);
	TextDrawUseBox(selectmenu[22], 0);
	TextDrawBoxColor(selectmenu[22], 0x80808080);
	TextDrawSetShadow(selectmenu[22], 0);
	TextDrawSetOutline(selectmenu[22], 0);
	TextDrawBackgroundColor(selectmenu[22], 0x00000000);
	TextDrawFont(selectmenu[22], 5);
	TextDrawSetProportional(selectmenu[22], 0);
	TextDrawSetSelectable(selectmenu[22], 0);
	TextDrawSetPreviewModel(selectmenu[22], 19738);
	TextDrawSetPreviewRot(selectmenu[22], 90.000000, 24.000000, 181.000000, 1.000000);

	selectmenu[21] = TextDrawCreate(314.966797, 187.040802, "");
	TextDrawLetterSize(selectmenu[21], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[21], -55.000000, 64.000000);
	TextDrawAlignment(selectmenu[21], 1);
	TextDrawColor(selectmenu[21], 0x80000078);
	TextDrawUseBox(selectmenu[21], 0);
	TextDrawBoxColor(selectmenu[21], 0x80808080);
	TextDrawSetShadow(selectmenu[21], 0);
	TextDrawSetOutline(selectmenu[21], 0);
	TextDrawBackgroundColor(selectmenu[21], 0x00000000);
	TextDrawFont(selectmenu[21], 5);
	TextDrawSetProportional(selectmenu[21], 0);
	TextDrawSetSelectable(selectmenu[21], 0);
	TextDrawSetPreviewModel(selectmenu[21], 19738);
	TextDrawSetPreviewRot(selectmenu[21], 90.000000, 24.000000, 181.000000, 1.000000);

	selectmenu[20] = TextDrawCreate(319.599915, 281.207306, "");
	TextDrawLetterSize(selectmenu[20], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[20], 53.000000, -65.000000);
	TextDrawAlignment(selectmenu[20], 1);
	TextDrawColor(selectmenu[20], 0x80000078);
	TextDrawUseBox(selectmenu[20], 0);
	TextDrawBoxColor(selectmenu[20], 0x80808080);
	TextDrawSetShadow(selectmenu[20], 0);
	TextDrawSetOutline(selectmenu[20], 0);
	TextDrawBackgroundColor(selectmenu[20], 0x00000000);
	TextDrawFont(selectmenu[20], 5);
	TextDrawSetProportional(selectmenu[20], 0);
	TextDrawSetSelectable(selectmenu[20], 0);
	TextDrawSetPreviewModel(selectmenu[20], 19738);
	TextDrawSetPreviewRot(selectmenu[20], 116.000000, 20.000000, 132.000000, 1.000000);

	selectmenu[19] = TextDrawCreate(291.933411, 291.536591, "");
	TextDrawLetterSize(selectmenu[19], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[19], 58.000000, -63.000000);
	TextDrawAlignment(selectmenu[19], 1);
	TextDrawColor(selectmenu[19], 0x00000078);
	TextDrawUseBox(selectmenu[19], 0);
	TextDrawBoxColor(selectmenu[19], 0x80808080);
	TextDrawSetShadow(selectmenu[19], 0);
	TextDrawSetOutline(selectmenu[19], 0);
	TextDrawBackgroundColor(selectmenu[19], 0x00000000);
	TextDrawFont(selectmenu[19], 5);
	TextDrawSetProportional(selectmenu[19], 0);
	TextDrawSetSelectable(selectmenu[19], 0);
	TextDrawSetPreviewModel(selectmenu[19], 19738);
	TextDrawSetPreviewRot(selectmenu[19], 119.000000, 0.000000, 90.000000, 1.000000);

	selectmenu[18] = TextDrawCreate(321.899994, 281.707306, "");
	TextDrawLetterSize(selectmenu[18], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[18], -52.000000, -65.000000);
	TextDrawAlignment(selectmenu[18], 1);
	TextDrawColor(selectmenu[18], 0x80000078);
	TextDrawUseBox(selectmenu[18], 0);
	TextDrawBoxColor(selectmenu[18], 0x80808080);
	TextDrawSetShadow(selectmenu[18], 0);
	TextDrawSetOutline(selectmenu[18], 0);
	TextDrawBackgroundColor(selectmenu[18], 0x00000000);
	TextDrawFont(selectmenu[18], 5);
	TextDrawSetProportional(selectmenu[18], 0);
	TextDrawSetSelectable(selectmenu[18], 0);
	TextDrawSetPreviewModel(selectmenu[18], 19738);
	TextDrawSetPreviewRot(selectmenu[18], 116.000000, 20.000000, 132.000000, 1.000000);

	selectmenu[17] = TextDrawCreate(296.133118, 189.414764, "LD_POOL:ball");
	TextDrawLetterSize(selectmenu[17], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[17], 50.000000, 59.000000);
	TextDrawAlignment(selectmenu[17], 1);
	TextDrawColor(selectmenu[17], 0xC8C8C8FF);
	TextDrawUseBox(selectmenu[17], 0);
	TextDrawBoxColor(selectmenu[17], 0x80808080);
	TextDrawSetShadow(selectmenu[17], 0);
	TextDrawSetOutline(selectmenu[17], 0);
	TextDrawBackgroundColor(selectmenu[17], 0x000000FF);
	TextDrawFont(selectmenu[17], 4);
	TextDrawSetProportional(selectmenu[17], 0);
	TextDrawSetSelectable(selectmenu[17], 0);

	selectmenu[16] = TextDrawCreate(310.000092, 165.140686, "");
	TextDrawLetterSize(selectmenu[16], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[16], 19.000000, 20.000000);
	TextDrawAlignment(selectmenu[16], 1);
	TextDrawColor(selectmenu[16], 0xFFFFFF78);
	TextDrawUseBox(selectmenu[16], 0);
	TextDrawBoxColor(selectmenu[16], 0x80808080);
	TextDrawSetShadow(selectmenu[16], 0);
	TextDrawSetOutline(selectmenu[16], 0);
	TextDrawBackgroundColor(selectmenu[16], 0x00000000);
	TextDrawFont(selectmenu[16], 5);
	TextDrawSetProportional(selectmenu[16], 0);
	TextDrawSetSelectable(selectmenu[16], 1);
	TextDrawSetPreviewModel(selectmenu[16], 1314);
	TextDrawSetPreviewRot(selectmenu[16], 0.000000, 0.000000, 0.000000, 0.860271);

	selectmenu[15] = TextDrawCreate(337.333405, 177.585129, "");
	TextDrawLetterSize(selectmenu[15], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[15], 19.000000, 20.000000);
	TextDrawAlignment(selectmenu[15], 1);
	TextDrawColor(selectmenu[15], 0xFFFFFF78);
	TextDrawUseBox(selectmenu[15], 0);
	TextDrawBoxColor(selectmenu[15], 0x80808080);
	TextDrawSetShadow(selectmenu[15], 0);
	TextDrawSetOutline(selectmenu[15], 0);
	TextDrawBackgroundColor(selectmenu[15], 0x00000000);
	TextDrawFont(selectmenu[15], 5);
	TextDrawSetProportional(selectmenu[15], 0);
	TextDrawSetSelectable(selectmenu[15], 1);
	TextDrawSetPreviewModel(selectmenu[15], 19610);
	TextDrawSetPreviewRot(selectmenu[15], 250.000000, 0.000000, 133.000000, 0.797705);

	selectmenu[14] = TextDrawCreate(347.533508, 210.770340, "");
	TextDrawLetterSize(selectmenu[14], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[14], 19.000000, 20.000000);
	TextDrawAlignment(selectmenu[14], 1);
	TextDrawColor(selectmenu[14], 0xFFFFFF78);
	TextDrawUseBox(selectmenu[14], 0);
	TextDrawBoxColor(selectmenu[14], 0x80808080);
	TextDrawSetShadow(selectmenu[14], 0);
	TextDrawSetOutline(selectmenu[14], 0);
	TextDrawBackgroundColor(selectmenu[14], 0x00000000);
	TextDrawFont(selectmenu[14], 5);
	TextDrawSetProportional(selectmenu[14], 0);
	TextDrawSetSelectable(selectmenu[14], 1);
	TextDrawSetPreviewModel(selectmenu[14], 1274);
	TextDrawSetPreviewRot(selectmenu[14], 0.000000, 0.000000, 180.000000, 0.860271);

	selectmenu[13] = TextDrawCreate(337.200104, 238.018539, "");
	TextDrawLetterSize(selectmenu[13], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[13], 19.000000, 20.000000);
	TextDrawAlignment(selectmenu[13], 1);
	TextDrawColor(selectmenu[13], 0xFFFFFF78);
	TextDrawUseBox(selectmenu[13], 0);
	TextDrawBoxColor(selectmenu[13], 0x80808080);
	TextDrawSetShadow(selectmenu[13], 0);
	TextDrawSetOutline(selectmenu[13], 0);
	TextDrawBackgroundColor(selectmenu[13], 0x00000000);
	TextDrawFont(selectmenu[13], 5);
	TextDrawSetProportional(selectmenu[13], 0);
	TextDrawSetSelectable(selectmenu[13], 1);
	TextDrawSetPreviewModel(selectmenu[13], 500);
	TextDrawSetPreviewRot(selectmenu[13], 0.000000, 0.000000, 90.000000, 0.792492);
	TextDrawSetPreviewVehCol(selectmenu[13], 65535, 65535);

	selectmenu[12] = TextDrawCreate(286.600098, 237.433289, "");
	TextDrawLetterSize(selectmenu[12], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[12], 19.000000, 20.000000);
	TextDrawAlignment(selectmenu[12], 1);
	TextDrawColor(selectmenu[12], 0xFFFFFF78);
	TextDrawUseBox(selectmenu[12], 0);
	TextDrawBoxColor(selectmenu[12], 0x80808080);
	TextDrawSetShadow(selectmenu[12], 0);
	TextDrawSetOutline(selectmenu[12], 0);
	TextDrawBackgroundColor(selectmenu[12], 0x00000000);
	TextDrawFont(selectmenu[12], 5);
	TextDrawSetProportional(selectmenu[12], 0);
	TextDrawSetSelectable(selectmenu[12], 1);
	TextDrawSetPreviewModel(selectmenu[12], 1581);
	TextDrawSetPreviewRot(selectmenu[12], 0.000000, 0.000000, 180.000000, 0.667361);

	selectmenu[11] = TextDrawCreate(276.700073, 207.766586, "");
	TextDrawLetterSize(selectmenu[11], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[11], 19.000000, 20.000000);
	TextDrawAlignment(selectmenu[11], 1);
	TextDrawColor(selectmenu[11], 0xFFFFFF78);
	TextDrawUseBox(selectmenu[11], 0);
	TextDrawBoxColor(selectmenu[11], 0x80808080);
	TextDrawSetShadow(selectmenu[11], 0);
	TextDrawSetOutline(selectmenu[11], 0);
	TextDrawBackgroundColor(selectmenu[11], 0x00000000);
	TextDrawFont(selectmenu[11], 5);
	TextDrawSetProportional(selectmenu[11], 0);
	TextDrawSetSelectable(selectmenu[11], 1);
	TextDrawSetPreviewModel(selectmenu[11], 19134);
	TextDrawSetPreviewRot(selectmenu[11], 0.000000, 0.000000, 90.000000, 0.844629);

	selectmenu[10] = TextDrawCreate(286.166779, 177.370316, "");
	TextDrawLetterSize(selectmenu[10], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[10], 19.000000, 20.000000);
	TextDrawAlignment(selectmenu[10], 1);
	TextDrawColor(selectmenu[10], 0xFFFFFF78);
	TextDrawUseBox(selectmenu[10], 0);
	TextDrawBoxColor(selectmenu[10], 0x80808080);
	TextDrawSetShadow(selectmenu[10], 0);
	TextDrawSetOutline(selectmenu[10], 0);
	TextDrawBackgroundColor(selectmenu[10], 0x00000000);
	TextDrawFont(selectmenu[10], 5);
	TextDrawSetProportional(selectmenu[10], 0);
	TextDrawSetSelectable(selectmenu[10], 1);
	TextDrawSetPreviewModel(selectmenu[10], 1240);
	TextDrawSetPreviewRot(selectmenu[10], 0.000000, 0.000000, 0.000000, 0.844629);

	selectmenu[9] = TextDrawCreate(312.266754, 251.122177, "");
	TextDrawLetterSize(selectmenu[9], 0.000000, 0.000000);
	TextDrawTextSize(selectmenu[9], 19.000000, 20.000000);
	TextDrawAlignment(selectmenu[9], 1);
	TextDrawColor(selectmenu[9], 0xFFFFFF78);
	TextDrawUseBox(selectmenu[9], 0);
	TextDrawBoxColor(selectmenu[9], 0x80808080);
	TextDrawSetShadow(selectmenu[9], 0);
	TextDrawSetOutline(selectmenu[9], 0);
	TextDrawBackgroundColor(selectmenu[9], 0x00000000);
	TextDrawFont(selectmenu[9], 5);
	TextDrawSetProportional(selectmenu[9], 0);
	TextDrawSetSelectable(selectmenu[9], 1);
	TextDrawSetPreviewModel(selectmenu[9], 9525);
	TextDrawSetPreviewRot(selectmenu[9], 0.000000, 0.000000, 0.000000, 0.797705);
	//
	
	//
    klickd[0] = TextDrawCreate(228.000000, 137.000000, "_");
	TextDrawBackgroundColor(klickd[0], 255);
	TextDrawFont(klickd[0], 1);
	TextDrawLetterSize(klickd[0], 0.500000, 19.799999);
	TextDrawColor(klickd[0], 1969887264);
	TextDrawSetOutline(klickd[0], 0);
	TextDrawSetProportional(klickd[0], 1);
	TextDrawSetShadow(klickd[0], 1);
	TextDrawUseBox(klickd[0], 1);
	TextDrawBoxColor(klickd[0], -240);
	TextDrawTextSize(klickd[0], 473.000000, 2.000000);
	TextDrawSetSelectable(klickd[0], 0);

    klickd[1] = TextDrawCreate(436.000000, 166.000000, "Done");
	TextDrawAlignment(klickd[1], 2);
	TextDrawBackgroundColor(klickd[1], 255);
	TextDrawFont(klickd[1], 2);
	TextDrawLetterSize(klickd[1], 0.300000, 1.100000);
	TextDrawColor(klickd[1], -1);
	TextDrawSetOutline(klickd[1], 1);
	TextDrawSetProportional(klickd[1], 1);
	TextDrawUseBox(klickd[1], 1);
	TextDrawBoxColor(klickd[1], -1294582896);
	TextDrawTextSize(klickd[1], 20.000000, 63.000000);
	TextDrawSetSelectable(klickd[1], 1);

	klickd[2] = TextDrawCreate(436.000000, 190.000000, "Clear");
	TextDrawAlignment(klickd[2], 2);
	TextDrawBackgroundColor(klickd[2], 255);
	TextDrawFont(klickd[2], 2);
	TextDrawLetterSize(klickd[2], 0.300000, 1.100000);
	TextDrawColor(klickd[2], -1);
	TextDrawSetOutline(klickd[2], 1);
	TextDrawSetProportional(klickd[2], 1);
	TextDrawUseBox(klickd[2], 1);
	TextDrawBoxColor(klickd[2], -1294582896);
	TextDrawTextSize(klickd[2], 20.000000, 63.000000);
	TextDrawSetSelectable(klickd[2], 1);

	klick[0] = TextDrawCreate(266.000000, 145.000000, "1");
	TextDrawAlignment(klick[0], 2);
	TextDrawBackgroundColor(klick[0], 255);
	TextDrawFont(klick[0], 3);
	TextDrawLetterSize(klick[0], 1.560000, 4.999999);
	TextDrawColor(klick[0], -1);
	TextDrawSetOutline(klick[0], 0);
	TextDrawSetProportional(klick[0], 1);
	TextDrawSetShadow(klick[0], 1);
	TextDrawUseBox(klick[0], 1);
	TextDrawBoxColor(klick[0], -1012451329);
	TextDrawTextSize(klick[0], 40.000000, 40.000000);
	TextDrawSetSelectable(klick[0], 1);

	klick[1] = TextDrawCreate(320.000000, 145.000000, "2");
	TextDrawAlignment(klick[1], 2);
	TextDrawBackgroundColor(klick[1], 255);
	TextDrawFont(klick[1], 3);
	TextDrawLetterSize(klick[1], 1.560000, 4.999999);
	TextDrawColor(klick[1], -1);
	TextDrawSetOutline(klick[1], 0);
	TextDrawSetProportional(klick[1], 1);
	TextDrawSetShadow(klick[1], 1);
	TextDrawUseBox(klick[1], 1);
	TextDrawBoxColor(klick[1], -1012451329);
	TextDrawTextSize(klick[1], 40.000000, 40.000000);
	TextDrawSetSelectable(klick[1], 1);

	klick[2] = TextDrawCreate(374.000000, 145.000000, "3");
	TextDrawAlignment(klick[2], 2);
	TextDrawBackgroundColor(klick[2], 255);
	TextDrawFont(klick[2], 3);
	TextDrawLetterSize(klick[2], 1.560000, 4.999999);
	TextDrawColor(klick[2], -1);
	TextDrawSetOutline(klick[2], 0);
	TextDrawSetProportional(klick[2], 1);
	TextDrawSetShadow(klick[2], 1);
	TextDrawUseBox(klick[2], 1);
	TextDrawBoxColor(klick[2], -1012451329);
	TextDrawTextSize(klick[2], 40.000000, 40.000000);
	TextDrawSetSelectable(klick[2], 1);

	klick[3] = TextDrawCreate(266.000000, 203.000000, "4");
	TextDrawAlignment(klick[3], 2);
	TextDrawBackgroundColor(klick[3], 255);
	TextDrawFont(klick[3], 3);
	TextDrawLetterSize(klick[3], 1.560000, 4.999999);
	TextDrawColor(klick[3], -1);
	TextDrawSetOutline(klick[3], 0);
	TextDrawSetProportional(klick[3], 1);
	TextDrawSetShadow(klick[3], 1);
	TextDrawUseBox(klick[3], 1);
	TextDrawBoxColor(klick[3], -1012451329);
	TextDrawTextSize(klick[3], 40.000000, 40.000000);
	TextDrawSetSelectable(klick[3], 1);

	klick[4] = TextDrawCreate(320.000000, 204.000000, "5");
	TextDrawAlignment(klick[4], 2);
	TextDrawBackgroundColor(klick[4], 255);
	TextDrawFont(klick[4], 3);
	TextDrawLetterSize(klick[4], 1.560000, 4.999999);
	TextDrawColor(klick[4], -1);
	TextDrawSetOutline(klick[4], 0);
	TextDrawSetProportional(klick[4], 1);
	TextDrawSetShadow(klick[4], 1);
	TextDrawUseBox(klick[4], 1);
	TextDrawBoxColor(klick[4], -1012451329);
	TextDrawTextSize(klick[4], 40.000000, 40.000000);
	TextDrawSetSelectable(klick[4], 1);

	klick[5] = TextDrawCreate(374.000000, 203.000000, "6");
	TextDrawAlignment(klick[5], 2);
	TextDrawBackgroundColor(klick[5], 255);
	TextDrawFont(klick[5], 3);
	TextDrawLetterSize(klick[5], 1.560000, 4.999999);
	TextDrawColor(klick[5], -1);
	TextDrawSetOutline(klick[5], 0);
	TextDrawSetProportional(klick[5], 1);
	TextDrawSetShadow(klick[5], 1);
	TextDrawUseBox(klick[5], 1);
	TextDrawBoxColor(klick[5], -1012451329);
	TextDrawTextSize(klick[5],40.000000, 40.000000);
	TextDrawSetSelectable(klick[5], 1);


	klick[6] = TextDrawCreate(266.000000, 262.000000, "7");
	TextDrawAlignment(klick[6], 2);
	TextDrawBackgroundColor(klick[6], 255);
	TextDrawFont(klick[6], 3);
	TextDrawLetterSize(klick[6], 1.560000, 4.999999);
	TextDrawColor(klick[6], -1);
	TextDrawSetOutline(klick[6], 0);
	TextDrawSetProportional(klick[6], 1);
	TextDrawSetShadow(klick[6], 1);
	TextDrawUseBox(klick[6], 1);
	TextDrawBoxColor(klick[6], -1012451329);
	TextDrawTextSize(klick[6],40.000000, 40.000000);
	TextDrawSetSelectable(klick[6], 1);

	klick[7] = TextDrawCreate(320.000000, 262.000000, "8");
	TextDrawAlignment(klick[7], 2);
	TextDrawBackgroundColor(klick[7], 255);
	TextDrawFont(klick[7], 3);
	TextDrawLetterSize(klick[7], 1.560000, 4.999999);
	TextDrawColor(klick[7], -1);
	TextDrawSetOutline(klick[7], 0);
	TextDrawSetProportional(klick[7], 1);
	TextDrawSetShadow(klick[7], 1);
	TextDrawUseBox(klick[7], 1);
	TextDrawBoxColor(klick[7], -1012451329);
	TextDrawTextSize(klick[7], 40.000000, 40.000000);
	TextDrawSetSelectable(klick[7], 1);


	klick[8] = TextDrawCreate(374.000000, 262.000000, "9");
	TextDrawAlignment(klick[8], 2);
	TextDrawBackgroundColor(klick[8], 255);
	TextDrawFont(klick[8], 3);
	TextDrawLetterSize(klick[8], 1.560000, 4.999999);
	TextDrawColor(klick[8], -1);
	TextDrawSetOutline(klick[8], 0);
	TextDrawSetProportional(klick[8], 1);
	TextDrawSetShadow(klick[8], 1);
	TextDrawUseBox(klick[8], 1);
	TextDrawBoxColor(klick[8], -1012451329);
	TextDrawTextSize(klick[8],40.000000, 40.000000);
	TextDrawSetSelectable(klick[8], 1);


	//
	StopAnimation = TextDrawCreate(401.00, 419.00, "~w~Press ~y~ENTER~w~ to stop animation");
	TextDrawBackgroundColor(StopAnimation, 0x000000FF);
	TextDrawFont(StopAnimation, 2);
	TextDrawSetOutline(StopAnimation, 1);
	TextDrawLetterSize(StopAnimation, 0.300000, 1.250000);
	TextDrawColor(StopAnimation, 0x0095B6FF);
	TextDrawSetProportional(StopAnimation, 1);

	TextDrawCreate(-100,-100,".");//?aaiaue oaenoa?aa
	TirBGDraw = TextDrawCreate(518,341,"-");
	TextDrawUseBox(TirBGDraw,1);
	TextDrawColor(TirBGDraw,0xFFFFFFFF);//
	TextDrawBackgroundColor(TirBGDraw,0x00000000);
	TextDrawBoxColor(TirBGDraw,0x00000055);
	TextDrawTextSize(TirBGDraw,105.0,40.0);
	TextDrawAlignment(TirBGDraw,2);
	TextDrawLetterSize(TirBGDraw,0.00,5.09);
	TextDrawSetOutline(TirBGDraw,1);
	TextDrawFont(TirBGDraw,0);
	//iai? ea?iea
	IconsMenu[0] = TextDrawCreate(213.000000, 91.000000, "Icons1");
	TextDrawBackgroundColor(IconsMenu[0], 0xFFFFFF00);
	TextDrawFont(IconsMenu[0], 5);
	TextDrawLetterSize(IconsMenu[0], 0.500000, 1.000000);
	TextDrawColor(IconsMenu[0], -157666329750);
	TextDrawTextSize(IconsMenu[0], 228.000000, 229.000000);
	TextDrawSetPreviewModel(IconsMenu[0], 1953);
	TextDrawSetPreviewRot(IconsMenu[0], 90.000000, 0.000000, 0.000000, 1.000000);
	TextDrawSetSelectable(IconsMenu[0], 0);

	IconsMenu[1] = TextDrawCreate(302.000000, 176.000000, "Icons2");
	TextDrawBackgroundColor(IconsMenu[1], 0xFFFFFF00);
	TextDrawFont(IconsMenu[1], 5);
	TextDrawLetterSize(IconsMenu[1], 0.500000, 1.000000);
	TextDrawColor(IconsMenu[1], -157666329750);
	TextDrawTextSize(IconsMenu[1], 56.000000, 54.000000);
	TextDrawSetPreviewModel(IconsMenu[1], 1953);
	TextDrawSetPreviewRot(IconsMenu[1], 90.000000, 0.000000, 0.000000, 1.000000);
	TextDrawSetSelectable(IconsMenu[1], 0);

	IconsMenu[2] = TextDrawCreate(306.000000, 129.000000, "Q");
	TextDrawBackgroundColor(IconsMenu[2], 0);
	TextDrawFont(IconsMenu[2], 5);
	TextDrawLetterSize(IconsMenu[2], 0.500000, 1.000000);
	TextDrawTextSize(IconsMenu[2], 46.000000, 42.000000);
	TextDrawSetPreviewModel(IconsMenu[2], 1314);
	TextDrawSetPreviewRot(IconsMenu[2], -10.000000, 0.000000, 0.000000, 1.000000);
	TextDrawSetSelectable(IconsMenu[2], 1);

	IconsMenu[3] = TextDrawCreate(344.000000, 162.000000, "Q");
	TextDrawBackgroundColor(IconsMenu[3], 0);
	TextDrawFont(IconsMenu[3], 5);
	TextDrawLetterSize(IconsMenu[3], 0.500000, 1.000000);
	TextDrawTextSize(IconsMenu[3], 62.000000, 69.000000);
	TextDrawSetPreviewModel(IconsMenu[3], 1212);
	TextDrawSetPreviewRot(IconsMenu[3], 90.000000, -20.000000, 0.000000, 1.000000);
	TextDrawSetSelectable(IconsMenu[3], 1);

	IconsMenu[4] = TextDrawCreate(255.000000, 175.000000, "Q");
	TextDrawBackgroundColor(IconsMenu[4], 0);
	TextDrawFont(IconsMenu[4], 5);
	TextDrawLetterSize(IconsMenu[4], 0.500000, 1.000000);
	TextDrawTextSize(IconsMenu[4], 52.000000, 49.000000);
	TextDrawSetPreviewModel(IconsMenu[4], 1581);
	TextDrawSetPreviewRot(IconsMenu[4], 0.000000, 0.000000, 195.000000, 1.000000);
	TextDrawSetSelectable(IconsMenu[4], 1);

	IconsMenu[5] = TextDrawCreate(310.000000, 235.000000, "Q");
	TextDrawBackgroundColor(IconsMenu[5], 0);
	TextDrawFont(IconsMenu[5], 5);
	TextDrawLetterSize(IconsMenu[5], 0.500000, 1.000000);
	TextDrawTextSize(IconsMenu[5], 38.000000, 40.000000);
	TextDrawSetPreviewModel(IconsMenu[5], 1253);
	TextDrawSetPreviewRot(IconsMenu[5], 10.000000, 0.000000, 0.000000, 1.000000);
	TextDrawSetSelectable(IconsMenu[5], 1);

	IconsMenu[6] = TextDrawCreate(331.000000, 164.000000, "Hi");
	TextDrawAlignment(IconsMenu[6], 2);
	TextDrawBackgroundColor(IconsMenu[6], 255);
	TextDrawFont(IconsMenu[6], 1);
	TextDrawLetterSize(IconsMenu[6], 0.280000, 1.000000);
	TextDrawColor(IconsMenu[6], -1);
	TextDrawSetOutline(IconsMenu[6], 1);
	TextDrawSetProportional(IconsMenu[6], 0);
	TextDrawSetSelectable(IconsMenu[6], 0);

	IconsMenu[7] = TextDrawCreate(376.000000, 211.000000, "Trade");
	TextDrawAlignment(IconsMenu[7], 2);
	TextDrawBackgroundColor(IconsMenu[7], 255);
	TextDrawFont(IconsMenu[7], 1);
	TextDrawLetterSize(IconsMenu[7], 0.280000, 1.000000);
	TextDrawColor(IconsMenu[7], -1);
	TextDrawSetOutline(IconsMenu[7], 1);
	TextDrawSetProportional(IconsMenu[7], 0);
	TextDrawSetSelectable(IconsMenu[7], 0);

	IconsMenu[8] = TextDrawCreate(282.000000, 211.000000, "Dock");
	TextDrawAlignment(IconsMenu[8], 2);
	TextDrawBackgroundColor(IconsMenu[8], 255);
	TextDrawFont(IconsMenu[8], 1);
	TextDrawLetterSize(IconsMenu[8], 0.260000, 1.000000);
	TextDrawColor(IconsMenu[8], -1);
	TextDrawSetOutline(IconsMenu[8], 1);
	TextDrawSetProportional(IconsMenu[8], 1);
	TextDrawSetSelectable(IconsMenu[8], 0);

	IconsMenu[9] = TextDrawCreate(328.000000, 228.000000, "Say");
	TextDrawAlignment(IconsMenu[9], 2);
	TextDrawBackgroundColor(IconsMenu[9], 255);
	TextDrawFont(IconsMenu[9], 1);
	TextDrawLetterSize(IconsMenu[9], 0.260000, 1.000000);
	TextDrawColor(IconsMenu[9], -1);
	TextDrawSetOutline(IconsMenu[9], 1);
	TextDrawSetProportional(IconsMenu[9], 0);
	TextDrawSetSelectable(IconsMenu[9], 0);

	IconsMenu[10] = TextDrawCreate(330.000000, 195.000000, ""NAMEICRP"");
	TextDrawAlignment(IconsMenu[10], 2);
	TextDrawBackgroundColor(IconsMenu[10], 255);
	TextDrawFont(IconsMenu[10], 1);
	TextDrawLetterSize(IconsMenu[10], 0.200000, 0.800000);
	TextDrawColor(IconsMenu[10], -1);
	TextDrawSetOutline(IconsMenu[10], 1);
	TextDrawSetProportional(IconsMenu[10], 1);
	TextDrawSetSelectable(IconsMenu[10], 0);

	IconsMenu[11] = TextDrawCreate(330.000000, 201.000000, "Role Play");
	TextDrawAlignment(IconsMenu[11], 2);
	TextDrawBackgroundColor(IconsMenu[11], 255);
	TextDrawFont(IconsMenu[11], 1);
	TextDrawLetterSize(IconsMenu[11], 0.160000, 0.800000);
	TextDrawColor(IconsMenu[11], -1);
	TextDrawSetOutline(IconsMenu[11], 1);
	TextDrawSetProportional(IconsMenu[11], 1);
	TextDrawSetSelectable(IconsMenu[11], 0);

	TirDraw[0] = TextDrawCreate(499, 300, "-");
	TextDrawFont(TirDraw[0], 1);
	TextDrawLetterSize(TirDraw[0], 3.5, 8.7);
	TextDrawColor(TirDraw[0], 0xFFFFFFFF);
	TextDrawBackgroundColor(TirDraw[0],0xAFAFAFFF);
	TextDrawSetOutline(TirDraw[0], 1);

	TirDraw[1] = TextDrawCreate(500, 315, "-");
	TextDrawFont(TirDraw[1], 1);
	TextDrawLetterSize(TirDraw[1], 1.47, 8.7);
	TextDrawColor(TirDraw[1], 0xFFFFFFFF);
	TextDrawBackgroundColor(TirDraw[1],0xAFAFAFFF);
	TextDrawSetOutline(TirDraw[1], 1);

	TirDraw[2] = TextDrawCreate(520, 315, "-");
	TextDrawFont(TirDraw[2], 1);
	TextDrawLetterSize(TirDraw[2], 1.47, 8.7);
	TextDrawColor(TirDraw[2], 0xFFFFFFFF);
	TextDrawBackgroundColor(TirDraw[2],0xAFAFAFFF);
	TextDrawSetOutline(TirDraw[2], 1);

	TirDraw[3] = TextDrawCreate(500, 330, "-");
	TextDrawFont(TirDraw[3], 1);
	TextDrawLetterSize(TirDraw[3], 1.47, 8.7);
	TextDrawColor(TirDraw[3], 0xFFFFFFFF);
	TextDrawBackgroundColor(TirDraw[3],0xAFAFAFFF);
	TextDrawSetOutline(TirDraw[3], 1);

	TirDraw[4] = TextDrawCreate(520, 330, "-");
	TextDrawFont(TirDraw[4], 1);
	TextDrawLetterSize(TirDraw[4], 1.47, 8.7);
	TextDrawColor(TirDraw[4], 0xFFFFFFFF);
	TextDrawBackgroundColor(TirDraw[4],0xAFAFAFFF);
	TextDrawSetOutline(TirDraw[4], 1);

	HInfoBG = TextDrawCreate(390.000000, 171.000000, "New Textdraw");
	TextDrawBackgroundColor(HInfoBG, 255);
	TextDrawFont(HInfoBG, 1);
	TextDrawLetterSize(HInfoBG, 0.000000, 17.300001);
	TextDrawColor(HInfoBG, -1);
	TextDrawSetOutline(HInfoBG, 0);
	TextDrawSetProportional(HInfoBG, 1);
	TextDrawSetShadow(HInfoBG, 1);
	TextDrawUseBox(HInfoBG, 1);
	TextDrawBoxColor(HInfoBG, 85);
	TextDrawTextSize(HInfoBG, 602.000000, 1.000000);


	HInfoEnterDraw = TextDrawCreate(497.000000, 312.000000, "PRESS ~g~~k~~SNEAK_ABOUT~~w~ TO ENTER");
	TextDrawAlignment(HInfoEnterDraw, 2);
	TextDrawBackgroundColor(HInfoEnterDraw, 255);
	TextDrawFont(HInfoEnterDraw, 3);
	TextDrawLetterSize(HInfoEnterDraw, 0.500000, 1.000000);
	TextDrawColor(HInfoEnterDraw, -1);
	TextDrawSetOutline(HInfoEnterDraw, 0);
	TextDrawSetProportional(HInfoEnterDraw, 1);
	TextDrawSetShadow(HInfoEnterDraw, 1);

	HInfoBuyDraw = TextDrawCreate(497.000000, 312.000000, "PRESS ~g~~k~~CONVERSATION_NO~~w~ TO BUY");
	TextDrawAlignment(HInfoBuyDraw, 2);
	TextDrawBackgroundColor(HInfoBuyDraw, 255);
	TextDrawFont(HInfoBuyDraw, 3);
	TextDrawLetterSize(HInfoBuyDraw, 0.500000, 1.000000);
	TextDrawColor(HInfoBuyDraw, -1);
	TextDrawSetOutline(HInfoBuyDraw, 0);
	TextDrawSetProportional(HInfoBuyDraw, 1);
	TextDrawSetShadow(HInfoBuyDraw, 1);

	BandDrawBG[0] = TextDrawCreate(203.000000, 110.000000, "Band1");
	TextDrawBackgroundColor(BandDrawBG[0], 255);
	TextDrawFont(BandDrawBG[0], 1);
	TextDrawLetterSize(BandDrawBG[0], -0.000000, 1.33);
	TextDrawColor(BandDrawBG[0], -1);
	TextDrawSetOutline(BandDrawBG[0], 0);
	TextDrawSetProportional(BandDrawBG[0], 1);
	TextDrawSetShadow(BandDrawBG[0], 1);
	TextDrawUseBox(BandDrawBG[0], 1);
	TextDrawBoxColor(BandDrawBG[0], 0x00000099);
	TextDrawTextSize(BandDrawBG[0], 445.000000, 0.000000);

	BandDrawBG[1] = TextDrawCreate(205.000000, 112.000000, "Band2");
	TextDrawBackgroundColor(BandDrawBG[1], 255);
	TextDrawFont(BandDrawBG[1], 1);
	TextDrawLetterSize(BandDrawBG[1], -0.000000, 0.899999);
	TextDrawColor(BandDrawBG[1], -1);
	TextDrawSetOutline(BandDrawBG[1], 0);
	TextDrawSetProportional(BandDrawBG[1], 1);
	TextDrawSetShadow(BandDrawBG[1], 1);
	TextDrawUseBox(BandDrawBG[1], 1);
	TextDrawBoxColor(BandDrawBG[1], 0x88990055);
	TextDrawTextSize(BandDrawBG[1], 443.000000, 0.000000);
	////ieaa228
	Boxmenu0 = TextDrawCreate(439.000000, 383.000000, "box1");
	TextDrawBackgroundColor(Boxmenu0, 255);
	TextDrawFont(Boxmenu0, 1);
	TextDrawLetterSize(Boxmenu0, 0.000000, 3.400001);
	TextDrawUseBox(Boxmenu0, 1);
	TextDrawBoxColor(Boxmenu0, 80);
	TextDrawTextSize(Boxmenu0, 206.000000, 10.000000);
	TextDrawSetSelectable(Boxmenu0, 0);

	Boxmenu1 = TextDrawCreate(387.000000, 358.000000, "box2");
	TextDrawBackgroundColor(Boxmenu1, 255);
	TextDrawFont(Boxmenu1, 1);
	TextDrawLetterSize(Boxmenu1, 0.000000, 2.000000);
	TextDrawUseBox(Boxmenu1, 1);
	TextDrawBoxColor(Boxmenu1, 2132351487);
	TextDrawTextSize(Boxmenu1, 258.000000, 10.000000);
	TextDrawSetSelectable(Boxmenu1, 0);

	Boxmenu2 = TextDrawCreate(385.000000, 360.000000, "box3");
	TextDrawBackgroundColor(Boxmenu2, 255);
	TextDrawFont(Boxmenu2, 1);
	TextDrawLetterSize(Boxmenu2, 0.000000, 1.600000);
	TextDrawUseBox(Boxmenu2, 1);
	TextDrawBoxColor(Boxmenu2, 128);
	TextDrawTextSize(Boxmenu2, 260.000000, 10.000000);
	TextDrawSetSelectable(Boxmenu2, 0);

	ButtonLeft = TextDrawCreate(176.000000, 345.000000, "selecticon1");
	TextDrawBackgroundColor(ButtonLeft, 0);
	TextDrawFont(ButtonLeft, 5);
	TextDrawLetterSize(ButtonLeft, 0.500000, 1.000000);
	TextDrawColor(ButtonLeft, -1876547841);
	TextDrawTextSize(ButtonLeft, 73.000000, 65.000000);
	TextDrawSetPreviewModel(ButtonLeft, 19132);
	TextDrawSetPreviewRot(ButtonLeft, -40.000000, -90.000000, 90.000000, 1.000000);
	TextDrawSetSelectable(ButtonLeft, 1);

	ButtonRight = TextDrawCreate(396.000000, 345.000000, "selecticon2");
	TextDrawBackgroundColor(ButtonRight, 0);
	TextDrawFont(ButtonRight, 5);
	TextDrawLetterSize(ButtonRight, 0.500000, 1.000000);
	TextDrawColor(ButtonRight, -1876547841);
	TextDrawTextSize(ButtonRight, 73.000000, 65.000000);
	TextDrawSetPreviewModel(ButtonRight, 19132);
	TextDrawSetPreviewRot(ButtonRight, -40.000000, 90.000000, 90.000000, 1.000000);
	TextDrawSetSelectable(ButtonRight, 1);
	//////////////
	boxcancel = TextDrawCreate(233.000000, 367.000000, "selecticon3");
	TextDrawBackgroundColor(boxcancel, 0);
	TextDrawFont(boxcancel, 5);
	TextDrawLetterSize(boxcancel, 0.500000, 1.000000);
	TextDrawColor(boxcancel, -1876547841);
	TextDrawTextSize(boxcancel, 84.000000, 63.000000);
	TextDrawSetPreviewModel(boxcancel, 19447);
	TextDrawSetPreviewRot(boxcancel, -20.000000, 0.000000, 90.000000, 1.000000);
	TextDrawSetSelectable(boxcancel, 1);

	boxaccept = TextDrawCreate(327.000000, 367.000000, "selecticon3");
	TextDrawBackgroundColor(boxaccept, 0);
	TextDrawFont(boxaccept, 5);
	TextDrawLetterSize(boxaccept, 0.500000, 1.000000);
	TextDrawColor(boxaccept, -1876547841);
	TextDrawSetProportional(boxaccept, 1);
	TextDrawTextSize(boxaccept, 84.000000, 63.000000);
	TextDrawSetPreviewModel(boxaccept, 19447);
	TextDrawSetPreviewRot(boxaccept, -20.000000, 0.000000, 90.000000, 1.000000);
	TextDrawSetSelectable(boxaccept, 1);

	ButtonUp = TextDrawCreate( 558.000000, 434.000000, "Fire arms");
	TextDrawBackgroundColor( ButtonUp, 255);
	TextDrawFont( ButtonUp, 3);
	TextDrawLetterSize( ButtonUp, 0.500000, 1.000000);
	TextDrawColor( ButtonUp, -602653600);
	//TextDrawSetOutline( ButtonUp, 0);
	TextDrawSetProportional( ButtonUp, 1);
	TextDrawSetShadow( ButtonUp, 1);
	TextDrawSetSelectable( ButtonUp, 0);

	ButtonDown = TextDrawCreate(543.000000, 375.000000, "selectactiondown");
	TextDrawBackgroundColor(ButtonDown, 0);
	TextDrawFont(ButtonDown, 5);
	TextDrawLetterSize(ButtonDown, 0.500000, 1.000000);
	TextDrawColor(ButtonDown, -1876547841);
	TextDrawSetOutline(ButtonDown, 0);
	TextDrawSetProportional(ButtonDown, 1);
	TextDrawSetShadow(ButtonDown, 1);
	//TextDrawUseBox(ButtonDown, 1);
	//TextDrawBoxColor(ButtonDown, 255);
	TextDrawTextSize(ButtonDown, 73.000000, 65.000000);
	TextDrawSetPreviewModel(ButtonDown, 19132);
	TextDrawSetPreviewRot(ButtonDown, -40.000000, 0.000000, 90.000000, 1.000000);
	TextDrawSetSelectable(ButtonDown, 1);

	ButtonDown = TextDrawCreate(300.0, 300.0, "LD_BEAT:down");
	TextDrawFont(ButtonDown, 4);
	TextDrawTextSize(ButtonDown, 50, 25);
	TextDrawSetSelectable(ButtonDown, 1);

	ButtonCancel = TextDrawCreate(342.000000, 392.000000, "Cancel");
	TextDrawBackgroundColor(ButtonCancel, 255);
	TextDrawFont(ButtonCancel, 2);
	TextDrawLetterSize(ButtonCancel, 0.350000, 1.200000);
	TextDrawColor(ButtonCancel, -1);
	//TextDrawSetOutline(ButtonCancel, 1);
	TextDrawSetProportional(ButtonCancel, 1);
	TextDrawSetSelectable(ButtonCancel, 0);

	Boxmenu3 = TextDrawCreate(268.000000, 361.000000, "Select Action");
	TextDrawBackgroundColor(Boxmenu3, 255);
	TextDrawFont(Boxmenu3, 2);
	TextDrawLetterSize(Boxmenu3, 0.349999, 1.200000);
	TextDrawColor(Boxmenu3, -1);
	TextDrawSetOutline(Boxmenu3, 0);
	TextDrawSetProportional(Boxmenu3, 1);
	TextDrawSetShadow(Boxmenu3, 1);
	TextDrawSetSelectable(Boxmenu3, 0);

	/*BoxTaxi1 = TextDrawCreate(620.000000, 191.000000, "box1");
	TextDrawBackgroundColor(BoxTaxi1, 255);
	TextDrawFont(BoxTaxi1, 1);
	TextDrawLetterSize(BoxTaxi1, 0.000000, 5.300002);
	TextDrawColor(BoxTaxi1, 2020214864);
	TextDrawSetOutline(BoxTaxi1, 0);
	TextDrawSetProportional(BoxTaxi1, 1);
	TextDrawSetShadow(BoxTaxi1, 1);
	TextDrawUseBox(BoxTaxi1, 1);
	TextDrawBoxColor(BoxTaxi1, -1284241840);
	TextDrawTextSize(BoxTaxi1, 545.000000, 44.000000);
	TextDrawSetSelectable(BoxTaxi1, 0);

	BoxTaxi2 = TextDrawCreate(618.000000, 193.000000, "box1");
	TextDrawBackgroundColor(BoxTaxi2, 255);
	TextDrawFont(BoxTaxi2, 1);
	TextDrawLetterSize(BoxTaxi2, 0.000000, 4.800001);
	TextDrawColor(BoxTaxi2, -1);
	TextDrawSetOutline(BoxTaxi2, 0);
	TextDrawSetProportional(BoxTaxi2, 1);
	TextDrawSetShadow(BoxTaxi2, 1);
	TextDrawUseBox(BoxTaxi2, 1);
	TextDrawBoxColor(BoxTaxi2, 80);
	TextDrawTextSize(BoxTaxi2, 547.000000, 27.000000);
	TextDrawSetSelectable(BoxTaxi2, 0);

	Taximonitor = TextDrawCreate(556.000000, 194.000000, "Monitoring");
	TextDrawBackgroundColor(Taximonitor, 255);
	TextDrawFont(Taximonitor, 2);
	TextDrawLetterSize(Taximonitor, 0.209999, 0.799998);
	TextDrawColor(Taximonitor, -1);
	TextDrawSetOutline(Taximonitor, 0);
	TextDrawSetProportional(Taximonitor, 1);
	TextDrawSetShadow(Taximonitor, 1);
	TextDrawSetSelectable(Taximonitor, 0);

	TaxiDol = TextDrawCreate(566.000000, 206.000000, "$");
	TextDrawBackgroundColor(TaxiDol, 255);
	TextDrawFont(TaxiDol, 2);
	TextDrawLetterSize(TaxiDol, 0.239999, 1.499998);
	TextDrawColor(TaxiDol, -1);
	TextDrawSetOutline(TaxiDol, 0);
	TextDrawSetProportional(TaxiDol, 1);
	TextDrawSetShadow(TaxiDol, 1);
	TextDrawSetSelectable(TaxiDol, 0);

	TaxiServ = TextDrawCreate(562.000000, 227.000000, "taxi service");
	TextDrawBackgroundColor(TaxiServ, 255);
	TextDrawFont(TaxiServ, 2);
	TextDrawLetterSize(TaxiServ, 0.149999, 0.799998);
	TextDrawColor(TaxiServ, -1);
	TextDrawSetOutline(TaxiServ, 0);
	TextDrawSetProportional(TaxiServ, 1);
	TextDrawSetShadow(TaxiServ, 1);
	TextDrawSetSelectable(TaxiServ, 0);*/

	ButtonSelect = TextDrawCreate(247.000000, 392.000000, "Accept");
	TextDrawBackgroundColor(ButtonSelect, 255);
	TextDrawFont(ButtonSelect, 2);
	TextDrawLetterSize(ButtonSelect, 0.350000, 1.200000);
	TextDrawColor(ButtonSelect, -1);
	//TextDrawSetOutline(ButtonSelect, 1);
	TextDrawSetProportional(ButtonSelect, 1);
	TextDrawSetSelectable(ButtonSelect, 0);

	ShieldBG[0] = TextDrawCreate(610.0,57.8,"_");
	TextDrawLetterSize(ShieldBG[0],0.0,0.57);
	TextDrawUseBox(ShieldBG[0],1);
	TextDrawBoxColor(ShieldBG[0],COLOR_SHBAR_BG);
	TextDrawTextSize(ShieldBG[0],544.5,0.0);

	ShieldBG[1] = TextDrawCreate(608.0,59.6,"_");
	TextDrawLetterSize(ShieldBG[1],0.0,0.135);
	TextDrawUseBox(ShieldBG[1],1);
	TextDrawBoxColor(ShieldBG[1],COLOR_SHBAR_BG2);
	TextDrawTextSize(ShieldBG[1],546.5,0.0);

	FuelDrawBG[0] = TextDrawCreate(320.000000, 244.000000, "BackGround1");
	TextDrawAlignment(FuelDrawBG[0], 2);
	TextDrawBackgroundColor(FuelDrawBG[0], 255);
	TextDrawFont(FuelDrawBG[0], 1);
	TextDrawLetterSize(FuelDrawBG[0], 0.000000, 5.099997);
	TextDrawColor(FuelDrawBG[0], -1);
	TextDrawSetOutline(FuelDrawBG[0], 0);
	TextDrawSetProportional(FuelDrawBG[0], 1);
	TextDrawSetShadow(FuelDrawBG[0], 1);
	TextDrawUseBox(FuelDrawBG[0], 1);
	TextDrawBoxColor(FuelDrawBG[0], -1347440641);
	TextDrawTextSize(FuelDrawBG[0], 0.000000, 311.000000);

	FuelDrawBG[1] = TextDrawCreate(320.000000, 248.000000, "BackGround2");
	TextDrawAlignment(FuelDrawBG[1], 2);
	TextDrawBackgroundColor(FuelDrawBG[1], 255);
	TextDrawFont(FuelDrawBG[1], 1);
	TextDrawLetterSize(FuelDrawBG[1], 0.000000, 4.099998);
	TextDrawColor(FuelDrawBG[1], -1);
	TextDrawSetOutline(FuelDrawBG[1], 0);
	TextDrawSetProportional(FuelDrawBG[1], 1);
	TextDrawSetShadow(FuelDrawBG[1], 1);
	TextDrawUseBox(FuelDrawBG[1], 1);
	TextDrawBoxColor(FuelDrawBG[1], 255);
	TextDrawTextSize(FuelDrawBG[1], 0.000000, 300.000000);

	FuelNextBG[0] = TextDrawCreate(459.000000, 248.000000, "Fuel + BG");
	TextDrawAlignment(FuelNextBG[0], 2);
	TextDrawBackgroundColor(FuelNextBG[0], 255);
	TextDrawFont(FuelNextBG[0], 3);
	TextDrawLetterSize(FuelNextBG[0], 0.000000, 4.099997);
	TextDrawColor(FuelNextBG[0], -1);
	TextDrawSetOutline(FuelNextBG[0], 1);
	TextDrawSetProportional(FuelNextBG[0], 1);
	TextDrawUseBox(FuelNextBG[0], 1);
	TextDrawBoxColor(FuelNextBG[0], 0xFF6347FF);
	TextDrawTextSize(FuelNextBG[0], 0.000000, 22.000000);

	FuelNextBG[1] = TextDrawCreate(182.000000, 248.000000, "Fuel - BG");
	TextDrawAlignment(FuelNextBG[1], 2);
	TextDrawBackgroundColor(FuelNextBG[1], 255);
	TextDrawFont(FuelNextBG[1], 3);
	TextDrawLetterSize(FuelNextBG[1], 0.000000, 4.099997);
	TextDrawColor(FuelNextBG[1], -1);
	TextDrawSetOutline(FuelNextBG[1], 1);
	TextDrawSetProportional(FuelNextBG[1], 1);
	TextDrawUseBox(FuelNextBG[1], 1);
	TextDrawBoxColor(FuelNextBG[1], 0xFF6347FF);
	TextDrawTextSize(FuelNextBG[1], 0.000000, 24.000000);

	FuelBackKey[0] = TextDrawCreate(203.000000, 266.000000, "LD_BEAT:left");
	TextDrawBackgroundColor(FuelBackKey[0], 255);
	TextDrawFont(FuelBackKey[0], 4);
	TextDrawLetterSize(FuelBackKey[0], 0.500000, 1.000000);
	TextDrawColor(FuelBackKey[0], 16777215);
	TextDrawSetOutline(FuelBackKey[0], 0);
	TextDrawSetProportional(FuelBackKey[0], 1);
	TextDrawSetShadow(FuelBackKey[0], 1);
	TextDrawUseBox(FuelBackKey[0], 1);
	TextDrawBoxColor(FuelBackKey[0], 255);
	TextDrawTextSize(FuelBackKey[0], 28.000000, 17.000000);
	TextDrawSetSelectable(FuelBackKey[0], true);

	FuelNextKey[0] = TextDrawCreate(403.000000, 266.000000, "LD_BEAT:right");
	TextDrawBackgroundColor(FuelNextKey[0], 255);
	TextDrawFont(FuelNextKey[0], 4);
	TextDrawLetterSize(FuelNextKey[0], 0.500000, 1.000000);
	TextDrawColor(FuelNextKey[0], 16777215);
	TextDrawSetOutline(FuelNextKey[0], 0);
	TextDrawSetProportional(FuelNextKey[0], 1);
	TextDrawSetShadow(FuelNextKey[0], 1);
	TextDrawUseBox(FuelNextKey[0], 1);
	TextDrawBoxColor(FuelNextKey[0], 255);
	TextDrawTextSize(FuelNextKey[0], 28.000000, 17.000000);
	TextDrawSetSelectable(FuelNextKey[0], true);

	FuelBarDraw = TextDrawCreate(401.000000, 268.000000, "FuelBar1");
	TextDrawBackgroundColor(FuelBarDraw, 255);
	TextDrawFont(FuelBarDraw, 1);
	TextDrawLetterSize(FuelBarDraw, 0.000000, 1.399999);
	TextDrawColor(FuelBarDraw, -1);
	TextDrawSetOutline(FuelBarDraw, 0);
	TextDrawSetProportional(FuelBarDraw, 1);
	TextDrawSetShadow(FuelBarDraw, 1);
	TextDrawUseBox(FuelBarDraw, 1);
	TextDrawBoxColor(FuelBarDraw, -11206401);
	TextDrawTextSize(FuelBarDraw, 233.000000, 0.000000);

	FuelBackKey[1] = TextDrawCreate(172.000000, 249.000000, "LD_BEAT:left");
	TextDrawBackgroundColor(FuelBackKey[1], 255);
	TextDrawFont(FuelBackKey[1], 4);
	TextDrawLetterSize(FuelBackKey[1], 0.500000, 1.000000);
	TextDrawColor(FuelBackKey[1], -65281);
	TextDrawSetOutline(FuelBackKey[1], 0);
	TextDrawSetProportional(FuelBackKey[1], 1);
	TextDrawSetShadow(FuelBackKey[1], 1);
	TextDrawUseBox(FuelBackKey[1], 1);
	TextDrawBoxColor(FuelBackKey[1], 255);
	TextDrawTextSize(FuelBackKey[1], 19.000000, 36.000000);
	TextDrawSetSelectable(FuelBackKey[1], true);

	FuelNextKey[1] = TextDrawCreate(450.000000, 249.000000, "LD_BEAT:right");
	TextDrawBackgroundColor(FuelNextKey[1], 255);
	TextDrawFont(FuelNextKey[1], 4);
	TextDrawLetterSize(FuelNextKey[1], 0.500000, 1.000000);
	TextDrawColor(FuelNextKey[1], -65281);
	TextDrawSetOutline(FuelNextKey[1], 0);
	TextDrawSetProportional(FuelNextKey[1], 1);
	TextDrawSetShadow(FuelNextKey[1], 1);
	TextDrawUseBox(FuelNextKey[1], 1);
	TextDrawBoxColor(FuelNextKey[1], 255);
	TextDrawTextSize(FuelNextKey[1], 19.000000, 36.000000);
	TextDrawSetSelectable(FuelNextKey[1], true);

	FuelSelectDraw = TextDrawCreate(400.000000, 295.000000, "Fill");
	TextDrawBackgroundColor(FuelSelectDraw, 255);
	TextDrawFont(FuelSelectDraw, 3);
	TextDrawLetterSize(FuelSelectDraw, 0.990000, 2.300000);
	TextDrawColor(FuelSelectDraw, -1);
	TextDrawSetOutline(FuelSelectDraw, 1);
	TextDrawTextSize(FuelSelectDraw, 460.0, 20.0);
	TextDrawSetProportional(FuelSelectDraw, 1);
	TextDrawSetSelectable(FuelSelectDraw, true);

	FuelCancelDraw = TextDrawCreate(183.000000, 295.000000, "Cancel");
	TextDrawBackgroundColor(FuelCancelDraw, 255);
	TextDrawFont(FuelCancelDraw, 3);
	TextDrawLetterSize(FuelCancelDraw, 0.730000, 2.299999);
	TextDrawTextSize(FuelCancelDraw, 260.0, 20.0);
	TextDrawColor(FuelCancelDraw, -1);
	TextDrawSetOutline(FuelCancelDraw, 1);
	TextDrawSetProportional(FuelCancelDraw, 1);
	TextDrawSetSelectable(FuelCancelDraw, true);

	FuelKeyBG = TextDrawCreate(165.000000, 141.000000, "New Textdraw");
	TextDrawBackgroundColor(FuelKeyBG, 255);
	TextDrawFont(FuelKeyBG, 1);
	TextDrawLetterSize(FuelKeyBG, 0.000000, 9.699998);
	TextDrawColor(FuelKeyBG, -1);
	TextDrawSetOutline(FuelKeyBG, 0);
	TextDrawSetProportional(FuelKeyBG, 1);
	TextDrawSetShadow(FuelKeyBG, 1);
	TextDrawUseBox(FuelKeyBG, 1);
	TextDrawBoxColor(FuelKeyBG, 255);
	TextDrawTextSize(FuelKeyBG, 305.000000, 0.000000);

	FuelKeyDraw[0] = TextDrawCreate(287.000000, 204.000000, "0");
	TextDrawAlignment(FuelKeyDraw[0], 2);
	TextDrawBackgroundColor(FuelKeyDraw[0], 255);
	TextDrawFont(FuelKeyDraw[0], 1);
	TextDrawLetterSize(FuelKeyDraw[0], 0.699999, 2.099999);
	TextDrawColor(FuelKeyDraw[0], -65281);
	TextDrawSetOutline(FuelKeyDraw[0], 1);
	TextDrawSetProportional(FuelKeyDraw[0], 1);
	TextDrawUseBox(FuelKeyDraw[0], 1);
	TextDrawBoxColor(FuelKeyDraw[0], 16777215);
	TextDrawTextSize(FuelKeyDraw[0], 20.000000, 24.000000);
	TextDrawSetSelectable(FuelKeyDraw[0], true);

	FuelKeyDraw[1] = TextDrawCreate(183.000000, 146.000000, "1");
	TextDrawAlignment(FuelKeyDraw[1], 2);
	TextDrawBackgroundColor(FuelKeyDraw[1], 255);
	TextDrawFont(FuelKeyDraw[1], 1);
	TextDrawLetterSize(FuelKeyDraw[1], 0.699999, 2.099999);
	TextDrawColor(FuelKeyDraw[1], -65281);
	TextDrawSetOutline(FuelKeyDraw[1], 1);
	TextDrawSetProportional(FuelKeyDraw[1], 1);
	TextDrawUseBox(FuelKeyDraw[1], 1);
	TextDrawBoxColor(FuelKeyDraw[1], 16777215);
	TextDrawTextSize(FuelKeyDraw[1], 20.000000, 24.000000);
	TextDrawSetSelectable(FuelKeyDraw[1], true);

	FuelKeyDraw[2] = TextDrawCreate(218.000000, 146.000000, "2");
	TextDrawAlignment(FuelKeyDraw[2], 2);
	TextDrawBackgroundColor(FuelKeyDraw[2], 255);
	TextDrawFont(FuelKeyDraw[2], 1);
	TextDrawLetterSize(FuelKeyDraw[2], 0.699999, 2.099999);
	TextDrawColor(FuelKeyDraw[2], -65281);
	TextDrawSetOutline(FuelKeyDraw[2], 1);
	TextDrawSetProportional(FuelKeyDraw[2], 1);
	TextDrawUseBox(FuelKeyDraw[2], 1);
	TextDrawBoxColor(FuelKeyDraw[2], 16777215);
	TextDrawTextSize(FuelKeyDraw[2], 20.000000, 24.000000);
	TextDrawSetSelectable(FuelKeyDraw[2], true);

	FuelKeyDraw[3] = TextDrawCreate(253.000000, 146.000000, "3");
	TextDrawAlignment(FuelKeyDraw[3], 2);
	TextDrawBackgroundColor(FuelKeyDraw[3], 255);
	TextDrawFont(FuelKeyDraw[3], 1);
	TextDrawLetterSize(FuelKeyDraw[3], 0.699999, 2.099999);
	TextDrawColor(FuelKeyDraw[3], -65281);
	TextDrawSetOutline(FuelKeyDraw[3], 1);
	TextDrawSetProportional(FuelKeyDraw[3], 1);
	TextDrawUseBox(FuelKeyDraw[3], 1);
	TextDrawBoxColor(FuelKeyDraw[3], 16777215);
	TextDrawTextSize(FuelKeyDraw[3], 20.000000, 24.000000);
	TextDrawSetSelectable(FuelKeyDraw[3], true);

	FuelKeyDraw[4] = TextDrawCreate(183.000000, 175.000000, "4");
	TextDrawAlignment(FuelKeyDraw[4], 2);
	TextDrawBackgroundColor(FuelKeyDraw[4], 255);
	TextDrawFont(FuelKeyDraw[4], 1);
	TextDrawLetterSize(FuelKeyDraw[4], 0.699999, 2.099999);
	TextDrawColor(FuelKeyDraw[4], -65281);
	TextDrawSetOutline(FuelKeyDraw[4], 1);
	TextDrawSetProportional(FuelKeyDraw[4], 1);
	TextDrawUseBox(FuelKeyDraw[4], 1);
	TextDrawBoxColor(FuelKeyDraw[4], 16777215);
	TextDrawTextSize(FuelKeyDraw[4], 20.000000, 24.000000);
	TextDrawSetSelectable(FuelKeyDraw[4], true);

	FuelKeyDraw[5] = TextDrawCreate(218.000000, 175.000000, "5");
	TextDrawAlignment(FuelKeyDraw[5], 2);
	TextDrawBackgroundColor(FuelKeyDraw[5], 255);
	TextDrawFont(FuelKeyDraw[5], 1);
	TextDrawLetterSize(FuelKeyDraw[5], 0.699999, 2.099999);
	TextDrawColor(FuelKeyDraw[5], -65281);
	TextDrawSetOutline(FuelKeyDraw[5], 1);
	TextDrawSetProportional(FuelKeyDraw[5], 1);
	TextDrawUseBox(FuelKeyDraw[5], 1);
	TextDrawBoxColor(FuelKeyDraw[5], 16777215);
	TextDrawTextSize(FuelKeyDraw[5], 20.000000, 24.000000);
	TextDrawSetSelectable(FuelKeyDraw[5], true);

	FuelKeyDraw[6] = TextDrawCreate(253.000000, 175.000000, "6");
	TextDrawAlignment(FuelKeyDraw[6], 2);
	TextDrawBackgroundColor(FuelKeyDraw[6], 255);
	TextDrawFont(FuelKeyDraw[6], 1);
	TextDrawLetterSize(FuelKeyDraw[6], 0.699999, 2.099999);
	TextDrawColor(FuelKeyDraw[6], -65281);
	TextDrawSetOutline(FuelKeyDraw[6], 1);
	TextDrawSetProportional(FuelKeyDraw[6], 1);
	TextDrawUseBox(FuelKeyDraw[6], 1);
	TextDrawBoxColor(FuelKeyDraw[6], 16777215);
	TextDrawTextSize(FuelKeyDraw[6], 20.000000, 24.000000);
	TextDrawSetSelectable(FuelKeyDraw[6], true);

	FuelKeyDraw[7] = TextDrawCreate(183.000000, 204.000000, "7");
	TextDrawAlignment(FuelKeyDraw[7], 2);
	TextDrawBackgroundColor(FuelKeyDraw[7], 255);
	TextDrawFont(FuelKeyDraw[7], 1);
	TextDrawLetterSize(FuelKeyDraw[7], 0.699999, 2.099999);
	TextDrawColor(FuelKeyDraw[7], -65281);
	TextDrawSetOutline(FuelKeyDraw[7], 1);
	TextDrawSetProportional(FuelKeyDraw[7], 1);
	TextDrawUseBox(FuelKeyDraw[7], 1);
	TextDrawBoxColor(FuelKeyDraw[7], 16777215);
	TextDrawTextSize(FuelKeyDraw[7], 20.000000, 24.000000);
	TextDrawSetSelectable(FuelKeyDraw[7], true);

	FuelKeyDraw[8] = TextDrawCreate(218.000000, 204.000000, "8");
	TextDrawAlignment(FuelKeyDraw[8], 2);
	TextDrawBackgroundColor(FuelKeyDraw[8], 255);
	TextDrawFont(FuelKeyDraw[8], 1);
	TextDrawLetterSize(FuelKeyDraw[8], 0.699999, 2.099999);
	TextDrawColor(FuelKeyDraw[8], -65281);
	TextDrawSetOutline(FuelKeyDraw[8], 1);
	TextDrawSetProportional(FuelKeyDraw[8], 1);
	TextDrawUseBox(FuelKeyDraw[8], 1);
	TextDrawBoxColor(FuelKeyDraw[8], 16777215);
	TextDrawTextSize(FuelKeyDraw[8], 20.000000, 24.000000);
	TextDrawSetSelectable(FuelKeyDraw[8], true);

	FuelKeyDraw[9] = TextDrawCreate(253.000000, 204.000000, "9");
	TextDrawAlignment(FuelKeyDraw[9], 2);
	TextDrawBackgroundColor(FuelKeyDraw[9], 255);
	TextDrawFont(FuelKeyDraw[9], 1);
	TextDrawLetterSize(FuelKeyDraw[9], 0.699999, 2.099999);
	TextDrawColor(FuelKeyDraw[9], -65281);
	TextDrawSetOutline(FuelKeyDraw[9], 1);
	TextDrawSetProportional(FuelKeyDraw[9], 1);
	TextDrawUseBox(FuelKeyDraw[9], 1);
	TextDrawBoxColor(FuelKeyDraw[9], 16777215);
	TextDrawTextSize(FuelKeyDraw[9], 20.000000, 24.000000);
	TextDrawSetSelectable(FuelKeyDraw[9], true);

	FuelOtherDraw = TextDrawCreate(287.000000, 146.000000, "0");
	TextDrawAlignment(FuelOtherDraw, 2);
	TextDrawBackgroundColor(FuelOtherDraw, 255);
	TextDrawFont(FuelOtherDraw, 1);
	TextDrawLetterSize(FuelOtherDraw, -0.000000, 5.299999);
	TextDrawColor(FuelOtherDraw, -65281);
	TextDrawSetOutline(FuelOtherDraw, 1);
	TextDrawSetProportional(FuelOtherDraw, 1);
	TextDrawUseBox(FuelOtherDraw, 1);
	TextDrawBoxColor(FuelOtherDraw, -1347440641);
	TextDrawTextSize(FuelOtherDraw, 20.000000, 24.000000);
	TextDrawSetSelectable(FuelOtherDraw, true);

	//====speed=====
	speedbox[0] = TextDrawCreate( 513.000000, 356.000000, "_");
	TextDrawBackgroundColor( speedbox[0], 255);
	TextDrawFont( speedbox[0], 1);
	TextDrawLetterSize( speedbox[0], 0.500000, 7.099998);
	TextDrawColor( speedbox[0], 144);
	TextDrawSetOutline( speedbox[0], 0);
	TextDrawSetProportional( speedbox[0], 1);
	TextDrawSetShadow( speedbox[0], 1);
	TextDrawUseBox( speedbox[0], 1);
	TextDrawBoxColor( speedbox[0], 144);
	TextDrawTextSize( speedbox[0], 621.000000, 0.000000);
	TextDrawSetSelectable( speedbox[0], 0);

	speedbox[1] = TextDrawCreate( 513.000000, 430.000000, "_");
	TextDrawBackgroundColor( speedbox[1], 255);
	TextDrawFont( speedbox[1], 1);
	TextDrawLetterSize( speedbox[1], 0.500000, 1.499999);
	TextDrawColor( speedbox[1], 144);
	TextDrawSetOutline( speedbox[1], 0);
	TextDrawSetProportional( speedbox[1], 1);
	TextDrawSetShadow( speedbox[1], 1);
	TextDrawUseBox( speedbox[1], 1);
	TextDrawBoxColor( speedbox[1], 144);
	TextDrawTextSize( speedbox[1], 621.000000, 0.000000);
	TextDrawSetSelectable( speedbox[1], 0);

	speedbox[2] = TextDrawCreate( 567.000000, 360.000000, "_");
	TextDrawAlignment( speedbox[2], 2);
	TextDrawBackgroundColor( speedbox[2], 255);
	TextDrawFont( speedbox[2], 3);
	TextDrawLetterSize( speedbox[2], 0.629999, 2.700001);
	TextDrawColor( speedbox[2], -65);
	TextDrawSetOutline( speedbox[2], 1);
	TextDrawSetProportional( speedbox[2], 1);
	TextDrawUseBox( speedbox[2], 1);
	TextDrawBoxColor( speedbox[2], -1407312129);
	TextDrawTextSize( speedbox[2], 714.000000, 103.000000);
	TextDrawSetSelectable( speedbox[2], 0);

	speedbox[3] = TextDrawCreate( 513.000000, 462.000000, "_");
	TextDrawBackgroundColor( speedbox[3], 255);
	TextDrawFont( speedbox[3], 1);
	TextDrawLetterSize( speedbox[3], 0.500000, 7.099998);
	TextDrawColor( speedbox[3], 144);
	TextDrawSetOutline( speedbox[3], 0);
	TextDrawSetProportional( speedbox[3], 1);
	TextDrawSetShadow( speedbox[3], 1);
	TextDrawUseBox( speedbox[3], 1);
	TextDrawBoxColor( speedbox[3], 144);
	TextDrawTextSize( speedbox[3], 621.000000, 0.000000);
	TextDrawSetSelectable( speedbox[3], 0);
	//====speed=====
	//ShopEatResp
	BoxShopEat1 = TextDrawCreate(436.000000, 176.000000, "box1");
	TextDrawBackgroundColor(BoxShopEat1, 255);
	TextDrawFont(BoxShopEat1, 1);
	TextDrawLetterSize(BoxShopEat1, 0.000000, 15.100000);
	TextDrawColor(BoxShopEat1, -1);
	TextDrawSetOutline(BoxShopEat1, 0);
	TextDrawSetProportional(BoxShopEat1, 1);
	TextDrawSetShadow(BoxShopEat1, 1);
	TextDrawUseBox(BoxShopEat1, 1);
	TextDrawBoxColor(BoxShopEat1, 80);
	TextDrawTextSize(BoxShopEat1, 206.000000, 10.000000);
	TextDrawSetSelectable(BoxShopEat1, 0);

	BoxShopEat2 = TextDrawCreate(387.000000, 166.000000, "box2");
	TextDrawBackgroundColor(BoxShopEat2, 255);
	TextDrawFont(BoxShopEat2, 1);
	TextDrawLetterSize(BoxShopEat2, 0.000000, 1.999999);
	TextDrawColor(BoxShopEat2, -1);
	TextDrawSetOutline(BoxShopEat2, 0);
	TextDrawSetProportional(BoxShopEat2, 1);
	TextDrawSetShadow(BoxShopEat2, 1);
	TextDrawUseBox(BoxShopEat2, 1);
	TextDrawBoxColor(BoxShopEat2, 2132351487);
	TextDrawTextSize(BoxShopEat2, 258.000000, 10.000000);
	TextDrawSetSelectable(BoxShopEat2, 0);

	BoxShopEat3 = TextDrawCreate(385.000000, 168.000000, "box3");
	TextDrawBackgroundColor(BoxShopEat3, 255);
	TextDrawFont(BoxShopEat3, 1);
	TextDrawLetterSize(BoxShopEat3, 0.000000, 1.600000);
	TextDrawColor(BoxShopEat3, -1);
	TextDrawSetOutline(BoxShopEat3, 0);
	TextDrawSetProportional(BoxShopEat3, 1);
	TextDrawSetShadow(BoxShopEat3, 1);
	TextDrawUseBox(BoxShopEat3, 1);
	TextDrawBoxColor(BoxShopEat3, 128);
	TextDrawTextSize(BoxShopEat3, 260.000000, 10.000000);
	TextDrawSetSelectable(BoxShopEat3, 0);

	BoxShopEat4 = TextDrawCreate(436.000000, 289.000000, "box4");
	TextDrawBackgroundColor(BoxShopEat4, 255);
	TextDrawFont(BoxShopEat4, 1);
	TextDrawLetterSize(BoxShopEat4, 0.000000, 2.000000);
	TextDrawColor(BoxShopEat4, -1);
	TextDrawSetOutline(BoxShopEat4, 0);
	TextDrawSetProportional(BoxShopEat4, 1);
	TextDrawSetShadow(BoxShopEat4, 1);
	TextDrawUseBox(BoxShopEat4, 1);
	TextDrawBoxColor(BoxShopEat4, 80);
	TextDrawTextSize(BoxShopEat4, 206.000000, 10.000000);
	TextDrawSetSelectable(BoxShopEat4, 0);

	BoxShopEat5 = TextDrawCreate(320.000000, 194.000000, "box5");
	TextDrawBackgroundColor(BoxShopEat5, 255);
	TextDrawFont(BoxShopEat5, 1);
	TextDrawLetterSize(BoxShopEat5, 0.000000, 9.499998);
	TextDrawColor(BoxShopEat5, -1);
	TextDrawSetOutline(BoxShopEat5, 0);
	TextDrawSetProportional(BoxShopEat5, 1);
	TextDrawSetShadow(BoxShopEat5, 1);
	TextDrawUseBox(BoxShopEat5, 1);
	TextDrawBoxColor(BoxShopEat5, 80);
	TextDrawTextSize(BoxShopEat5, 226.000000, 10.000000);
	TextDrawSetSelectable(BoxShopEat5, 0);

	BoxShopEat6 = TextDrawCreate(419.000000, 194.000000, "box6");
	TextDrawBackgroundColor(BoxShopEat6, 255);
	TextDrawFont(BoxShopEat6, 1);
	TextDrawLetterSize(BoxShopEat6, 0.000000, 9.499998);
	TextDrawColor(BoxShopEat6, -1);
	TextDrawSetOutline(BoxShopEat6, 0);
	TextDrawSetProportional(BoxShopEat6, 1);
	TextDrawSetShadow(BoxShopEat6, 1);
	TextDrawUseBox(BoxShopEat6, 1);
	TextDrawBoxColor(BoxShopEat6, 80);
	TextDrawTextSize(BoxShopEat6, 329.000000, 10.000000);
	TextDrawSetSelectable(BoxShopEat6, 0);

	EatShopEat1 = TextDrawCreate(253.000000, 267.000000, "burger");
	TextDrawBackgroundColor(EatShopEat1, 255);
	TextDrawFont(EatShopEat1, 2);
	TextDrawLetterSize(EatShopEat1, 0.349999, 1.200000);
	TextDrawColor(EatShopEat1, -1);
	TextDrawSetOutline(EatShopEat1, 1);
	TextDrawSetProportional(EatShopEat1, 1);
	TextDrawSetSelectable(EatShopEat1, 0);

	EatShopEat2 = TextDrawCreate(348.000000, 267.000000, "pizza");
	TextDrawBackgroundColor(EatShopEat2, 255);
	TextDrawFont(EatShopEat2, 2);
	TextDrawLetterSize(EatShopEat2, 0.349999, 1.200000);
	TextDrawColor(EatShopEat2, -1);
	TextDrawSetOutline(EatShopEat2, 1);
	TextDrawSetProportional(EatShopEat2, 1);
	TextDrawSetSelectable(EatShopEat2, 0);

	IconShopsEat2 = TextDrawCreate(333.000000, 272.000000, "icon2");
	TextDrawBackgroundColor(IconShopsEat2, 0);
	TextDrawFont(IconShopsEat2, 5);
	TextDrawLetterSize(IconShopsEat2, 0.500000, -0.000000);
	TextDrawColor(IconShopsEat2, 0xFF6347FF);
	TextDrawSetOutline(IconShopsEat2, 0);
	TextDrawSetProportional(IconShopsEat2, 1);
	TextDrawSetShadow(IconShopsEat2, 1);
	TextDrawTextSize(IconShopsEat2, 84.000000, 53.000000);
	TextDrawSetPreviewModel(IconShopsEat2, 19447);
	TextDrawSetPreviewRot(IconShopsEat2, -20.000000, 0.000000, 90.000000, 1.000000);
	TextDrawSetSelectable(IconShopsEat2, 1);

	CenaShopEat1 = TextDrawCreate(260.000000, 293.000000, "None");
	TextDrawBackgroundColor(CenaShopEat1, 255);
	TextDrawFont(CenaShopEat1, 2);
	TextDrawLetterSize(CenaShopEat1, 0.390000, 1.000000);
	TextDrawColor(CenaShopEat1, -1);
	TextDrawSetOutline(CenaShopEat1, 1);
	TextDrawSetProportional(CenaShopEat1, 1);
	TextDrawSetSelectable(CenaShopEat1, 0);

	SelectShopEat1 = TextDrawCreate(282.000000, 169.000000, "select eat");
	TextDrawBackgroundColor(SelectShopEat1, 255);
	TextDrawFont(SelectShopEat1, 2);
	TextDrawLetterSize(SelectShopEat1, 0.349999, 1.200000);
	TextDrawColor(SelectShopEat1, -1);
	TextDrawSetOutline(SelectShopEat1, 0);
	TextDrawSetProportional(SelectShopEat1, 1);
	TextDrawSetShadow(SelectShopEat1, 1);
	TextDrawSetSelectable(SelectShopEat1, 0);

	IconShopEat1 = TextDrawCreate(229.000000, 204.000000, "iconpizza");
	TextDrawBackgroundColor(IconShopEat1, 0);
	TextDrawFont(IconShopEat1, 5);
	TextDrawLetterSize(IconShopEat1, 0.500000, -0.000000);
	TextDrawColor(IconShopEat1, -1);
	TextDrawSetOutline(IconShopEat1, 0);
	TextDrawSetProportional(IconShopEat1, 1);
	TextDrawSetShadow(IconShopEat1, 1);
	TextDrawTextSize(IconShopEat1, 84.000000, 53.000000);
	TextDrawSetPreviewModel(IconShopEat1, 2663);
	TextDrawSetPreviewRot(IconShopEat1, 0.000000, 0.000000, 30.000000, 1.000000);
	TextDrawSetSelectable(IconShopEat1, 0);

	IconShopEat2 = TextDrawCreate(334.000000, 204.000000, "iconpack");
	TextDrawBackgroundColor(IconShopEat2, 0);
	TextDrawFont(IconShopEat2, 5);
	TextDrawLetterSize(IconShopEat2, 0.500000, -0.000000);
	TextDrawColor(IconShopEat2, -1);
	TextDrawSetOutline(IconShopEat2, 0);
	TextDrawSetProportional(IconShopEat2, 1);
	TextDrawSetShadow(IconShopEat2, 1);
	TextDrawTextSize(IconShopEat2, 84.000000, 53.000000);
	TextDrawSetPreviewModel(IconShopEat2, 1582);
	TextDrawSetPreviewRot(IconShopEat2, 120.000000, 0.000000, 0.000000, 1.000000);
	TextDrawSetSelectable(IconShopEat2, 0);

	alcodraw1[6] = TextDrawCreate(90.000000, 139.000000, "_");
	TextDrawBackgroundColor(alcodraw1[6], 255);
	TextDrawFont(alcodraw1[6], 1);
	TextDrawLetterSize(alcodraw1[6], 0.500000, 17.099998);
	TextDrawColor(alcodraw1[6], -1);
	TextDrawSetOutline(alcodraw1[6], 0);
	TextDrawSetProportional(alcodraw1[6], 1);
	TextDrawSetShadow(alcodraw1[6], 1);
	TextDrawUseBox(alcodraw1[6], 1);
	TextDrawBoxColor(alcodraw1[6], 48);
	TextDrawTextSize(alcodraw1[6], 241.000000, 1.000000);
	TextDrawSetSelectable(alcodraw1[6], 0);

	alcodraw1[5] = TextDrawCreate(179.000000, 296.000000, "close");
	TextDrawBackgroundColor(alcodraw1[5], 255);
	TextDrawFont(alcodraw1[5], 2);
	TextDrawLetterSize(alcodraw1[5], 0.500000, 1.299999);
	TextDrawColor(alcodraw1[5], -1);
	TextDrawSetOutline(alcodraw1[5], 0);
	TextDrawSetProportional(alcodraw1[5], 1);
	TextDrawSetShadow(alcodraw1[5], 1);
	TextDrawSetSelectable(alcodraw1[5], 1);

	alcodraw[0] = TextDrawCreate(92.000000, 142.000000, "ld_beat:up");
	alcodraw[1] = TextDrawCreate(141.000000, 142.000000, "ld_beat:up");
	alcodraw[2] = TextDrawCreate(191.000000, 142.000000, "ld_beat:up");
	alcodraw[3] = TextDrawCreate(92.000000, 191.000000, "ld_beat:up");
	alcodraw[4] = TextDrawCreate(141.000000, 191.000000, "ld_beat:up");
	for(new A; A < 5; A++)
	{
		TextDrawBackgroundColor(alcodraw[A], 0);
		TextDrawFont(alcodraw[A], 5);
		TextDrawLetterSize(alcodraw[A], 0.500000, 1.000000);
		TextDrawColor(alcodraw[A], 32);
		TextDrawSetOutline(alcodraw[A], 0);
		TextDrawSetProportional(alcodraw[A], 1);
		TextDrawSetShadow(alcodraw[A], 1);
		TextDrawTextSize(alcodraw[A], 46.000000, 46.000000);
		TextDrawSetPreviewModel(alcodraw[A], 19377);
		TextDrawSetPreviewRot(alcodraw[A], 0.000000, 0.000000, 90.000000, 0.000000);
		TextDrawSetSelectable(alcodraw[A], 1);
	}
	alcodraw1[0] = TextDrawCreate(90.000000, 150.000000, "ld_beat:up");
	TextDrawBackgroundColor(alcodraw1[0], 0);
	TextDrawFont(alcodraw1[0], 5);
	TextDrawLetterSize(alcodraw1[0], 0.500000, 1.000000);
	TextDrawColor(alcodraw1[0], -1);
	TextDrawSetOutline(alcodraw1[0], 0);
	TextDrawSetProportional(alcodraw1[0], 1);
	TextDrawSetShadow(alcodraw1[0], 1);
	TextDrawTextSize(alcodraw1[0], 40.000000, 33.000000);
	TextDrawSetPreviewModel(alcodraw1[0], 1546);
	TextDrawSetPreviewRot(alcodraw1[0], 0.000000, 0.000000, 120.000000, 1.000000);
	TextDrawSetSelectable(alcodraw1[0], 0);
	alcodraw1[1] = TextDrawCreate(133.000000, 143.000000, "ld_beat:up");
	TextDrawBackgroundColor(alcodraw1[1], 0);
	TextDrawFont(alcodraw1[1], 5);
	TextDrawLetterSize(alcodraw1[1], 0.500000, 1.000000);
	TextDrawColor(alcodraw1[1], -1);
	TextDrawSetOutline(alcodraw1[1], 0);
	TextDrawSetProportional(alcodraw1[1], 1);
	TextDrawSetShadow(alcodraw1[1], 1);
	TextDrawTextSize(alcodraw1[1], 55.000000, 41.000000);
	TextDrawSetPreviewModel(alcodraw1[1], 1520);
	TextDrawSetPreviewRot(alcodraw1[1], 0.000000, 0.000000, 120.000000, 1.000000);
	TextDrawSetSelectable(alcodraw1[1], 0);
	alcodraw1[2] = TextDrawCreate(184.000000, 144.000000, "ld_beat:up");
	TextDrawBackgroundColor(alcodraw1[2], 0);
	TextDrawFont(alcodraw1[2], 5);
	TextDrawLetterSize(alcodraw1[2], 0.500000, 1.000000);
	TextDrawColor(alcodraw1[2], -1);
	TextDrawSetOutline(alcodraw1[2], 0);
	TextDrawSetProportional(alcodraw1[2], 1);
	TextDrawSetShadow(alcodraw1[2], 1);
	TextDrawTextSize(alcodraw1[2], 55.000000, 41.000000);
	TextDrawSetPreviewModel(alcodraw1[2], 1512);
	TextDrawSetPreviewRot(alcodraw1[2], 0.000000, 0.000000, 120.000000, 1.000000);
	TextDrawSetSelectable(alcodraw1[2], 0);
	alcodraw1[3] = TextDrawCreate(94.000000, 194.000000, "ld_beat:up");
	TextDrawBackgroundColor(alcodraw1[3], 0);
	TextDrawFont(alcodraw1[3], 5);
	TextDrawLetterSize(alcodraw1[3], 0.500000, 1.000000);
	TextDrawColor(alcodraw1[3], -1);
	TextDrawSetOutline(alcodraw1[3], 0);
	TextDrawSetProportional(alcodraw1[3], 1);
	TextDrawSetShadow(alcodraw1[3], 1);
	TextDrawTextSize(alcodraw1[3], 41.000000, 42.000000);
	TextDrawSetPreviewModel(alcodraw1[3], 2814);
	TextDrawSetPreviewRot(alcodraw1[3], -30.000000, 0.000000, 0.000000, 1.000000);
	TextDrawSetSelectable(alcodraw1[3], 0);
	alcodraw1[4] = TextDrawCreate(141.000000, 185.000000, "ld_beat:up");
	TextDrawBackgroundColor(alcodraw1[4], 0);
	TextDrawFont(alcodraw1[4], 5);
	TextDrawLetterSize(alcodraw1[4], 0.500000, 1.000000);
	TextDrawColor(alcodraw1[4], -1);
	TextDrawSetOutline(alcodraw1[4], 0);
	TextDrawSetProportional(alcodraw1[4], 1);
	TextDrawSetShadow(alcodraw1[4], 1);
	TextDrawTextSize(alcodraw1[4], 44.000000, 57.000000);
	TextDrawSetPreviewModel(alcodraw1[4], 2768);
	TextDrawSetPreviewRot(alcodraw1[4], -30.000000, 0.000000, 120.000000, 1.000000);
	TextDrawSetSelectable(alcodraw1[4], 0);
	alcodraw2[0] = TextDrawCreate(121.000000, 178.000000, "_");
	alcodraw2[1] = TextDrawCreate(170.000000, 178.000000, "_");
	alcodraw2[2] = TextDrawCreate(221.000000, 178.000000, "_");
	alcodraw2[3] = TextDrawCreate(122.000000, 227.000000, "_");
	alcodraw2[4] = TextDrawCreate(170.000000, 227.000000, "_");
	for(new A; A < 5; A++)
	{
		TextDrawBackgroundColor(alcodraw2[A], 255);
		TextDrawFont(alcodraw2[A], 2);
		TextDrawLetterSize(alcodraw2[A], 0.320000, 0.899999);
		TextDrawColor(alcodraw2[A], -1);
		TextDrawSetOutline(alcodraw2[A], 0);
		TextDrawSetProportional(alcodraw2[A], 1);
		TextDrawSetShadow(alcodraw2[A], 1);
		TextDrawSetSelectable(alcodraw2[A], 0);
	}
	//////////////////////////////////========++++++++
	GrandKapt[0] = TextDrawCreate(320.000000, 382.000000, "00:00");
	TextDrawAlignment(GrandKapt[0], 2);
	TextDrawBackgroundColor(GrandKapt[0], 255);
	TextDrawFont(GrandKapt[0], 1);
	TextDrawLetterSize(GrandKapt[0], 0.470000, 1.500000);
	TextDrawColor(GrandKapt[0], -1);
	TextDrawSetOutline(GrandKapt[0], 0);
	TextDrawSetProportional(GrandKapt[0], 1);
	TextDrawSetShadow(GrandKapt[0], 0);
	TextDrawSetSelectable(GrandKapt[0], 0);



	GrandKapt[3] = TextDrawCreate(319.000000, 378.000000, "_");
	TextDrawAlignment(GrandKapt[3], 2);
	TextDrawBackgroundColor(GrandKapt[3], 255);
	TextDrawFont(GrandKapt[3], 1);
	TextDrawLetterSize(GrandKapt[3], 0.500000, 6.699999);
	TextDrawColor(GrandKapt[3], -1);
	TextDrawSetOutline(GrandKapt[3], 0);
	TextDrawSetProportional(GrandKapt[3], 1);
	TextDrawSetShadow(GrandKapt[3], 1);
	TextDrawUseBox(GrandKapt[3], 1);
	TextDrawBoxColor(GrandKapt[3], 639969023);
	TextDrawTextSize(GrandKapt[3], 0.000000, 131.000000);
	TextDrawSetSelectable(GrandKapt[3], 0);

	GrandKapt[4] = TextDrawCreate(319.000000, 384.000000, "_");
	TextDrawAlignment(GrandKapt[4], 2);
	TextDrawBackgroundColor(GrandKapt[3], 255);
	TextDrawFont(GrandKapt[4], 1);
	TextDrawLetterSize(GrandKapt[4], 0.500000, 5.400000);
	TextDrawColor(GrandKapt[4], -1);
	TextDrawSetOutline(GrandKapt[4], 0);
	TextDrawSetProportional(GrandKapt[4], 1);
	TextDrawSetShadow(GrandKapt[4], 1);
	TextDrawUseBox(GrandKapt[4], 1);
	TextDrawBoxColor(GrandKapt[4], 1077952767);
	TextDrawTextSize(GrandKapt[4], 0.000000, 121.000000);
	TextDrawSetSelectable(GrandKapt[4], 0);

	GrandKapt[5] = TextDrawCreate(319.000000, 378.000000, "_");
	TextDrawAlignment(GrandKapt[5], 2);
	TextDrawBackgroundColor(GrandKapt[5], 255);
	TextDrawFont(GrandKapt[5], 1);
	TextDrawLetterSize(GrandKapt[5], 0.500000, 2.000000);
	TextDrawColor(GrandKapt[5], -1);
	TextDrawSetOutline(GrandKapt[5], 0);
	TextDrawSetProportional(GrandKapt[5], 1);
	TextDrawSetShadow(GrandKapt[5], 1);
	TextDrawUseBox(GrandKapt[5], 1);
	TextDrawBoxColor(GrandKapt[5], 639969023);
	TextDrawTextSize(GrandKapt[5], 0.000000, 54.000000);
	TextDrawSetSelectable(GrandKapt[5], 0);

	GrandKapt[6] = TextDrawCreate(319.000000, 402.000000, "GroveStreet");
	TextDrawAlignment(GrandKapt[6], 2);
	TextDrawBackgroundColor(GrandKapt[6], 255);
	TextDrawFont(GrandKapt[6], 1);
	TextDrawLetterSize(GrandKapt[6], 0.190000, 0.700000);
	TextDrawColor(GrandKapt[6], -1);
	TextDrawSetOutline(GrandKapt[6], 0);
	TextDrawSetProportional(GrandKapt[6], 1);
	TextDrawSetShadow(GrandKapt[6], 0);
	TextDrawUseBox(GrandKapt[6], 1);
	TextDrawBoxColor(GrandKapt[6], 639969023);
	TextDrawTextSize(GrandKapt[6], 0.000000, 54.000000);
	TextDrawSetSelectable(GrandKapt[6], 0);

	GrandKapt[7] = TextDrawCreate(319.000000, 414.000000, "GroveStreet");
	TextDrawAlignment(GrandKapt[7], 2);
	TextDrawBackgroundColor(GrandKapt[7], 255);
	TextDrawFont(GrandKapt[7], 1);
	TextDrawLetterSize(GrandKapt[7], 0.190000, 0.700000);
	TextDrawColor(GrandKapt[7], -1);
	TextDrawSetOutline(GrandKapt[7], 0);
	TextDrawSetProportional(GrandKapt[7], 1);
	TextDrawSetShadow(GrandKapt[7], 0);
	TextDrawUseBox(GrandKapt[7], 1);
	TextDrawBoxColor(GrandKapt[7], 639969023);
	TextDrawTextSize(GrandKapt[7], 0.000000, 54.000000);
	TextDrawSetSelectable(GrandKapt[7], 0);

	GrandKapt[1] = TextDrawCreate(364.000000, 402.000000, "00");
	TextDrawAlignment(GrandKapt[1], 2);
	TextDrawBackgroundColor(GrandKapt[1], 255);
	TextDrawFont(GrandKapt[1], 1);
	TextDrawLetterSize(GrandKapt[1], 0.460000, 2.000000);
	TextDrawColor(GrandKapt[1], -1);
	TextDrawSetOutline(GrandKapt[1], 0);
	TextDrawSetProportional(GrandKapt[1], 1);
	TextDrawSetShadow(GrandKapt[1], 0);
	TextDrawUseBox(GrandKapt[1], 1);
	TextDrawBoxColor(GrandKapt[1], 0x5E8832FF);
	TextDrawTextSize(GrandKapt[1], 0.000000, 23.000000);
	TextDrawSetSelectable(GrandKapt[1], 0);

	GrandKapt[2] = TextDrawCreate(274.000000, 402.000000, "02");
	TextDrawAlignment(GrandKapt[2], 2);
	TextDrawBackgroundColor(GrandKapt[2], 255);
	TextDrawFont(GrandKapt[2], 1);
	TextDrawLetterSize(GrandKapt[2], 0.460000, 2.000000);
	TextDrawColor(GrandKapt[2], -1);
	TextDrawSetOutline(GrandKapt[2], 0);
	TextDrawSetProportional(GrandKapt[2], 1);
	TextDrawSetShadow(GrandKapt[2], 0);
	TextDrawUseBox(GrandKapt[2], 1);
	TextDrawBoxColor(GrandKapt[2], 0x5E8832FF);
	TextDrawTextSize(GrandKapt[2], 0.000000, 23.000000);
	TextDrawSetSelectable(GrandKapt[2], 0);

	GrandKapt[8] = TextDrawCreate(364.000000, 390.000000, "score");
	TextDrawAlignment(GrandKapt[8], 2);
	TextDrawBackgroundColor(GrandKapt[8], 255);
	TextDrawFont(GrandKapt[8], 1);
	TextDrawLetterSize(GrandKapt[8], 0.170000, 0.900000);
	TextDrawColor(GrandKapt[8], -1);
	TextDrawSetOutline(GrandKapt[8], 0);
	TextDrawSetProportional(GrandKapt[8], 1);
	TextDrawSetShadow(GrandKapt[8], 0);
	TextDrawUseBox(GrandKapt[8], 1);
	TextDrawBoxColor(GrandKapt[8], 1342177280);
	TextDrawTextSize(GrandKapt[8], 0.000000, 23.000000);
	TextDrawSetSelectable(GrandKapt[8], 0);

	GrandKapt[9] = TextDrawCreate(274.000000, 390.000000, "score");
	TextDrawAlignment(GrandKapt[9], 2);
	TextDrawBackgroundColor(GrandKapt[9], 255);
	TextDrawFont(GrandKapt[9], 1);
	TextDrawLetterSize(GrandKapt[9], 0.170000, 0.900000);
	TextDrawColor(GrandKapt[9], -1);
	TextDrawSetOutline(GrandKapt[9], 0);
	TextDrawSetProportional(GrandKapt[9], 1);
	TextDrawSetShadow(GrandKapt[9], 0);
	TextDrawUseBox(GrandKapt[9], 1);
	TextDrawBoxColor(GrandKapt[9], 1342177280);
	TextDrawTextSize(GrandKapt[9], 0.000000, 23.000000);
	TextDrawSetSelectable(GrandKapt[9], 0);

	//////////////////////////////////========++++++++
	// iaoee
	Grand2Kapt[0] = TextDrawCreate(320.000000, 382.000000, "00:00");
	TextDrawAlignment(Grand2Kapt[0], 2);
	TextDrawBackgroundColor(Grand2Kapt[0], 255);
	TextDrawFont(Grand2Kapt[0], 1);
	TextDrawLetterSize(Grand2Kapt[0], 0.470000, 1.500000);
	TextDrawColor(Grand2Kapt[0], -1);
	TextDrawSetOutline(Grand2Kapt[0], 0);
	TextDrawSetProportional(Grand2Kapt[0], 1);
	TextDrawSetShadow(Grand2Kapt[0], 0);
	TextDrawSetSelectable(Grand2Kapt[0], 0);



	Grand2Kapt[3] = TextDrawCreate(319.000000, 378.000000, "_");
	TextDrawAlignment(Grand2Kapt[3], 2);
	TextDrawBackgroundColor(Grand2Kapt[3], 255);
	TextDrawFont(Grand2Kapt[3], 1);
	TextDrawLetterSize(Grand2Kapt[3], 0.500000, 6.699999);
	TextDrawColor(Grand2Kapt[3], -1);
	TextDrawSetOutline(Grand2Kapt[3], 0);
	TextDrawSetProportional(Grand2Kapt[3], 1);
	TextDrawSetShadow(Grand2Kapt[3], 1);
	TextDrawUseBox(Grand2Kapt[3], 1);
	TextDrawBoxColor(Grand2Kapt[3], 639969023);
	TextDrawTextSize(Grand2Kapt[3], 0.000000, 131.000000);
	TextDrawSetSelectable(Grand2Kapt[3], 0);

	Grand2Kapt[4] = TextDrawCreate(319.000000, 384.000000, "_");
	TextDrawAlignment(Grand2Kapt[4], 2);
	TextDrawBackgroundColor(Grand2Kapt[3], 255);
	TextDrawFont(Grand2Kapt[4], 1);
	TextDrawLetterSize(Grand2Kapt[4], 0.500000, 5.400000);
	TextDrawColor(Grand2Kapt[4], -1);
	TextDrawSetOutline(Grand2Kapt[4], 0);
	TextDrawSetProportional(Grand2Kapt[4], 1);
	TextDrawSetShadow(Grand2Kapt[4], 1);
	TextDrawUseBox(Grand2Kapt[4], 1);
	TextDrawBoxColor(Grand2Kapt[4], 1077952767);
	TextDrawTextSize(Grand2Kapt[4], 0.000000, 121.000000);
	TextDrawSetSelectable(Grand2Kapt[4], 0);

	Grand2Kapt[5] = TextDrawCreate(319.000000, 378.000000, "_");
	TextDrawAlignment(Grand2Kapt[5], 2);
	TextDrawBackgroundColor(Grand2Kapt[5], 255);
	TextDrawFont(Grand2Kapt[5], 1);
	TextDrawLetterSize(Grand2Kapt[5], 0.500000, 2.000000);
	TextDrawColor(Grand2Kapt[5], -1);
	TextDrawSetOutline(Grand2Kapt[5], 0);
	TextDrawSetProportional(Grand2Kapt[5], 1);
	TextDrawSetShadow(Grand2Kapt[5], 1);
	TextDrawUseBox(Grand2Kapt[5], 1);
	TextDrawBoxColor(Grand2Kapt[5], 639969023);
	TextDrawTextSize(Grand2Kapt[5], 0.000000, 54.000000);
	TextDrawSetSelectable(Grand2Kapt[5], 0);

	Grand2Kapt[6] = TextDrawCreate(319.000000, 402.000000, "GroveStreet");
	TextDrawAlignment(Grand2Kapt[6], 2);
	TextDrawBackgroundColor(Grand2Kapt[6], 255);
	TextDrawFont(Grand2Kapt[6], 1);
	TextDrawLetterSize(Grand2Kapt[6], 0.190000, 0.700000);
	TextDrawColor(Grand2Kapt[6], -1);
	TextDrawSetOutline(Grand2Kapt[6], 0);
	TextDrawSetProportional(Grand2Kapt[6], 1);
	TextDrawSetShadow(Grand2Kapt[6], 0);
	TextDrawUseBox(Grand2Kapt[6], 1);
	TextDrawBoxColor(Grand2Kapt[6], 639969023);
	TextDrawTextSize(Grand2Kapt[6], 0.000000, 54.000000);
	TextDrawSetSelectable(Grand2Kapt[6], 0);

	Grand2Kapt[7] = TextDrawCreate(319.000000, 414.000000, "GroveStreet");
	TextDrawAlignment(Grand2Kapt[7], 2);
	TextDrawBackgroundColor(Grand2Kapt[7], 255);
	TextDrawFont(Grand2Kapt[7], 1);
	TextDrawLetterSize(Grand2Kapt[7], 0.190000, 0.700000);
	TextDrawColor(Grand2Kapt[7], -1);
	TextDrawSetOutline(Grand2Kapt[7], 0);
	TextDrawSetProportional(Grand2Kapt[7], 1);
	TextDrawSetShadow(Grand2Kapt[7], 0);
	TextDrawUseBox(Grand2Kapt[7], 1);
	TextDrawBoxColor(Grand2Kapt[7], 639969023);
	TextDrawTextSize(Grand2Kapt[7], 0.000000, 54.000000);
	TextDrawSetSelectable(Grand2Kapt[7], 0);

	Grand2Kapt[1] = TextDrawCreate(364.000000, 402.000000, "00");
	TextDrawAlignment(Grand2Kapt[1], 2);
	TextDrawBackgroundColor(Grand2Kapt[1], 255);
	TextDrawFont(Grand2Kapt[1], 1);
	TextDrawLetterSize(Grand2Kapt[1], 0.460000, 2.000000);
	TextDrawColor(Grand2Kapt[1], -1);
	TextDrawSetOutline(Grand2Kapt[1], 0);
	TextDrawSetProportional(Grand2Kapt[1], 1);
	TextDrawSetShadow(Grand2Kapt[1], 0);
	TextDrawUseBox(Grand2Kapt[1], 1);
	TextDrawBoxColor(Grand2Kapt[1], 0x5E8832FF);
	TextDrawTextSize(Grand2Kapt[1], 0.000000, 23.000000);
	TextDrawSetSelectable(Grand2Kapt[1], 0);

	Grand2Kapt[2] = TextDrawCreate(274.000000, 402.000000, "02");
	TextDrawAlignment(Grand2Kapt[2], 2);
	TextDrawBackgroundColor(Grand2Kapt[2], 255);
	TextDrawFont(Grand2Kapt[2], 1);
	TextDrawLetterSize(Grand2Kapt[2], 0.460000, 2.000000);
	TextDrawColor(Grand2Kapt[2], -1);
	TextDrawSetOutline(Grand2Kapt[2], 0);
	TextDrawSetProportional(Grand2Kapt[2], 1);
	TextDrawSetShadow(Grand2Kapt[2], 0);
	TextDrawUseBox(Grand2Kapt[2], 1);
	TextDrawBoxColor(Grand2Kapt[2], 0x5E8832FF);
	TextDrawTextSize(Grand2Kapt[2], 0.000000, 23.000000);
	TextDrawSetSelectable(Grand2Kapt[2], 0);

	Grand2Kapt[8] = TextDrawCreate(364.000000, 390.000000, "score");
	TextDrawAlignment(Grand2Kapt[8], 2);
	TextDrawBackgroundColor(Grand2Kapt[8], 255);
	TextDrawFont(Grand2Kapt[8], 1);
	TextDrawLetterSize(Grand2Kapt[8], 0.170000, 0.900000);
	TextDrawColor(Grand2Kapt[8], -1);
	TextDrawSetOutline(Grand2Kapt[8], 0);
	TextDrawSetProportional(Grand2Kapt[8], 1);
	TextDrawSetShadow(Grand2Kapt[8], 0);
	TextDrawUseBox(Grand2Kapt[8], 1);
	TextDrawBoxColor(Grand2Kapt[8], 1342177280);
	TextDrawTextSize(Grand2Kapt[8], 0.000000, 23.000000);
	TextDrawSetSelectable(Grand2Kapt[8], 0);

	Grand2Kapt[9] = TextDrawCreate(274.000000, 390.000000, "score");
	TextDrawAlignment(Grand2Kapt[9], 2);
	TextDrawBackgroundColor(Grand2Kapt[9], 255);
	TextDrawFont(Grand2Kapt[9], 1);
	TextDrawLetterSize(Grand2Kapt[9], 0.170000, 0.900000);
	TextDrawColor(Grand2Kapt[9], -1);
	TextDrawSetOutline(Grand2Kapt[9], 0);
	TextDrawSetProportional(Grand2Kapt[9], 1);
	TextDrawSetShadow(Grand2Kapt[9], 0);
	TextDrawUseBox(Grand2Kapt[9], 1);
	TextDrawBoxColor(Grand2Kapt[9], 1342177280);
	TextDrawTextSize(Grand2Kapt[9], 0.000000, 23.000000);
	TextDrawSetSelectable(Grand2Kapt[9], 0);
	//
	PTarget[0] = TextDrawCreate(402.000000, 8.000000, "BoxTarget1");
	TextDrawBackgroundColor(PTarget[0], 255);
	TextDrawFont(PTarget[0], 1);
	TextDrawLetterSize(PTarget[0], 0.000000, 5.099997);
	TextDrawUseBox(PTarget[0], 1);
	TextDrawBoxColor(PTarget[0], 48);
	TextDrawTextSize(PTarget[0], 243.000000, 1.000000);
	TextDrawSetSelectable(PTarget[0], 0);
	PTarget[1] = TextDrawCreate(400.000000, 10.000000, "BoxTarget2");
	TextDrawBackgroundColor(PTarget[1], 255);
	TextDrawFont(PTarget[1], 1);
	TextDrawLetterSize(PTarget[1], 0.000000, 4.599998);
	TextDrawUseBox(PTarget[1], 1);
	TextDrawBoxColor( PTarget[1], 80);
	TextDrawTextSize(PTarget[1], 245.000000, 1.000000);
	TextDrawSetSelectable(PTarget[1], 0);
	PTarget[2] = TextDrawCreate(400.000000, 35.000000, "BoxHP");
	TextDrawBackgroundColor(PTarget[2], 255);
	TextDrawFont(PTarget[2], 1);
	TextDrawLetterSize(PTarget[2], 0.000000, 0.400000);
	TextDrawUseBox(PTarget[2], 1);
	TextDrawBoxColor(PTarget[2], -1408430593);
	TextDrawTextSize(PTarget[2], 245.000000, 1.000000);
	TextDrawSetSelectable(PTarget[2], 0);
	PTarget[3] = TextDrawCreate(400.000000, 45.000000, "BoxARMOUR");
	TextDrawBackgroundColor(PTarget[3], 255);
	TextDrawFont(PTarget[3], 1);
	TextDrawLetterSize(PTarget[3], 0.000000, 0.400000);
	TextDrawUseBox(PTarget[3], 1);
	TextDrawBoxColor(PTarget[3], 794073599);
	TextDrawTextSize(PTarget[3], 245.000000, 1.000000);
	TextDrawSetSelectable(PTarget[3], 0);

	kryg = TextDrawCreate(123.000000, 397.000000, "ld_beat:up");
	TextDrawBackgroundColor(kryg, 0);
	TextDrawFont(kryg, 5);
	TextDrawLetterSize(kryg, 0.500000, 10.000000);
	TextDrawColor(kryg, -208);
	TextDrawSetOutline(kryg, 0);
	TextDrawSetProportional(kryg, 1);
	TextDrawSetShadow(kryg, 1);
	TextDrawTextSize(kryg, 41.000000, 56.000000);
	TextDrawSetPreviewModel(kryg, 1953);
	TextDrawSetPreviewRot(kryg, 90.000000, 0.000000, 0.000000, 1.000000);
	TextDrawSetSelectable(kryg, 0);

	/////////////////////////oaeaoii
	Sphone[0] = TextDrawCreate( 39.000000, 162.000000, "_");
	TextDrawBackgroundColor( Sphone[0], 255);
	TextDrawFont( Sphone[0], 1);
	TextDrawLetterSize( Sphone[0], 0.549999, 18.499998);
	TextDrawColor( Sphone[0], -1);
	TextDrawSetOutline( Sphone[0], 0);
	TextDrawSetProportional( Sphone[0], 1);
	TextDrawSetShadow( Sphone[0], 1);
	TextDrawUseBox( Sphone[0], 1);
	TextDrawBoxColor( Sphone[0], 2088335871);
	TextDrawTextSize( Sphone[0], 135.000000, 0.000000);
	TextDrawSetSelectable( Sphone[0], 0);

	Sphone[1] = TextDrawCreate( 41.000000, 177.000000, "_");
	TextDrawBackgroundColor( Sphone[1], 255);
	TextDrawFont( Sphone[1], 1);
	TextDrawLetterSize( Sphone[1], 0.500000, 14.200000);
	TextDrawColor( Sphone[1], -1);
	TextDrawSetOutline( Sphone[1], 0);
	TextDrawSetProportional( Sphone[1], 1);
	TextDrawSetShadow( Sphone[1], 1);
	TextDrawUseBox( Sphone[1], 1);
	TextDrawBoxColor( Sphone[1], -1);
	TextDrawTextSize( Sphone[1], 133.000000, 3.000000);
	TextDrawSetSelectable( Sphone[1], 0);

	Sphone[2] = TextDrawCreate( 40.000000, 166.000000, "_");
	TextDrawBackgroundColor( Sphone[2], 255);
	TextDrawFont( Sphone[2], 1);
	TextDrawLetterSize( Sphone[2], 0.500000, 0.599999);
	TextDrawColor( Sphone[2], -1);
	TextDrawSetOutline( Sphone[2], 0);
	TextDrawSetProportional( Sphone[2], 1);
	TextDrawSetShadow( Sphone[2], 1);
	TextDrawUseBox( Sphone[2], 1);
	TextDrawBoxColor( Sphone[2], 1482053375);
	TextDrawTextSize( Sphone[2], 134.000000, 0.000000);
	TextDrawSetSelectable( Sphone[2], 0);

	Sphone[3] = TextDrawCreate( 72.000000, 313.000000, "_");
	TextDrawBackgroundColor( Sphone[3], 255);
	TextDrawFont( Sphone[3], 1);
	TextDrawLetterSize( Sphone[3], 0.500000, 1.400000);
	TextDrawColor( Sphone[3], -1);
	TextDrawSetOutline( Sphone[3], 0);
	TextDrawSetProportional( Sphone[3], 1);
	TextDrawSetShadow( Sphone[3], 1);
	TextDrawUseBox( Sphone[3], 1);
	TextDrawBoxColor( Sphone[3], 1482053375);
	TextDrawTextSize( Sphone[3], 102.000000, 1.000000);
	TextDrawSetSelectable( Sphone[3], 0);

	Sphone[4] = TextDrawCreate( 40.000000, 164.000000, "26/01/2015      Atizona state");
	TextDrawBackgroundColor( Sphone[4], 255);
	TextDrawFont( Sphone[4], 2);
	TextDrawLetterSize( Sphone[4], 0.130000, 0.899999);
	TextDrawColor( Sphone[4], -1);
	TextDrawSetOutline( Sphone[4], 0);
	TextDrawSetProportional( Sphone[4], 1);
	TextDrawSetShadow( Sphone[4], 0);
	TextDrawSetSelectable( Sphone[4], 0);

	Sphone[5] = TextDrawCreate( 95.000000, 167.000000, "22.30");
	TextDrawBackgroundColor( Sphone[5], 255);
	TextDrawFont( Sphone[5], 2);
	TextDrawLetterSize( Sphone[5], 0.370000, 3.500000);
	TextDrawColor( Sphone[5], 128);
	TextDrawSetOutline( Sphone[5], 0);
	TextDrawSetProportional( Sphone[5], 1);
	TextDrawSetShadow( Sphone[5], 0);
	TextDrawSetSelectable( Sphone[5], 0);

	Sphone[6] = TextDrawCreate( 72.000000, 312.000000, "ld_beat:up"); /////???? ????????
	TextDrawBackgroundColor( Sphone[6], 0);
	TextDrawFont( Sphone[6], 5);
	TextDrawLetterSize( Sphone[6], 0.500000, 1.000000);
	TextDrawColor( Sphone[6], 437721087);
	TextDrawSetOutline( Sphone[6], 0);
	TextDrawSetProportional( Sphone[6], 1);
	TextDrawSetShadow( Sphone[6], 1);
	TextDrawTextSize( Sphone[6], 30.000000, 14.000000);
	TextDrawSetPreviewModel( Sphone[6], 19377);
	TextDrawSetPreviewRot( Sphone[6], 0.000000, 0.000000, 90.000000, 0.000000);
	TextDrawSetSelectable( Sphone[6], 1);

	Sphone[7] = TextDrawCreate( 78.000000, 314.000000, "menu");
	TextDrawBackgroundColor( Sphone[7], 255);
	TextDrawFont( Sphone[7], 2);
	TextDrawLetterSize( Sphone[7], 0.130000, 1.000000);
	TextDrawColor( Sphone[7], -1);
	TextDrawSetOutline( Sphone[7], 0);
	TextDrawSetProportional( Sphone[7], 1);
	TextDrawSetShadow( Sphone[7], 0);
	TextDrawSetSelectable( Sphone[7], 0);

	Sphone[8] = TextDrawCreate( 41.000000, 291.000000, "ld_beat:up"); //??????
	TextDrawBackgroundColor( Sphone[8], 0);
	TextDrawFont( Sphone[8], 5);
	TextDrawLetterSize( Sphone[8], 0.500000, -0.000000);
	TextDrawColor( Sphone[8], 32);
	TextDrawSetOutline( Sphone[8], 0);
	TextDrawSetProportional( Sphone[8], 1);
	TextDrawSetShadow( Sphone[8], 1);
	TextDrawTextSize( Sphone[8], 92.000000, 15.000000);
	TextDrawSetPreviewModel( Sphone[8], 19377);
	TextDrawSetPreviewRot( Sphone[8], 0.000000, 0.000000, 90.000000, 0.000000);
	TextDrawSetSelectable( Sphone[8], 1);


	SphoneKey[0] = TextDrawCreate( 41.000000, 197.000000, "ld_beat:up"); //????????
	TextDrawBackgroundColor( SphoneKey[0], 0);
	TextDrawFont( SphoneKey[0], 5);
	TextDrawLetterSize( SphoneKey[0], 0.500000, 1.000000);
	TextDrawColor( SphoneKey[0], 32);
	TextDrawSetOutline( SphoneKey[0], 0);
	TextDrawSetProportional( SphoneKey[0], 1);
	TextDrawSetShadow( SphoneKey[0], 1);
	TextDrawTextSize( SphoneKey[0], 92.000000, 20.000000);
	TextDrawSetPreviewModel( SphoneKey[0], 19377);
	TextDrawSetPreviewRot( SphoneKey[0], 0.000000, 0.000000, 90.000000, 0.000000);
	TextDrawSetSelectable( SphoneKey[0], 1);

	SphoneKey[1] = TextDrawCreate( 56.000000, 200.000000, "Contacts");
	TextDrawBackgroundColor( SphoneKey[1], 255);
	TextDrawFont( SphoneKey[1], 2);
	TextDrawLetterSize( SphoneKey[1], 0.270000, 1.300000);
	TextDrawColor( SphoneKey[1], 255);
	TextDrawSetOutline( SphoneKey[1], 0);
	TextDrawSetProportional( SphoneKey[1], 1);
	TextDrawSetShadow( SphoneKey[1], 0);
	TextDrawSetSelectable( SphoneKey[1], 0);

	SphoneKey[2] = TextDrawCreate( 41.000000, 221.000000, "ld_beat:up");//mesages
	TextDrawBackgroundColor( SphoneKey[2], 0);
	TextDrawFont( SphoneKey[2], 5);
	TextDrawLetterSize( SphoneKey[2], 0.500000, 1.000000);
	TextDrawColor( SphoneKey[2], 32);
	TextDrawSetOutline( SphoneKey[2], 0);
	TextDrawSetProportional( SphoneKey[2], 1);
	TextDrawSetShadow( SphoneKey[2], 1);
	TextDrawTextSize( SphoneKey[2], 92.000000, 20.000000);
	TextDrawSetPreviewModel( SphoneKey[2], 19377);
	TextDrawSetPreviewRot( SphoneKey[2], 0.000000, 0.000000, 90.000000, 0.000000);
	TextDrawSetSelectable( SphoneKey[2], 1);

	SphoneKey[3] = TextDrawCreate( 54.000000, 224.000000, "Messages");
	TextDrawBackgroundColor( SphoneKey[3], 255);
	TextDrawFont( SphoneKey[3], 2);
	TextDrawLetterSize( SphoneKey[3], 0.270000, 1.300000);
	TextDrawColor( SphoneKey[3], 255);
	TextDrawSetOutline( SphoneKey[3], 0);
	TextDrawSetProportional( SphoneKey[3], 1);
	TextDrawSetShadow( SphoneKey[3], 0);
	TextDrawSetSelectable( SphoneKey[3], 0);

	SphoneKey[4] = TextDrawCreate( 41.000000, 269.000000, "ld_beat:up"); // ????????? ????????
	TextDrawBackgroundColor( SphoneKey[4], 0);
	TextDrawFont( SphoneKey[4], 5);
	TextDrawLetterSize( SphoneKey[4], 0.500000, 1.000000);
	TextDrawColor( SphoneKey[4], 32);
	TextDrawSetOutline( SphoneKey[4], 0);
	TextDrawSetProportional( SphoneKey[4], 1);
	TextDrawSetShadow( SphoneKey[4], 1);
	TextDrawTextSize( SphoneKey[4], 92.000000, 20.000000);
	TextDrawSetPreviewModel( SphoneKey[4], 19377);
	TextDrawSetPreviewRot( SphoneKey[4], 0.000000, 0.000000, 90.000000, 0.000000);
	TextDrawSetSelectable( SphoneKey[4], 1);

	SphoneKey[5] = TextDrawCreate( 54.000000, 271.000000, "Off/On phone");
	TextDrawBackgroundColor( SphoneKey[5], 255);
	TextDrawFont( SphoneKey[5], 2);
	TextDrawLetterSize( SphoneKey[5], 0.270000, 1.300000);
	TextDrawColor( SphoneKey[5], 255);
	TextDrawSetOutline( SphoneKey[5], 0);
	TextDrawSetProportional( SphoneKey[5], 1);
	TextDrawSetShadow( SphoneKey[5], 0);
	TextDrawSetSelectable( SphoneKey[5], 0);

	SphoneKey[6] = TextDrawCreate( 41.000000, 245.000000, "ld_beat:up"); //////?????????
	TextDrawBackgroundColor( SphoneKey[6], 0);
	TextDrawFont( SphoneKey[6], 5);
	TextDrawLetterSize( SphoneKey[6], 0.500000, 1.000000);
	TextDrawColor( SphoneKey[6], 32);
	TextDrawSetOutline( SphoneKey[6], 0);
	TextDrawSetProportional( SphoneKey[6], 1);
	TextDrawSetShadow( SphoneKey[6], 1);
	TextDrawTextSize( SphoneKey[6], 92.000000, 20.000000);
	TextDrawSetPreviewModel( SphoneKey[6], 19377);
	TextDrawSetPreviewRot( SphoneKey[6], 0.000000, 0.000000, 90.000000, 0.000000);
	TextDrawSetSelectable( SphoneKey[6], 1);

	SphoneKey[7] = TextDrawCreate( 54.000000, 247.000000, "Call");
	TextDrawBackgroundColor( SphoneKey[7], 255);
	TextDrawFont( SphoneKey[7], 2);
	TextDrawLetterSize( SphoneKey[7], 0.270000, 1.300000);
	TextDrawColor( SphoneKey[7], 255);
	TextDrawSetOutline( SphoneKey[7], 0);
	TextDrawSetProportional( SphoneKey[7], 1);
	TextDrawSetShadow( SphoneKey[7], 0);
	TextDrawSetSelectable( SphoneKey[7], 0);

	Calling[0] = TextDrawCreate( 41.000000, 245.000000, "ld_beat:up"); ///????????? ?????
	TextDrawBackgroundColor( Calling[0], 0);
	TextDrawFont( Calling[0], 5);
	TextDrawLetterSize( Calling[0], 0.500000, 1.000000);
	TextDrawColor( Calling[0], 32);
	TextDrawSetOutline( Calling[0], 0);
	TextDrawSetProportional( Calling[0], 1);
	TextDrawSetShadow( Calling[0], 1);
	TextDrawTextSize( Calling[0], 92.000000, 20.000000);
	TextDrawSetPreviewModel( Calling[0], 19377);
	TextDrawSetPreviewRot( Calling[0], 0.000000, 0.000000, 90.000000, 0.000000);
	TextDrawSetSelectable( Calling[0], 1);

	Calling[1] = TextDrawCreate( 41.000000, 269.000000, "ld_beat:up"); // ??????? ??????
	TextDrawBackgroundColor( Calling[1], 0);
	TextDrawFont( Calling[1], 5);
	TextDrawLetterSize( Calling[1], 0.500000, 1.000000);
	TextDrawColor( Calling[1], 32);
	TextDrawSetOutline( Calling[1], 0);
	TextDrawSetProportional( Calling[1], 1);
	TextDrawSetShadow( Calling[1], 1);
	TextDrawTextSize( Calling[1], 92.000000, 20.000000);
	TextDrawSetPreviewModel( Calling[1], 19377);
	TextDrawSetPreviewRot( Calling[1], 0.000000, 0.000000, 90.000000, 0.000000);
	TextDrawSetSelectable( Calling[1], 1);

	Calling[2] = TextDrawCreate( 54.000000, 247.000000, "Take");
	TextDrawBackgroundColor( Calling[2], 255);
	TextDrawFont( Calling[2], 2);
	TextDrawLetterSize( Calling[2], 0.270000, 1.300000);
	TextDrawColor( Calling[2], 255);
	TextDrawSetOutline( Calling[2], 0);
	TextDrawSetProportional( Calling[2], 1);
	TextDrawSetShadow( Calling[2], 0);
	TextDrawSetSelectable( Calling[2], 0);

	Calling[3] = TextDrawCreate( 54.000000, 271.000000, "Cancel");
	TextDrawBackgroundColor( Calling[3], 255);
	TextDrawFont( Calling[3], 2);
	TextDrawLetterSize( Calling[3], 0.270000, 1.300000);
	TextDrawColor( Calling[3], 255);
	TextDrawSetOutline( Calling[3], 0);
	TextDrawSetProportional( Calling[3], 1);
	TextDrawSetShadow( Calling[3], 0);
	TextDrawSetSelectable( Calling[3], 0);
	//Nicaaiea ii /eventmenu
	TeleportEvent[13] = TextDrawCreate(247.000000, 403.975006, "LD_SPAC:WHITE");
	TextDrawLetterSize(TeleportEvent[13], 0.000000, 0.000000);
	TextDrawTextSize(TeleportEvent[13], 149.000000, 12.000000);
	TextDrawAlignment(TeleportEvent[13], 1);
	TextDrawColor(TeleportEvent[13], 0xA52A2AFF);
	TextDrawUseBox(TeleportEvent[13], 0);
	TextDrawBoxColor(TeleportEvent[13], 0x80808080);
	TextDrawSetShadow(TeleportEvent[13], 0);
	TextDrawSetOutline(TeleportEvent[13], 0);
	TextDrawBackgroundColor(TeleportEvent[13], 0x000000FF);
	TextDrawFont(TeleportEvent[13], 4);
	TextDrawSetProportional(TeleportEvent[13], 0);
	TextDrawSetSelectable(TeleportEvent[13], 0);

	TeleportEvent[12] = TextDrawCreate(248.000000, 403.975006, "LD_SPAC:WHITE");
	TextDrawLetterSize(TeleportEvent[12], 0.000000, 0.000000);
	TextDrawTextSize(TeleportEvent[12], 147.000000, 12.000000);
	TextDrawAlignment(TeleportEvent[12], 1);
	TextDrawColor(TeleportEvent[12], 0x1B181FFF);
	TextDrawUseBox(TeleportEvent[12], 0);
	TextDrawBoxColor(TeleportEvent[12], 0x80808080);
	TextDrawSetShadow(TeleportEvent[12], 0);
	TextDrawSetOutline(TeleportEvent[12], 0);
	TextDrawBackgroundColor(TeleportEvent[12], 0x000000FF);
	TextDrawFont(TeleportEvent[12], 4);
	TextDrawSetProportional(TeleportEvent[12], 0);
	TextDrawSetSelectable(TeleportEvent[12], 0);

	TeleportEvent[11] = TextDrawCreate(302.500000, 393.475006, "LD_BEAT:chit");
	TextDrawLetterSize(TeleportEvent[11], 0.000000, 0.000000);
	TextDrawTextSize(TeleportEvent[11], 37.000000, 32.000000);
	TextDrawAlignment(TeleportEvent[11], 1);
	TextDrawColor(TeleportEvent[11], 0xA52A2AFF);
	TextDrawUseBox(TeleportEvent[11], 0);
	TextDrawBoxColor(TeleportEvent[11], 0x80808080);
	TextDrawSetShadow(TeleportEvent[11], 0);
	TextDrawSetOutline(TeleportEvent[11], 0);
	TextDrawBackgroundColor(TeleportEvent[11], 0x000000FF);
	TextDrawFont(TeleportEvent[11], 4);
	TextDrawSetProportional(TeleportEvent[11], 0);
	TextDrawSetSelectable(TeleportEvent[11], 0);

	TeleportEvent[10] = TextDrawCreate(311.500122, 401.312531, "LD_BEAT:chit");
	TextDrawLetterSize(TeleportEvent[10], 0.000000, 0.000000);
	TextDrawTextSize(TeleportEvent[10], 25.129980, 21.789995);
	TextDrawAlignment(TeleportEvent[10], 1);
	TextDrawColor(TeleportEvent[10], 0x00000022);
	TextDrawUseBox(TeleportEvent[10], 0);
	TextDrawBoxColor(TeleportEvent[10], 0x80808080);
	TextDrawSetShadow(TeleportEvent[10], 0);
	TextDrawSetOutline(TeleportEvent[10], 0);
	TextDrawBackgroundColor(TeleportEvent[10], 0x000000FF);
	TextDrawFont(TeleportEvent[10], 4);
	TextDrawSetProportional(TeleportEvent[10], 0);
	TextDrawSetSelectable(TeleportEvent[10], 0);

	TeleportEvent[9] = TextDrawCreate(313.099976, 407.987244, "LD_BEAT:chit");
	TextDrawLetterSize(TeleportEvent[9], 0.000000, 0.000000);
	TextDrawTextSize(TeleportEvent[9], 16.000000, 7.000000);
	TextDrawAlignment(TeleportEvent[9], 1);
	TextDrawColor(TeleportEvent[9], 0xFFFFFFFF);
	TextDrawUseBox(TeleportEvent[9], 0);
	TextDrawBoxColor(TeleportEvent[9], 0x80808080);
	TextDrawSetShadow(TeleportEvent[9], 0);
	TextDrawSetOutline(TeleportEvent[9], 0);
	TextDrawBackgroundColor(TeleportEvent[9], 0x000000FF);
	TextDrawFont(TeleportEvent[9], 4);
	TextDrawSetProportional(TeleportEvent[9], 0);
	TextDrawSetSelectable(TeleportEvent[9], 0);

	TeleportEvent[8] = TextDrawCreate(319.099976, 413.324829, "LD_BEAT:chit");
	TextDrawLetterSize(TeleportEvent[8], 0.000000, 0.000000);
	TextDrawTextSize(TeleportEvent[8], 3.890000, 3.429999);
	TextDrawAlignment(TeleportEvent[8], 1);
	TextDrawColor(TeleportEvent[8], 0xFFFFFFFF);
	TextDrawUseBox(TeleportEvent[8], 0);
	TextDrawBoxColor(TeleportEvent[8], 0x80808080);
	TextDrawSetShadow(TeleportEvent[8], 0);
	TextDrawSetOutline(TeleportEvent[8], 0);
	TextDrawBackgroundColor(TeleportEvent[8], 0x000000FF);
	TextDrawFont(TeleportEvent[8], 4);
	TextDrawSetProportional(TeleportEvent[8], 0);
	TextDrawSetSelectable(TeleportEvent[8], 0);

	TeleportEvent[7] = TextDrawCreate(315.900024, 411.737579, "ld_spac:white");
	TextDrawLetterSize(TeleportEvent[7], 0.000000, 0.000000);
	TextDrawTextSize(TeleportEvent[7], 11.000000, 2.000000);
	TextDrawAlignment(TeleportEvent[7], 1);
	TextDrawColor(TeleportEvent[7], 0xD7D7D7FF);
	TextDrawUseBox(TeleportEvent[7], 0);
	TextDrawBoxColor(TeleportEvent[7], 0x80808080);
	TextDrawSetShadow(TeleportEvent[7], 0);
	TextDrawSetOutline(TeleportEvent[7], 0);
	TextDrawBackgroundColor(TeleportEvent[7], 0x000000FF);
	TextDrawFont(TeleportEvent[7], 4);
	TextDrawSetProportional(TeleportEvent[7], 0);
	TextDrawSetSelectable(TeleportEvent[7], 0);

	TeleportEvent[6] = TextDrawCreate(314.900024, 412.562469, "ld_spac:white");
	TextDrawLetterSize(TeleportEvent[6], 0.000000, 0.000000);
	TextDrawTextSize(TeleportEvent[6], 13.000000, 2.000000);
	TextDrawAlignment(TeleportEvent[6], 1);
	TextDrawColor(TeleportEvent[6], 0xFFFFFFFF);
	TextDrawUseBox(TeleportEvent[6], 0);
	TextDrawBoxColor(TeleportEvent[6], 0x80808080);
	TextDrawSetShadow(TeleportEvent[6], 0);
	TextDrawSetOutline(TeleportEvent[6], 0);
	TextDrawBackgroundColor(TeleportEvent[6], 0x000000FF);
	TextDrawFont(TeleportEvent[6], 4);
	TextDrawSetProportional(TeleportEvent[6], 0);
	TextDrawSetSelectable(TeleportEvent[6], 0);

	TeleportEvent[5] = TextDrawCreate(354.500000, 332.562500, "");
	TextDrawLetterSize(TeleportEvent[5], 0.325498, 1.228124);
	TextDrawTextSize(TeleportEvent[5], 1280.000000, 1280.000000);
	TextDrawAlignment(TeleportEvent[5], 1);
	TextDrawColor(TeleportEvent[5], 0xFFFFFFFF);
	TextDrawUseBox(TeleportEvent[5], 0);
	TextDrawBoxColor(TeleportEvent[5], 0x80808080);
	TextDrawSetShadow(TeleportEvent[5], 0);
	TextDrawSetOutline(TeleportEvent[5], 0);
	TextDrawBackgroundColor(TeleportEvent[5], 0x000000FF);
	TextDrawFont(TeleportEvent[5], 1);
	TextDrawSetProportional(TeleportEvent[5], 1);
	TextDrawSetSelectable(TeleportEvent[5], 0);

	TeleportEvent[4] = TextDrawCreate(316.800049, 405.362244, "ld_spac:white");
	TextDrawLetterSize(TeleportEvent[4], 0.000000, 0.000000);
	TextDrawTextSize(TeleportEvent[4], 9.000000, 6.000000);
	TextDrawAlignment(TeleportEvent[4], 1);
	TextDrawColor(TeleportEvent[4], 0xFFFFFFFF);
	TextDrawUseBox(TeleportEvent[4], 0);
	TextDrawBoxColor(TeleportEvent[4], 0x80808080);
	TextDrawSetShadow(TeleportEvent[4], 0);
	TextDrawSetOutline(TeleportEvent[4], 0);
	TextDrawBackgroundColor(TeleportEvent[4], 0x000000FF);
	TextDrawFont(TeleportEvent[4], 4);
	TextDrawSetProportional(TeleportEvent[4], 0);
	TextDrawSetSelectable(TeleportEvent[4], 0);

	TeleportEvent[3] = TextDrawCreate(314.599976, 402.387329, "LD_BEAT:chit");
	TextDrawLetterSize(TeleportEvent[3], 0.000000, 0.000000);
	TextDrawTextSize(TeleportEvent[3], 13.000000, 7.000000);
	TextDrawAlignment(TeleportEvent[3], 1);
	TextDrawColor(TeleportEvent[3], 0xFFFFFFFF);
	TextDrawUseBox(TeleportEvent[3], 0);
	TextDrawBoxColor(TeleportEvent[3], 0x80808080);
	TextDrawSetShadow(TeleportEvent[3], 0);
	TextDrawSetOutline(TeleportEvent[3], 0);
	TextDrawBackgroundColor(TeleportEvent[3], 0x000000FF);
	TextDrawFont(TeleportEvent[3], 4);
	TextDrawSetProportional(TeleportEvent[3], 0);
	TextDrawSetSelectable(TeleportEvent[3], 0);

	TeleportEvent[2] = TextDrawCreate(318.900238, 400.812500, "O");
	TextDrawLetterSize(TeleportEvent[2], 0.166997, 0.462500);
	TextDrawTextSize(TeleportEvent[2], 1280.000000, 1280.000000);
	TextDrawAlignment(TeleportEvent[2], 1);
	TextDrawColor(TeleportEvent[2], 0xFFFFFFFF);
	TextDrawUseBox(TeleportEvent[2], 0);
	TextDrawBoxColor(TeleportEvent[2], 0x80808080);
	TextDrawSetShadow(TeleportEvent[2], 0);
	TextDrawSetOutline(TeleportEvent[2], 0);
	TextDrawBackgroundColor(TeleportEvent[2], 0x000000FF);
	TextDrawFont(TeleportEvent[2], 1);
	TextDrawSetProportional(TeleportEvent[2], 1);
	TextDrawSetSelectable(TeleportEvent[2], 0);

	TeleportEvent[1] = TextDrawCreate(278.899109, 406.062500, "0:00_~W~-_/GOTP");
	TextDrawLetterSize(TeleportEvent[1], 0.196499, 0.751250);
	TextDrawTextSize(TeleportEvent[1], 1280.000000, 1280.000000);
	TextDrawAlignment(TeleportEvent[1], 2);
	TextDrawColor(TeleportEvent[1], 0xFFFF00FF);
	TextDrawUseBox(TeleportEvent[1], 0);
	TextDrawBoxColor(TeleportEvent[1], 0x80808080);
	TextDrawSetShadow(TeleportEvent[1], 0);
	TextDrawSetOutline(TeleportEvent[1], 0);
	TextDrawBackgroundColor(TeleportEvent[1], 0x000000FF);
	TextDrawFont(TeleportEvent[1], 1);
	TextDrawSetProportional(TeleportEvent[1], 1);
	TextDrawSetSelectable(TeleportEvent[1], 0);

	TeleportEvent[0] = TextDrawCreate(364.400116, 406.500000, "TELEPORT_EVENT");
	TextDrawLetterSize(TeleportEvent[0], 0.177497, 0.685625);
	TextDrawTextSize(TeleportEvent[0], 1280.000000, 1280.000000);
	TextDrawAlignment(TeleportEvent[0], 2);
	TextDrawColor(TeleportEvent[0], 0xFFFFFFFF);
	TextDrawUseBox(TeleportEvent[0], 0);
	TextDrawBoxColor(TeleportEvent[0], 0x80808080);
	TextDrawSetShadow(TeleportEvent[0], 0);
	TextDrawSetOutline(TeleportEvent[0], 0);
	TextDrawBackgroundColor(TeleportEvent[0], 0x000000FF);
	TextDrawFont(TeleportEvent[0], 1);
	TextDrawSetProportional(TeleportEvent[0], 1);
	TextDrawSetSelectable(TeleportEvent[0], 0);
	//Niae?aoaee
	EventSob[6] = TextDrawCreate(29.000000, 200.000000, "_");
	TextDrawLetterSize(EventSob[6], 0.600000, 6.099999);
	TextDrawTextSize(EventSob[6], 141.000000, 0.000000);
	TextDrawAlignment(EventSob[6], 0);
	TextDrawColor(EventSob[6], 0xFFFFFFFF);
	TextDrawUseBox(EventSob[6], 1);
	TextDrawBoxColor(EventSob[6], 0xDBD03D90);
	TextDrawSetShadow(EventSob[6], 1);
	TextDrawSetOutline(EventSob[6], 0);
	TextDrawBackgroundColor(EventSob[6], 0x000000FF);
	TextDrawFont(EventSob[6], 1);
	TextDrawSetProportional(EventSob[6], 1);
	TextDrawSetSelectable(EventSob[6], 0);

	EventSob[5] = TextDrawCreate(32.000000, 204.000000, "_");
	TextDrawLetterSize(EventSob[5], 0.600000, 5.300000);
	TextDrawTextSize(EventSob[5], 137.000000, 0.000000);
	TextDrawAlignment(EventSob[5], 0);
	TextDrawColor(EventSob[5], 0xFFFFFFFF);
	TextDrawUseBox(EventSob[5], 1);
	TextDrawBoxColor(EventSob[5], 0xC58F37FF);
	TextDrawSetShadow(EventSob[5], 1);
	TextDrawSetOutline(EventSob[5], 0);
	TextDrawBackgroundColor(EventSob[5], 0x000000FF);
	TextDrawFont(EventSob[5], 1);
	TextDrawSetProportional(EventSob[5], 1);
	TextDrawSetSelectable(EventSob[5], 0);

	EventSob[4] = TextDrawCreate(36.000000, 208.000000, "_");
	TextDrawLetterSize(EventSob[4], 0.600000, 4.500000);
	TextDrawTextSize(EventSob[4], 70.000000, 0.000000);
	TextDrawAlignment(EventSob[4], 0);
	TextDrawColor(EventSob[4], 0xFFFFFFFF);
	TextDrawUseBox(EventSob[4], 1);
	TextDrawBoxColor(EventSob[4], 0xFFFFFFFF);
	TextDrawSetShadow(EventSob[4], 1);
	TextDrawSetOutline(EventSob[4], 0);
	TextDrawBackgroundColor(EventSob[4], 0x000000FF);
	TextDrawFont(EventSob[4], 1);
	TextDrawSetProportional(EventSob[4], 1);
	TextDrawSetSelectable(EventSob[4], 0);

	EventSob[3] = TextDrawCreate(-9.000000, 198.000000, "ld_beat:up");
	TextDrawLetterSize(EventSob[3], 0.500000, 1.300000);
	TextDrawTextSize(EventSob[3], 110.000000, 91.000000);
	TextDrawAlignment(EventSob[3], 0);
	TextDrawColor(EventSob[3], 0xFFFFFFFF);
	TextDrawUseBox(EventSob[3], 1);
	TextDrawBoxColor(EventSob[3], 0x000000FF);
	TextDrawSetShadow(EventSob[3], 1);
	TextDrawSetOutline(EventSob[3], 0);
	TextDrawBackgroundColor(EventSob[3], 0x00000000);
	TextDrawFont(EventSob[3], 5);
	TextDrawSetProportional(EventSob[3], 1);
	TextDrawSetSelectable(EventSob[3], 0);
	TextDrawSetPreviewModel(EventSob[3], 19078);
	TextDrawSetPreviewRot(EventSob[3], 90.000000, 0.000000, 80.000000, 1.000000);

	EventSob[2] = TextDrawCreate(74.000000, 204.000000, "The event:");
	TextDrawLetterSize(EventSob[2], 0.160000, 1.300000);
	TextDrawTextSize(EventSob[2], 1280.000000, 1280.000000);
	TextDrawAlignment(EventSob[2], 0);
	TextDrawColor(EventSob[2], 0xFFFFFFFF);
	TextDrawUseBox(EventSob[2], 0);
	TextDrawBoxColor(EventSob[2], 0x80808080);
	TextDrawSetShadow(EventSob[2], 2);
	TextDrawSetOutline(EventSob[2], 1);
	TextDrawBackgroundColor(EventSob[2], 0x000000FF);
	TextDrawFont(EventSob[2], 2);
	TextDrawSetProportional(EventSob[2], 1);
	TextDrawSetSelectable(EventSob[2], 0);

	EventSob[1] = TextDrawCreate(74.000000, 215.000000, "collectors started in 20.15");
	TextDrawLetterSize(EventSob[1], 0.099999, 0.899999);
	TextDrawTextSize(EventSob[1], 1280.000000, 1280.000000);
	TextDrawAlignment(EventSob[1], 0);
	TextDrawColor(EventSob[1], 0xFFFFFFFF);
	TextDrawUseBox(EventSob[1], 0);
	TextDrawBoxColor(EventSob[1], 0x80808080);
	TextDrawSetShadow(EventSob[1], 2);
	TextDrawSetOutline(EventSob[1], 1);
	TextDrawBackgroundColor(EventSob[1], 0x000000FF);
	TextDrawFont(EventSob[1], 2);
	TextDrawSetProportional(EventSob[1], 1);
	TextDrawSetSelectable(EventSob[1], 0);

	EventSob[0] = TextDrawCreate(74.000000, 224.000000, "Use: /findcollectors");
	TextDrawLetterSize(EventSob[0], 0.129999, 1.400000);
	TextDrawTextSize(EventSob[0], 1280.000000, 1280.000000);
	TextDrawAlignment(EventSob[0], 0);
	TextDrawColor(EventSob[0], 0xFFFFFFFF);
	TextDrawUseBox(EventSob[0], 0);
	TextDrawBoxColor(EventSob[0], 0x80808080);
	TextDrawSetShadow(EventSob[0], 2);
	TextDrawSetOutline(EventSob[0], 1);
	TextDrawBackgroundColor(EventSob[0], 0x000000FF);
	TextDrawFont(EventSob[0], 2);
	TextDrawSetProportional(EventSob[0], 1);
	TextDrawSetSelectable(EventSob[0], 0);
	//////
	/////////////phonekey
	Pnumber[0] = TextDrawCreate(125.000000, 214.000000, "0");
	TextDrawAlignment(Pnumber[0], 2);
	TextDrawBackgroundColor(Pnumber[0], 255);
	TextDrawFont(Pnumber[0], 3);
	TextDrawLetterSize(Pnumber[0], 0.650000, 1.399999);
	TextDrawColor(Pnumber[0], -112);
	TextDrawSetOutline(Pnumber[0], 1);
	TextDrawSetProportional(Pnumber[0], 1);
	TextDrawUseBox(Pnumber[0], 1);
	TextDrawBoxColor(Pnumber[0], 32);
	TextDrawTextSize(Pnumber[0], 13.000000, 13.000000);
	TextDrawSetSelectable(Pnumber[0], 1);


	Pnumber[1] = TextDrawCreate(62.000000, 214.000000, "1");
	TextDrawAlignment(Pnumber[1], 2);
	TextDrawBackgroundColor(Pnumber[1], 255);
	TextDrawFont(Pnumber[1], 3);
	TextDrawLetterSize(Pnumber[1], 0.680000, 1.399999);
	TextDrawColor(Pnumber[1], -112);
	TextDrawSetOutline(Pnumber[1], 1);
	TextDrawSetProportional(Pnumber[1], 1);
	TextDrawUseBox(Pnumber[1], 1);
	TextDrawBoxColor(Pnumber[1], 32);
	TextDrawTextSize(Pnumber[1], 13.000000, 13.000000);
	TextDrawSetSelectable(Pnumber[1], 1);

	Pnumber[2] = TextDrawCreate(84.000000, 214.000000, "2");
	TextDrawAlignment(Pnumber[2], 2);
	TextDrawBackgroundColor(Pnumber[2], 255);
	TextDrawFont(Pnumber[2], 3);
	TextDrawLetterSize(Pnumber[2], 0.680000, 1.399999);
	TextDrawColor(Pnumber[2], -112);
	TextDrawSetOutline(Pnumber[2], 1);
	TextDrawSetProportional(Pnumber[2], 1);
	TextDrawUseBox(Pnumber[2], 1);
	TextDrawBoxColor(Pnumber[2], 32);
	TextDrawTextSize(Pnumber[2], 13.000000, 13.000000);
	TextDrawSetSelectable(Pnumber[2], 1);

	Pnumber[3] = TextDrawCreate(106.000000, 214.000000, "3");
	TextDrawAlignment(Pnumber[3], 2);
	TextDrawBackgroundColor(Pnumber[3], 255);
	TextDrawFont(Pnumber[3], 3);
	TextDrawLetterSize(Pnumber[3], 0.680000, 1.399999);
	TextDrawColor(Pnumber[3], -112);
	TextDrawSetOutline(Pnumber[3], 1);
	TextDrawSetProportional(Pnumber[3], 1);
	TextDrawUseBox(Pnumber[3], 1);
	TextDrawBoxColor(Pnumber[3], 32);
	TextDrawTextSize(Pnumber[3], 13.000000, 13.000000);
	TextDrawSetSelectable(Pnumber[3], 1);

	Pnumber[4] = TextDrawCreate(62.000000, 233.000000, "4");
	TextDrawAlignment(Pnumber[4], 2);
	TextDrawBackgroundColor(Pnumber[4], 255);
	TextDrawFont(Pnumber[4], 3);
	TextDrawLetterSize(Pnumber[4], 0.680000, 1.399999);
	TextDrawColor(Pnumber[4], -112);
	TextDrawSetOutline(Pnumber[4], 1);
	TextDrawSetProportional(Pnumber[4], 1);
	TextDrawUseBox(Pnumber[4], 1);
	TextDrawBoxColor(Pnumber[4], 32);
	TextDrawTextSize(Pnumber[4],13.000000, 13.000000);
	TextDrawSetSelectable(Pnumber[4], 1);

	Pnumber[5] = TextDrawCreate(84.000000, 233.000000, "5");
	TextDrawAlignment(Pnumber[5], 2);
	TextDrawBackgroundColor(Pnumber[5], 255);
	TextDrawFont(Pnumber[5], 3);
	TextDrawLetterSize(Pnumber[5], 0.680000, 1.399999);
	TextDrawColor(Pnumber[5], -112);
	TextDrawSetOutline(Pnumber[5], 1);
	TextDrawSetProportional(Pnumber[5], 1);
	TextDrawUseBox(Pnumber[5], 1);
	TextDrawBoxColor(Pnumber[5], 32);
	TextDrawTextSize(Pnumber[5], 13.000000, 13.000000);
	TextDrawSetSelectable(Pnumber[5], 1);

	Pnumber[6] = TextDrawCreate(106.000000, 233.000000, "6");
	TextDrawAlignment(Pnumber[6], 2);
	TextDrawBackgroundColor(Pnumber[6], 255);
	TextDrawFont(Pnumber[6], 3);
	TextDrawLetterSize(Pnumber[6], 0.680000, 1.399999);
	TextDrawColor(Pnumber[6], -112);
	TextDrawSetOutline(Pnumber[6], 1);
	TextDrawSetProportional(Pnumber[6], 1);
	TextDrawUseBox(Pnumber[6], 1);
	TextDrawBoxColor(Pnumber[6], 32);
	TextDrawTextSize(Pnumber[6], 13.000000, 13.000000);
	TextDrawSetSelectable(Pnumber[6], 1);

	Pnumber[7] = TextDrawCreate(62.000000, 252.000000, "7");
	TextDrawAlignment(Pnumber[7], 2);
	TextDrawBackgroundColor(Pnumber[7], 255);
	TextDrawFont(Pnumber[7], 3);
	TextDrawLetterSize(Pnumber[7], 0.680000, 1.399999);
	TextDrawColor(Pnumber[7], -112);
	TextDrawSetOutline(Pnumber[7], 1);
	TextDrawSetProportional(Pnumber[7], 1);
	TextDrawUseBox(Pnumber[7], 1);
	TextDrawBoxColor(Pnumber[7], 32);
	TextDrawTextSize(Pnumber[7], 13.000000, 13.000000);
	TextDrawSetSelectable(Pnumber[7], 1);

	Pnumber[8] = TextDrawCreate(84.000000, 252.000000, "8");
	TextDrawAlignment(Pnumber[8], 2);
	TextDrawBackgroundColor(Pnumber[8], 255);
	TextDrawFont(Pnumber[8], 3);
	TextDrawLetterSize(Pnumber[8], 0.680000, 1.399999);
	TextDrawColor(Pnumber[8], -112);
	TextDrawSetOutline(Pnumber[8], 1);
	TextDrawSetProportional(Pnumber[8], 1);
	TextDrawUseBox(Pnumber[8], 1);
	TextDrawBoxColor(Pnumber[8], 32);
	TextDrawTextSize(Pnumber[8], 13.000000, 13.000000);
	TextDrawSetSelectable(Pnumber[8], 1);

	Pnumber[9] = TextDrawCreate(106.000000, 252.000000, "9");
	TextDrawAlignment(Pnumber[9], 2);
	TextDrawBackgroundColor(Pnumber[9], 255);
	TextDrawFont(Pnumber[9], 3);
	TextDrawLetterSize(Pnumber[9], 0.680000, 1.399999);
	TextDrawColor(Pnumber[9], -112);
	TextDrawSetOutline(Pnumber[9], 1);
	TextDrawSetProportional(Pnumber[9], 1);
	TextDrawUseBox(Pnumber[9], 1);
	TextDrawBoxColor(Pnumber[9], 32);
	TextDrawTextSize(Pnumber[9], 13.000000, 13.000000);
	TextDrawSetSelectable(Pnumber[9], 1);

	Pnumber[10] = TextDrawCreate(41.000000, 197.000000, "xyyna");
	TextDrawBackgroundColor(Pnumber[10], 0);
	TextDrawFont(Pnumber[10], 5);
	TextDrawLetterSize(Pnumber[10], 0.500000, 1.000000);
	TextDrawColor(Pnumber[10], 32);
	TextDrawSetOutline(Pnumber[10], 0);
	TextDrawSetProportional(Pnumber[10], 1);
	TextDrawSetShadow(Pnumber[10], 1);
	TextDrawTextSize(Pnumber[10], 93.000000, 13.000000);
	TextDrawSetPreviewModel(Pnumber[10], 19377);
	TextDrawSetPreviewRot(Pnumber[10], 0.000000, 0.000000, 90.000000, 0.000000);
	TextDrawSetSelectable(Pnumber[10], 0);

	Pnumber[11] = TextDrawCreate(41.000000, 269.000000, "callersyka");
	TextDrawBackgroundColor(Pnumber[11], 0);
	TextDrawFont(Pnumber[11], 5);
	TextDrawLetterSize(Pnumber[11], 0.500000, 1.000000);
	TextDrawColor(Pnumber[11], 1003370751);
	TextDrawSetOutline(Pnumber[11], 0);
	TextDrawSetProportional(Pnumber[11], 1);
	TextDrawSetShadow(Pnumber[11], 1);
	TextDrawTextSize(Pnumber[11], 51.000000, 13.000000);
	TextDrawSetPreviewModel(Pnumber[11], 19377);
	TextDrawSetPreviewRot(Pnumber[11], 0.000000, 0.000000, 90.000000, 0.000000);
	TextDrawSetSelectable(Pnumber[11], 1);

	Pnumber[12] = TextDrawCreate(51.000000, 270.000000, "call");
	TextDrawBackgroundColor(Pnumber[12], 255);
	TextDrawFont(Pnumber[12], 2);
	TextDrawLetterSize(Pnumber[12], 0.300000, 1.000000);
	TextDrawColor(Pnumber[12], -1);
	TextDrawSetOutline(Pnumber[12], 1);
	TextDrawSetProportional(Pnumber[12], 1);
	TextDrawTextSize(Pnumber[12], 13.000000, 13.000000);
	TextDrawSetSelectable(Pnumber[12], 0);

	Pnumber[13] = TextDrawCreate(95.000000, 269.000000, "clearsyka");
	TextDrawBackgroundColor(Pnumber[13], 0);
	TextDrawFont(Pnumber[13], 5);
	TextDrawLetterSize(Pnumber[13], 0.500000, 1.000000);
	TextDrawColor(Pnumber[13], 32);
	TextDrawSetOutline(Pnumber[13], 0);
	TextDrawSetProportional(Pnumber[13], 1);
	TextDrawSetShadow(Pnumber[13], 1);
	TextDrawTextSize(Pnumber[13], 40.000000, 13.000000);
	TextDrawSetPreviewModel(Pnumber[13], 19377);
	TextDrawSetPreviewRot(Pnumber[13],0.000000, 0.000000, 90.000000, 0.000000);
	TextDrawSetSelectable(Pnumber[13], 1);

	Pnumber[14] = TextDrawCreate(102.000000, 270.000000, "clear");
	TextDrawBackgroundColor(Pnumber[14], 255);
	TextDrawFont(Pnumber[14], 2);
	TextDrawLetterSize(Pnumber[14], 0.210000, 1.000000);
	TextDrawColor(Pnumber[14], -1);
	TextDrawSetOutline(Pnumber[14], 1);
	TextDrawSetProportional(Pnumber[14], 1);
	TextDrawTextSize(Pnumber[14], 13.000000, 13.000000);
	TextDrawSetSelectable(Pnumber[14], 0);
	////
	/////////eaceii
	kbox[0] = TextDrawCreate(481.000000, 370.000000, "_");
	TextDrawBackgroundColor(kbox[0], 255);
	TextDrawFont(kbox[0], 1);
	TextDrawLetterSize(kbox[0], 0.500000, 7.099999);
	TextDrawColor(kbox[0], -1);
	TextDrawSetOutline(kbox[0], 0);
	TextDrawSetProportional(kbox[0], 1);
	TextDrawSetShadow(kbox[0], 1);
	TextDrawUseBox(kbox[0], 1);
	TextDrawBoxColor(kbox[0], 255);
	TextDrawTextSize(kbox[0], 631.000000, 0.000000);
	TextDrawSetSelectable(kbox[0], 0);

	kbox[1] = TextDrawCreate(483.000000, 373.000000, "_");
	TextDrawBackgroundColor(kbox[1], 255);
	TextDrawFont(kbox[1], 1);
	TextDrawLetterSize(kbox[1], 0.500000, 6.500000);
	TextDrawColor(kbox[1], -1);
	TextDrawSetOutline(kbox[1], 0);
	TextDrawSetProportional(kbox[1], 1);
	TextDrawSetShadow(kbox[1], 1);
	TextDrawUseBox(kbox[1], 1);
	TextDrawBoxColor(kbox[1], -1456788481);
	TextDrawTextSize(kbox[1], 629.000000, 0.000000);
	TextDrawSetSelectable(kbox[1], 0);
	/////////eaceii
	Bandito[0] = TextDrawCreate(272.000000, 147.000000, "_");
	TextDrawBackgroundColor(Bandito[0], 255);
	TextDrawFont(Bandito[0], 1);
	TextDrawLetterSize(Bandito[0], -0.199999, 15.800003);
	TextDrawColor(Bandito[0], -1);
	TextDrawSetOutline(Bandito[0], 0);
	TextDrawSetProportional(Bandito[0], 1);
	TextDrawSetShadow(Bandito[0], 1);
	TextDrawUseBox(Bandito[0], 1);
	TextDrawBoxColor(Bandito[0], -1961026049);
	TextDrawTextSize(Bandito[0], 367.000000, -2.000000);
	TextDrawSetSelectable(Bandito[0], 0);

	Bandito[1] = TextDrawCreate(320.000000, 152.000000, "Slot Machine");
	TextDrawAlignment(Bandito[1], 2);
	TextDrawBackgroundColor(Bandito[1], 255);
	TextDrawFont(Bandito[1], 2);
	TextDrawLetterSize(Bandito[1], 0.330000, 2.300000);
	TextDrawColor(Bandito[1], -1);
	TextDrawSetOutline(Bandito[1], 1);
	TextDrawSetProportional(Bandito[1], 1);
	TextDrawUseBox(Bandito[1], 1);
	TextDrawBoxColor(Bandito[1], 48);
	TextDrawTextSize(Bandito[1], 0.000000, 81.000000);
	TextDrawSetSelectable(Bandito[1], 0);

	Bandito[2] = TextDrawCreate(272.000000, 258.000000, "ld_beat:up");
	TextDrawBackgroundColor(Bandito[2], 0);
	TextDrawFont(Bandito[2], 5);
	TextDrawLetterSize(Bandito[2], 0.500000, 1.000000);
	TextDrawColor(Bandito[2], 64);
	TextDrawSetOutline(Bandito[2], 0);
	TextDrawSetProportional(Bandito[2], 1);
	TextDrawSetShadow(Bandito[2], 1);
	TextDrawTextSize(Bandito[2], 30.000000, 30.000000);
	TextDrawSetPreviewModel(Bandito[2], 19377);
	TextDrawSetPreviewRot(Bandito[2], 0.000000, 0.000000, 90.000000, 1.000000);
	TextDrawSetSelectable(Bandito[2], 1);

	Bandito[3] = TextDrawCreate(338.000000, 258.000000, "ld_beat:up");
	TextDrawBackgroundColor(Bandito[3], 0);
	TextDrawFont(Bandito[3], 5);
	TextDrawLetterSize(Bandito[3], 0.500000, 1.000000);
	TextDrawColor(Bandito[3], 64);
	TextDrawSetOutline(Bandito[3], 0);
	TextDrawSetProportional(Bandito[3], 1);
	TextDrawSetShadow(Bandito[3], 1);
	TextDrawTextSize(Bandito[3], 30.000000, 30.000000);
	TextDrawSetPreviewModel(Bandito[3], 19377);
	TextDrawSetPreviewRot(Bandito[3], 0.000000, 0.000000, 90.000000, 1.000000);
	TextDrawSetSelectable(Bandito[3], 1);
	////////////////////////////

	//////////////////////////////
	Bandito[4] = TextDrawCreate(285.000000, 264.000000, "~r~-");
	TextDrawBackgroundColor(Bandito[4], 255);
	TextDrawFont(Bandito[4], 1);
	TextDrawLetterSize(Bandito[4], 0.500000, 1.400000);
	TextDrawColor(Bandito[4], -1);
	TextDrawSetOutline(Bandito[4], 1);
	TextDrawSetProportional(Bandito[4], 1);
	TextDrawSetSelectable(Bandito[4], 0);

	Bandito[5] = TextDrawCreate(348.000000, 267.000000, "~g~+");
	TextDrawBackgroundColor(Bandito[5], 255);
	TextDrawFont(Bandito[5], 1);
	TextDrawLetterSize(Bandito[5], 0.549999, 1.200000);
	TextDrawColor(Bandito[5], -1);
	TextDrawSetOutline(Bandito[5], 1);
	TextDrawSetProportional(Bandito[5], 1);
	TextDrawSetSelectable(Bandito[5], 0);

	Bandito[6] = TextDrawCreate(299.000000, 263.000000, "ld_beat:up");
	TextDrawBackgroundColor(Bandito[6], 0);
	TextDrawFont(Bandito[6], 5);
	TextDrawLetterSize(Bandito[6], 0.500000, 1.000000);
	TextDrawColor(Bandito[6], 64);
	TextDrawSetOutline(Bandito[6], 0);
	TextDrawSetProportional(Bandito[6], 1);
	TextDrawSetShadow(Bandito[6], 1);
	TextDrawTextSize(Bandito[6], 40.000000, 20.000000);
	TextDrawSetPreviewModel(Bandito[6], 19377);
	TextDrawSetPreviewRot(Bandito[6], 0.000000, 0.000000, 90.000000, 0.000000);
	TextDrawSetSelectable(Bandito[6], 1);

	Bandito[7] = TextDrawCreate(308.000000, 268.000000, "play");
	TextDrawBackgroundColor(Bandito[7], 255);
	TextDrawFont(Bandito[7], 2);
	TextDrawLetterSize(Bandito[7], 0.240000, 1.000000);
	TextDrawColor(Bandito[7], -1);
	TextDrawSetOutline(Bandito[7], 1);
	TextDrawSetProportional(Bandito[7], 1);
	TextDrawSetSelectable(Bandito[7], 0);

	Bandito[8] = TextDrawCreate(364.000000, 139.000000, "ld_beat:up");
	TextDrawBackgroundColor(Bandito[8], 0);
	TextDrawFont(Bandito[8], 5);
	TextDrawLetterSize(Bandito[8], 0.500000, 1.000000);
	TextDrawColor(Bandito[8], 64);
	TextDrawSetOutline(Bandito[8], 0);
	TextDrawSetProportional(Bandito[8], 1);
	TextDrawSetShadow(Bandito[8], 1);
	TextDrawTextSize(Bandito[8], 30.000000, 30.000000);
	TextDrawSetPreviewModel(Bandito[8], 19377);
	TextDrawSetPreviewRot(Bandito[8], 0.000000, 0.000000, 90.000000, 1.000000);
	TextDrawSetSelectable(Bandito[8], 1);

	Bandito[9] = TextDrawCreate(371.000000, 140.000000, "~r~x");
	TextDrawBackgroundColor(Bandito[9], 255);
	TextDrawFont(Bandito[9], 2);
	TextDrawLetterSize(Bandito[9], 0.629999, 2.799999);
	TextDrawColor(Bandito[9], -1);
	TextDrawSetOutline(Bandito[9], 1);
	TextDrawSetProportional(Bandito[9], 1);
	TextDrawSetSelectable(Bandito[9], 0);
    /////////////////////////////////////////
