	tuntext_p[playerid][131] = CreatePlayerTextDraw(playerid, 320.299988, 138.642853, "usebox");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][131], 0.000000, 25.207449);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][131], 182.500000, 0.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][131], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][131], 0xE1E1E1FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][131], 1);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][131], 0x111111FF);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][131], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][131], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][131], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][131], 0);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][131], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][131], 0);

	tuntext_p[playerid][130] = CreatePlayerTextDraw(playerid, 190.000000, 143.218063, "SHOP");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][130], 0.184640, 0.984959);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][130], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][130], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][130], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][130], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][130], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][130], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][130], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][130], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][130], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][130], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][130], 0);

	tuntext_p[playerid][129] = CreatePlayerTextDraw(playerid, 320.299988, 160.642853, "usebox");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][129], 0.000000, -0.214150);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][129], 182.500000, 0.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][129], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][129], 0xE1E1E1FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][129], 1);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][129], 0x1C1F21FF);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][129], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][129], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][129], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][129], 0);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][129], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][129], 0);

	tuntext_p[playerid][128] = CreatePlayerTextDraw(playerid, 320.299988, 338.642853, "usebox");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][128], 0.000000, 3.037451);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][128], 182.500000, 0.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][128], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][128], 0xE1E1E1FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][128], 1);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][128], 0x1A1A1AFF);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][128], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][128], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][128], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][128], 0);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][128], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][128], 0);

	tuntext_p[playerid][127] = CreatePlayerTextDraw(playerid, 280.605530, 343.698395, "usebox");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][127], 0.000000, 1.916634);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][127], 222.194427, 0.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][127], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][127], 0xE1E1E1FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][127], 1);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][127], 0x050505FF);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][127], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][127], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][127], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][127], 0);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][127], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][127], 0);

	tuntext_p[playerid][126] = CreatePlayerTextDraw(playerid, 224.694427, 343.198395, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][126], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][126], 15.888894, 18.222229);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][126], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][126], 0x1A1A1AFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][126], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][126], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][126], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][126], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][126], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][126], 4);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][126], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][126], 1);

	tuntext_p[playerid][125] = CreatePlayerTextDraw(playerid, 232.023407, 349.026306, "<");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][125], 0.123093, 0.656639);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][125], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][125], 2);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][125], 0x777777FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][125], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][125], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][125], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][125], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][125], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][125], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][125], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][125], 0);

	tuntext_p[playerid][124] = CreatePlayerTextDraw(playerid, 262.416656, 343.198395, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][124], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][124], 15.888894, 18.222229);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][124], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][124], 0x1A1A1AFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][124], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][124], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][124], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][124], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][124], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][124], 4);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][124], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][124], 1);

	tuntext_p[playerid][123] = CreatePlayerTextDraw(playerid, 269.745636, 349.026306, ">");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][123], 0.123093, 0.656639);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][123], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][123], 2);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][123], 0x777777FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][123], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][123], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][123], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][123], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][123], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][123], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][123], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][123], 0);

	tuntext_p[playerid][122] = CreatePlayerTextDraw(playerid, 251.500000, 349.026306, "1");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][122], 0.123093, 0.656639);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][122], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][122], 2);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][122], 0x777777FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][122], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][122], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][122], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][122], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][122], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][122], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][122], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][122], 0);

	tuntext_p[playerid][121] = CreatePlayerTextDraw(playerid, 482.299988, 138.642853, "usebox");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][121], 0.000000, 25.207449);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][121], 318.500000, 0.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][121], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][121], 0xE1E1E1FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][121], 1);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][121], 0x111111FF);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][121], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][121], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][121], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][121], 0);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][121], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][121], 0);

	tuntext_p[playerid][120] = CreatePlayerTextDraw(playerid, 326.000000, 143.218063, "INVENTORY");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][120], 0.184640, 0.984959);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][120], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][120], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][120], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][120], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][120], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][120], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][120], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][120], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][120], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][120], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][120], 0);

	tuntext_p[playerid][119] = CreatePlayerTextDraw(playerid, 482.299988, 160.642853, "usebox");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][119], 0.000000, -0.214150);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][119], 318.500000, 0.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][119], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][119], 0xE1E1E1FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][119], 1);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][119], 0x1C1F21FF);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][119], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][119], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][119], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][119], 0);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][119], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][119], 0);

	tuntext_p[playerid][118] = CreatePlayerTextDraw(playerid, 436.333344, 346.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][118], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][118], 41.666664, 18.333334);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][118], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][118], 0x1C1F21FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][118], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][118], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][118], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][118], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][118], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][118], 4);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][118], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][118], 1);

	tuntext_p[playerid][117] = CreatePlayerTextDraw(playerid, 457.166687, 350.384735, "CLOSE");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][117], 0.184640, 0.984959);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][117], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][117], 2);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][117], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][117], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][117], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][117], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][117], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][117], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][117], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][117], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][117], 0);

	tuntext_p[playerid][116] = CreatePlayerTextDraw(playerid, 461.333313, 139.476181, "LD_BEAT:chit");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][116], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][116], 16.666666, 18.333334);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][116], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][116], 0x111111FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][116], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][116], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][116], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][116], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][116], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][116], 4);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][116], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][116], 1);

	tuntext_p[playerid][115] = CreatePlayerTextDraw(playerid, 469.666656, 143.718048, "S");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][115], 0.184640, 0.984959);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][115], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][115], 2);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][115], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][115], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][115], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][115], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][115], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][115], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][115], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][115], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][115], 0);

	tuntext_p[playerid][114] = CreatePlayerTextDraw(playerid, 444.666656, 139.476181, "LD_BEAT:chit");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][114], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][114], 16.666666, 18.333334);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][114], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][114], 0x111111FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][114], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][114], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][114], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][114], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][114], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][114], 4);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][114], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][114], 1);

	tuntext_p[playerid][113] = CreatePlayerTextDraw(playerid, 453.000000, 143.718048, "P");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][113], 0.184640, 0.984959);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][113], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][113], 2);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][113], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][113], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][113], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][113], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][113], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][113], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][113], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][113], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][113], 0);

	tuntext_p[playerid][112] = CreatePlayerTextDraw(playerid, 428.000000, 139.476181, "LD_BEAT:chit");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][112], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][112], 16.666666, 18.333334);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][112], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][112], 0x111111FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][112], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][112], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][112], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][112], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][112], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][112], 4);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][112], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][112], 1);

	tuntext_p[playerid][111] = CreatePlayerTextDraw(playerid, 436.333344, 143.718048, "C");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][111], 0.184640, 0.984959);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][111], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][111], 2);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][111], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][111], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][111], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][111], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][111], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][111], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][111], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][111], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][111], 0);

	tuntext_p[playerid][110] = CreatePlayerTextDraw(playerid, 411.333344, 139.476181, "LD_BEAT:chit");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][110], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][110], 16.666666, 18.333334);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][110], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][110], 0x111111FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][110], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][110], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][110], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][110], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][110], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][110], 4);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][110], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][110], 1);

	tuntext_p[playerid][109] = CreatePlayerTextDraw(playerid, 419.666687, 143.718048, "S");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][109], 0.184640, 0.984959);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][109], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][109], 2);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][109], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][109], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][109], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][109], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][109], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][109], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][109], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][109], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][109], 0);

	tuntext_p[playerid][108] = CreatePlayerTextDraw(playerid, 391.500000, 337.642853, "LD_BEAT:chit");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][108], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][108], 5.000000, 5.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][108], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][108], 0x555555FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][108], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][108], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][108], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][108], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][108], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][108], 4);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][108], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][108], 0);

	tuntext_p[playerid][107] = CreatePlayerTextDraw(playerid, 397.500000, 337.642853, "LD_BEAT:chit");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][107], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][107], 5.000000, 5.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][107], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][107], 0x1C1F21FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][107], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][107], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][107], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][107], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][107], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][107], 4);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][107], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][107], 1);

	tuntext_p[playerid][106] = CreatePlayerTextDraw(playerid, 403.500000, 337.642853, "LD_BEAT:chit");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][106], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][106], 5.000000, 5.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][106], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][106], 0x0E1011FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][106], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][106], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][106], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][106], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][106], 0x000000FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][106], 4);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][106], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][106], 0);

	tuntext_p[playerid][105] = CreatePlayerTextDraw(playerid, 187.000000, 163.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][105], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][105], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][105], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][105], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][105], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][105], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][105], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][105], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][105], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][105], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][105], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][105], 1);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][105], 2694);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][105], 90.000000, 0.000000, 90.000000, 0.811783);

	tuntext_p[playerid][104] = CreatePlayerTextDraw(playerid, 211.019608, 185.049637, "$10000000");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][104], 0.099215, 0.466102);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][104], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][104], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][104], 0x76EB5EAA);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][104], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][104], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][104], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][104], 1);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][104], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][104], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][104], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][104], 0);

	tuntext_p[playerid][103] = CreatePlayerTextDraw(playerid, 213.000000, 163.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][103], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][103], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][103], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][103], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][103], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][103], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][103], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][103], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][103], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][103], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][103], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][103], 1);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][103], 1288);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][103], 178.000000, 90.000000, 360.000000, 1.584983);

	tuntext_p[playerid][102] = CreatePlayerTextDraw(playerid, 237.019608, 185.049637, "$10000000");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][102], 0.099215, 0.466102);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][102], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][102], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][102], 0x76EB5EAA);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][102], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][102], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][102], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][102], 1);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][102], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][102], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][102], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][102], 0);

	tuntext_p[playerid][101] = CreatePlayerTextDraw(playerid, 239.000000, 163.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][101], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][101], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][101], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][101], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][101], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][101], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][101], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][101], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][101], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][101], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][101], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][101], 1);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][101], 19917);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][101], 160.000000, 174.000000, 195.000000, 1.000000);

	tuntext_p[playerid][100] = CreatePlayerTextDraw(playerid, 263.019623, 185.049637, "$10000000");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][100], 0.099215, 0.466102);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][100], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][100], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][100], 0x76EB5EAA);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][100], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][100], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][100], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][100], 1);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][100], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][100], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][100], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][100], 0);

	tuntext_p[playerid][99] = CreatePlayerTextDraw(playerid, 265.000000, 163.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][99], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][99], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][99], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][99], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][99], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][99], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][99], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][99], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][99], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][99], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][99], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][99], 1);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][99], 18846);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][99], 0.000000, 0.000000, 0.000000, 1.00000);

	tuntext_p[playerid][98] = CreatePlayerTextDraw(playerid, 289.019623, 185.049637, "$10000000");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][98], 0.099215, 0.466102);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][98], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][98], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][98], 0x76EB5EAA);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][98], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][98], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][98], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][98], 1);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][98], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][98], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][98], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][98], 0);

	tuntext_p[playerid][97] = CreatePlayerTextDraw(playerid, 291.000000, 163.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][97], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][97], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][97], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][97], 0xFFFFFFFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][97], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][97], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][97], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][97], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][97], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][97], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][97], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][97], 1);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][97], 1097);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][97], 0.000000, 0.000000, 0.000000, 1.00000);

	tuntext_p[playerid][96] = CreatePlayerTextDraw(playerid, 315.019623, 185.049637, "$10000000");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][96], 0.099215, 0.466102);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][96], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][96], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][96], 0x76EB5EAA);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][96], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][96], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][96], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][96], 1);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][96], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][96], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][96], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][96], 0);

	tuntext_p[playerid][95] = CreatePlayerTextDraw(playerid, 187.000000, 191.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][95], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][95], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][95], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][95], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][95], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][95], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][95], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][95], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][95], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][95], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][95], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][95], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][95], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][95], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][94] = CreatePlayerTextDraw(playerid, 213.000000, 191.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][94], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][94], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][94], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][94], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][94], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][94], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][94], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][94], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][94], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][94], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][94], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][94], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][94], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][94], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][93] = CreatePlayerTextDraw(playerid, 239.000000, 191.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][93], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][93], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][93], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][93], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][93], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][93], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][93], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][93], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][93], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][93], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][93], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][93], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][93], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][93], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][92] = CreatePlayerTextDraw(playerid, 265.000000, 191.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][92], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][92], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][92], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][92], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][92], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][92], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][92], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][92], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][92], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][92], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][92], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][92], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][92], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][92], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][91] = CreatePlayerTextDraw(playerid, 291.000000, 191.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][91], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][91], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][91], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][91], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][91], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][91], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][91], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][91], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][91], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][91], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][91], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][91], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][91], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][91], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][90] = CreatePlayerTextDraw(playerid, 187.000000, 220.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][90], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][90], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][90], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][90], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][90], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][90], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][90], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][90], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][90], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][90], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][90], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][90], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][90], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][90], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][89] = CreatePlayerTextDraw(playerid, 213.000000, 220.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][89], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][89], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][89], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][89], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][89], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][89], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][89], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][89], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][89], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][89], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][89], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][89], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][89], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][89], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][88] = CreatePlayerTextDraw(playerid, 239.000000, 220.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][88], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][88], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][88], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][88], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][88], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][88], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][88], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][88], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][88], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][88], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][88], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][88], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][88], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][88], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][87] = CreatePlayerTextDraw(playerid, 265.000000, 220.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][87], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][87], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][87], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][87], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][87], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][87], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][87], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][87], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][87], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][87], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][87], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][87], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][87], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][87], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][86] = CreatePlayerTextDraw(playerid, 291.000000, 220.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][86], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][86], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][86], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][86], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][86], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][86], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][86], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][86], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][86], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][86], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][86], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][86], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][86], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][86], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][85] = CreatePlayerTextDraw(playerid, 187.000000, 248.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][85], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][85], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][85], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][85], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][85], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][85], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][85], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][85], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][85], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][85], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][85], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][85], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][85], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][85], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][84] = CreatePlayerTextDraw(playerid, 213.000000, 248.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][84], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][84], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][84], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][84], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][84], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][84], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][84], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][84], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][84], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][84], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][84], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][84], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][84], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][84], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][83] = CreatePlayerTextDraw(playerid, 239.000000, 248.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][83], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][83], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][83], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][83], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][83], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][83], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][83], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][83], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][83], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][83], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][83], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][83], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][83], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][83], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][82] = CreatePlayerTextDraw(playerid, 265.000000, 248.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][82], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][82], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][82], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][82], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][82], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][82], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][82], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][82], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][82], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][82], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][82], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][82], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][82], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][82], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][81] = CreatePlayerTextDraw(playerid, 291.000000, 248.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][81], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][81], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][81], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][81], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][81], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][81], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][81], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][81], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][81], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][81], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][81], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][81], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][81], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][81], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][80] = CreatePlayerTextDraw(playerid, 187.000000, 277.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][80], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][80], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][80], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][80], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][80], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][80], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][80], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][80], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][80], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][80], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][80], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][80], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][80], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][80], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][79] = CreatePlayerTextDraw(playerid, 213.000000, 277.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][79], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][79], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][79], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][79], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][79], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][79], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][79], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][79], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][79], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][79], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][79], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][79], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][79], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][79], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][78] = CreatePlayerTextDraw(playerid, 239.000000, 277.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][78], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][78], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][78], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][78], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][78], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][78], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][78], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][78], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][78], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][78], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][78], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][78], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][78], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][78], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][77] = CreatePlayerTextDraw(playerid, 265.000000, 277.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][77], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][77], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][77], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][77], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][77], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][77], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][77], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][77], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][77], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][77], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][77], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][77], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][77], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][77], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][76] = CreatePlayerTextDraw(playerid, 291.000000, 277.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][76], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][76], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][76], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][76], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][76], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][76], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][76], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][76], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][76], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][76], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][76], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][76], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][76], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][76], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][75] = CreatePlayerTextDraw(playerid, 187.000000, 305.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][75], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][75], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][75], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][75], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][75], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][75], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][75], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][75], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][75], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][75], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][75], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][75], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][75], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][75], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][74] = CreatePlayerTextDraw(playerid, 213.000000, 305.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][74], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][74], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][74], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][74], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][74], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][74], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][74], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][74], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][74], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][74], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][74], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][74], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][74], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][74], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][73] = CreatePlayerTextDraw(playerid, 239.000000, 305.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][73], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][73], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][73], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][73], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][73], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][73], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][73], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][73], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][73], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][73], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][73], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][73], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][73], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][73], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][72] = CreatePlayerTextDraw(playerid, 265.000000, 305.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][72], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][72], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][72], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][72], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][72], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][72], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][72], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][72], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][72], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][72], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][72], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][72], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][72], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][72], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][71] = CreatePlayerTextDraw(playerid, 291.000000, 305.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][71], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][71], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][71], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][71], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][71], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][71], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][71], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][71], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][71], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][71], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][71], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][71], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][71], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][71], 0.000000, 0.000000, 90.000000, 2.000000);

	/*tuntext_p[playerid][70] = CreatePlayerTextDraw(playerid, 323.000000, 163.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][70], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][70], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][70], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][70], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][70], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][70], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][70], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][70], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][70], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][70], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][70], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][70], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][70], 19627);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][70], 108.000000, 0.000000, 119.000000, 0.980186);

	tuntext_p[playerid][69] = CreatePlayerTextDraw(playerid, 347.019623, 183.884384, "2");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][69], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][69], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][69], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][69], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][69], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][69], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][69], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][69], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][69], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][69], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][69], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][69], 0);

	tuntext_p[playerid][68] = CreatePlayerTextDraw(playerid, 349.000000, 163.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][68], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][68], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][68], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][68], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][68], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][68], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][68], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][68], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][68], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][68], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][68], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][68], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][68], 1979);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][68], 264.000000, 178.000000, 189.000000, 1.845672);

	tuntext_p[playerid][67] = CreatePlayerTextDraw(playerid, 373.019623, 183.884384, "3");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][67], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][67], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][67], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][67], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][67], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][67], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][67], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][67], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][67], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][67], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][67], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][67], 0);

	tuntext_p[playerid][66] = CreatePlayerTextDraw(playerid, 375.000000, 163.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][66], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][66], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][66], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][66], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][66], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][66], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][66], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][66], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][66], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][66], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][66], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][66], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][66], 1924);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][66], 289.000000, 0.000000, 297.000000, 1.032325);

	tuntext_p[playerid][65] = CreatePlayerTextDraw(playerid, 399.019623, 183.884384, "2");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][65], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][65], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][65], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][65], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][65], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][65], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][65], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][65], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][65], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][65], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][65], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][65], 0);

	tuntext_p[playerid][64] = CreatePlayerTextDraw(playerid, 401.000000, 163.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][64], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][64], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][64], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][64], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][64], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][64], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][64], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][64], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][64], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][64], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][64], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][64], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][64], 1650);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][64], 360.000000, 360.000000, 11.000000, 1.100103);

	tuntext_p[playerid][63] = CreatePlayerTextDraw(playerid, 425.019623, 183.884384, "4");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][63], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][63], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][63], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][63], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][63], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][63], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][63], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][63], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][63], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][63], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][63], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][63], 0);

	tuntext_p[playerid][62] = CreatePlayerTextDraw(playerid, 427.000000, 163.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][62], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][62], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][62], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][62], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][62], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][62], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][62], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][62], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][62], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][62], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][62], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][62], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][62], 19627);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][62], 108.000000, 0.000000, 119.000000, 0.980186);

	tuntext_p[playerid][61] = CreatePlayerTextDraw(playerid, 451.019623, 183.884384, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][61], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][61], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][61], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][61], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][61], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][61], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][61], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][61], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][61], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][61], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][61], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][61], 0);

	tuntext_p[playerid][60] = CreatePlayerTextDraw(playerid, 453.000000, 163.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][60], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][60], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][60], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][60], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][60], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][60], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][60], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][60], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][60], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][60], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][60], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][60], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][60], 19627);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][60], 108.000000, 0.000000, 119.000000, 0.980186);

	tuntext_p[playerid][59] = CreatePlayerTextDraw(playerid, 477.019623, 183.884384, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][59], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][59], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][59], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][59], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][59], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][59], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][59], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][59], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][59], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][59], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][59], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][59], 0);

	tuntext_p[playerid][58] = CreatePlayerTextDraw(playerid, 323.000000, 191.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][58], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][58], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][58], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][58], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][58], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][58], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][58], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][58], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][58], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][58], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][58], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][58], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][58], 19627);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][58], 108.000000, 0.000000, 119.000000, 0.980186);

	tuntext_p[playerid][57] = CreatePlayerTextDraw(playerid, 347.019623, 212.384384, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][57], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][57], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][57], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][57], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][57], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][57], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][57], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][57], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][57], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][57], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][57], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][57], 0);

	tuntext_p[playerid][56] = CreatePlayerTextDraw(playerid, 349.000000, 191.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][56], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][56], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][56], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][56], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][56], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][56], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][56], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][56], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][56], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][56], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][56], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][56], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][56], 1486);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][56], 333.000000, 12.000000, 286.000000, 0.928049);

	tuntext_p[playerid][55] = CreatePlayerTextDraw(playerid, 373.019623, 212.384384, "6");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][55], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][55], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][55], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][55], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][55], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][55], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][55], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][55], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][55], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][55], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][55], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][55], 0);

	tuntext_p[playerid][54] = CreatePlayerTextDraw(playerid, 375.000000, 191.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][54], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][54], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][54], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][54], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][54], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][54], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][54], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][54], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][54], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][54], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][54], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][54], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][54], 1979);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][54], 264.000000, 178.000000, 189.000000, 1.845672);

	tuntext_p[playerid][53] = CreatePlayerTextDraw(playerid, 399.019623, 212.384384, "3");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][53], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][53], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][53], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][53], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][53], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][53], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][53], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][53], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][53], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][53], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][53], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][53], 0);

	tuntext_p[playerid][52] = CreatePlayerTextDraw(playerid, 401.000000, 191.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][52], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][52], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][52], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][52], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][52], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][52], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][52], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][52], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][52], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][52], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][52], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][52], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][52], 19320);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][52], 360.000000, 39.000000, 177.000000, 0.672574);

	tuntext_p[playerid][51] = CreatePlayerTextDraw(playerid, 425.019623, 212.384384, "4");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][51], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][51], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][51], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][51], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][51], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][51], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][51], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][51], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][51], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][51], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][51], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][51], 0);

	tuntext_p[playerid][50] = CreatePlayerTextDraw(playerid, 427.000000, 191.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][50], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][50], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][50], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][50], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][50], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][50], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][50], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][50], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][50], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][50], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][50], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][50], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][50], 1979);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][50], 264.000000, 178.000000, 189.000000, 1.845672);

	tuntext_p[playerid][49] = CreatePlayerTextDraw(playerid, 451.019623, 212.384384, "2");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][49], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][49], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][49], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][49], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][49], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][49], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][49], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][49], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][49], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][49], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][49], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][49], 0);

	tuntext_p[playerid][48] = CreatePlayerTextDraw(playerid, 453.000000, 191.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][48], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][48], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][48], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][48], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][48], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][48], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][48], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][48], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][48], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][48], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][48], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][48], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][48], 1650);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][48], 360.000000, 360.000000, 11.000000, 1.100103);

	tuntext_p[playerid][47] = CreatePlayerTextDraw(playerid, 477.019623, 212.384384, "4");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][47], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][47], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][47], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][47], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][47], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][47], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][47], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][47], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][47], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][47], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][47], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][47], 0);

	tuntext_p[playerid][46] = CreatePlayerTextDraw(playerid, 323.000000, 220.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][46], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][46], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][46], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][46], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][46], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][46], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][46], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][46], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][46], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][46], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][46], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][46], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][46], 1242);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][46], 360.000000, 360.000000, 8.000000, 0.980186);

	tuntext_p[playerid][45] = CreatePlayerTextDraw(playerid, 347.019623, 240.884384, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][45], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][45], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][45], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][45], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][45], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][45], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][45], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][45], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][45], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][45], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][45], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][45], 0);

	tuntext_p[playerid][44] = CreatePlayerTextDraw(playerid, 349.000000, 220.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][44], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][44], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][44], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][44], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][44], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][44], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][44], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][44], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][44], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][44], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][44], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][44], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][44], 1649);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][44], 0.000000, 0.000000, 90.000000, 2.000000);

	tuntext_p[playerid][43] = CreatePlayerTextDraw(playerid, 375.000000, 220.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][43], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][43], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][43], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][43], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][43], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][43], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][43], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][43], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][43], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][43], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][43], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][43], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][43], 19801);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][43], 360.000000, 360.000000, 121.000000, 0.823773);

	tuntext_p[playerid][42] = CreatePlayerTextDraw(playerid, 399.019623, 240.884384, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][42], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][42], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][42], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][42], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][42], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][42], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][42], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][42], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][42], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][42], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][42], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][42], 0);

	tuntext_p[playerid][41] = CreatePlayerTextDraw(playerid, 401.000000, 220.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][41], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][41], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][41], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][41], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][41], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][41], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][41], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][41], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][41], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][41], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][41], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][41], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][41], 19320);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][41], 360.000000, 39.000000, 177.000000, 0.672574);

	tuntext_p[playerid][40] = CreatePlayerTextDraw(playerid, 425.019623, 240.884384, "4");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][40], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][40], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][40], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][40], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][40], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][40], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][40], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][40], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][40], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][40], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][40], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][40], 0);

	tuntext_p[playerid][39] = CreatePlayerTextDraw(playerid, 427.000000, 220.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][39], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][39], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][39], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][39], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][39], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][39], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][39], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][39], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][39], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][39], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][39], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][39], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][39], 19801);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][39], 360.000000, 360.000000, 121.000000, 0.823773);

	tuntext_p[playerid][38] = CreatePlayerTextDraw(playerid, 451.019623, 240.884384, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][38], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][38], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][38], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][38], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][38], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][38], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][38], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][38], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][38], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][38], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][38], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][38], 0);

	tuntext_p[playerid][37] = CreatePlayerTextDraw(playerid, 453.000000, 220.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][37], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][37], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][37], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][37], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][37], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][37], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][37], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][37], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][37], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][37], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][37], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][37], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][37], 1979);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][37], 264.000000, 178.000000, 189.000000, 1.845672);

	tuntext_p[playerid][36] = CreatePlayerTextDraw(playerid, 477.019623, 240.884384, "3");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][36], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][36], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][36], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][36], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][36], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][36], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][36], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][36], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][36], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][36], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][36], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][36], 0);

	tuntext_p[playerid][35] = CreatePlayerTextDraw(playerid, 323.000000, 248.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][35], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][35], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][35], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][35], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][35], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][35], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][35], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][35], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][35], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][35], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][35], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][35], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][35], 19627);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][35], 108.000000, 0.000000, 119.000000, 0.980186);

	tuntext_p[playerid][34] = CreatePlayerTextDraw(playerid, 347.019623, 269.384369, "3");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][34], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][34], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][34], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][34], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][34], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][34], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][34], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][34], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][34], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][34], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][34], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][34], 0);

	tuntext_p[playerid][33] = CreatePlayerTextDraw(playerid, 349.000000, 248.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][33], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][33], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][33], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][33], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][33], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][33], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][33], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][33], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][33], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][33], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][33], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][33], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][33], 19801);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][33], 360.000000, 360.000000, 121.000000, 0.823773);

	tuntext_p[playerid][32] = CreatePlayerTextDraw(playerid, 373.019623, 269.384369, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][32], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][32], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][32], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][32], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][32], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][32], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][32], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][32], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][32], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][32], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][32], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][32], 0);

	tuntext_p[playerid][31] = CreatePlayerTextDraw(playerid, 375.000000, 248.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][31], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][31], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][31], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][31], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][31], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][31], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][31], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][31], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][31], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][31], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][31], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][31], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][31], 19801);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][31], 360.000000, 360.000000, 121.000000, 0.823773);

	tuntext_p[playerid][30] = CreatePlayerTextDraw(playerid, 399.019623, 269.384369, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][30], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][30], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][30], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][30], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][30], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][30], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][30], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][30], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][30], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][30], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][30], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][30], 0);

	tuntext_p[playerid][29] = CreatePlayerTextDraw(playerid, 401.000000, 248.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][29], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][29], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][29], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][29], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][29], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][29], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][29], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][29], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][29], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][29], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][29], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][29], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][29], 348);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][29], 0.000000, 32.000000, 189.000000, 0.797705);

	tuntext_p[playerid][28] = CreatePlayerTextDraw(playerid, 425.019623, 269.384369, "142");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][28], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][28], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][28], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][28], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][28], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][28], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][28], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][28], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][28], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][28], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][28], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][28], 0);

	tuntext_p[playerid][27] = CreatePlayerTextDraw(playerid, 427.000000, 248.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][27], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][27], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][27], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][27], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][27], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][27], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][27], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][27], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][27], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][27], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][27], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][27], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][27], 19342);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][27], 253.000000, 141.000000, 0.000000, 1.210844);

	tuntext_p[playerid][26] = CreatePlayerTextDraw(playerid, 451.019623, 269.384369, "4");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][26], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][26], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][26], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][26], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][26], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][26], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][26], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][26], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][26], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][26], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][26], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][26], 0);

	tuntext_p[playerid][25] = CreatePlayerTextDraw(playerid, 453.000000, 248.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][25], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][25], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][25], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][25], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][25], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][25], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][25], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][25], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][25], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][25], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][25], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][25], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][25], 1650);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][25], 360.000000, 360.000000, 11.000000, 1.100103);

	tuntext_p[playerid][24] = CreatePlayerTextDraw(playerid, 477.019623, 269.384369, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][24], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][24], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][24], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][24], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][24], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][24], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][24], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][24], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][24], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][24], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][24], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][24], 0);

	tuntext_p[playerid][23] = CreatePlayerTextDraw(playerid, 323.000000, 277.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][23], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][23], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][23], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][23], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][23], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][23], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][23], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][23], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][23], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][23], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][23], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][23], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][23], 19801);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][23], 360.000000, 360.000000, 121.000000, 0.823773);

	tuntext_p[playerid][22] = CreatePlayerTextDraw(playerid, 347.019623, 297.884369, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][22], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][22], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][22], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][22], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][22], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][22], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][22], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][22], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][22], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][22], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][22], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][22], 0);

	tuntext_p[playerid][21] = CreatePlayerTextDraw(playerid, 349.000000, 277.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][21], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][21], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][21], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][21], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][21], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][21], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][21], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][21], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][21], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][21], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][21], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][21], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][21], 1650);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][21], 360.000000, 360.000000, 11.000000, 1.100103);

	tuntext_p[playerid][20] = CreatePlayerTextDraw(playerid, 373.019623, 297.884369, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][20], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][20], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][20], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][20], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][20], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][20], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][20], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][20], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][20], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][20], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][20], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][20], 0);

	tuntext_p[playerid][19] = CreatePlayerTextDraw(playerid, 375.000000, 277.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][19], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][19], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][19], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][19], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][19], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][19], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][19], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][19], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][19], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][19], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][19], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][19], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][19], 1650);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][19], 360.000000, 360.000000, 11.000000, 1.100103);

	tuntext_p[playerid][18] = CreatePlayerTextDraw(playerid, 399.019623, 297.884369, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][18], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][18], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][18], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][18], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][18], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][18], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][18], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][18], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][18], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][18], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][18], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][18], 0);

	tuntext_p[playerid][17] = CreatePlayerTextDraw(playerid, 401.000000, 277.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][17], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][17], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][17], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][17], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][17], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][17], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][17], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][17], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][17], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][17], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][17], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][17], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][17], 1650);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][17], 360.000000, 360.000000, 11.000000, 1.100103);

	tuntext_p[playerid][16] = CreatePlayerTextDraw(playerid, 425.019623, 297.884369, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][16], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][16], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][16], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][16], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][16], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][16], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][16], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][16], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][16], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][16], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][16], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][16], 0);

	tuntext_p[playerid][15] = CreatePlayerTextDraw(playerid, 427.000000, 277.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][15], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][15], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][15], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][15], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][15], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][15], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][15], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][15], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][15], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][15], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][15], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][15], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][15], 1650);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][15], 360.000000, 360.000000, 11.000000, 1.100103);

	tuntext_p[playerid][14] = CreatePlayerTextDraw(playerid, 451.019623, 297.884369, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][14], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][14], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][14], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][14], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][14], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][14], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][14], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][14], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][14], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][14], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][14], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][14], 0);

	tuntext_p[playerid][13] = CreatePlayerTextDraw(playerid, 453.000000, 277.142853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][13], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][13], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][13], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][13], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][13], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][13], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][13], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][13], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][13], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][13], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][13], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][13], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][13], 11723);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][13], 90.000000, 0.000000, 90.000000, 0.811783);

	tuntext_p[playerid][12] = CreatePlayerTextDraw(playerid, 477.019623, 297.884369, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][12], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][12], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][12], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][12], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][12], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][12], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][12], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][12], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][12], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][12], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][12], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][12], 0);

	tuntext_p[playerid][11] = CreatePlayerTextDraw(playerid, 323.000000, 305.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][11], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][11], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][11], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][11], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][11], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][11], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][11], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][11], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][11], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][11], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][11], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][11], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][11], 1650);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][11], 360.000000, 360.000000, 11.000000, 1.100103);

	tuntext_p[playerid][10] = CreatePlayerTextDraw(playerid, 347.019623, 326.384369, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][10], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][10], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][10], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][10], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][10], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][10], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][10], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][10], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][10], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][10], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][10], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][10], 0);

	tuntext_p[playerid][9] = CreatePlayerTextDraw(playerid, 349.000000, 305.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][9], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][9], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][9], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][9], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][9], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][9], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][9], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][9], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][9], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][9], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][9], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][9], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][9], 1650);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][9], 360.000000, 360.000000, 11.000000, 1.100103);

	tuntext_p[playerid][8] = CreatePlayerTextDraw(playerid, 373.019623, 326.384369, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][8], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][8], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][8], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][8], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][8], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][8], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][8], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][8], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][8], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][8], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][8], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][8], 0);

	tuntext_p[playerid][7] = CreatePlayerTextDraw(playerid, 375.000000, 305.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][7], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][7], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][7], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][7], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][7], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][7], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][7], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][7], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][7], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][7], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][7], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][7], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][7], 1254);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][7], 173.000000, 175.000000, 17.000000, 1.183524);

	tuntext_p[playerid][6] = CreatePlayerTextDraw(playerid, 399.019623, 326.384369, "2");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][6], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][6], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][6], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][6], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][6], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][6], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][6], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][6], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][6], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][6], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][6], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][6], 0);

	tuntext_p[playerid][5] = CreatePlayerTextDraw(playerid, 401.000000, 305.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][5], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][5], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][5], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][5], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][5], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][5], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][5], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][5], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][5], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][5], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][5], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][5], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][5], 19801);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][5], 360.000000, 360.000000, 121.000000, 0.823773);

	tuntext_p[playerid][4] = CreatePlayerTextDraw(playerid, 425.019623, 326.384369, "5");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][4], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][4], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][4], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][4], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][4], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][4], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][4], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][4], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][4], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][4], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][4], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][4], 0);

	tuntext_p[playerid][3] = CreatePlayerTextDraw(playerid, 427.000000, 305.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][3], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][3], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][3], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][3], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][3], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][3], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][3], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][3], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][3], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][3], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][3], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][3], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][3], 1240);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][3], 172.000000, 169.000000, 190.000000, 1.449426);

	tuntext_p[playerid][2] = CreatePlayerTextDraw(playerid, 451.019623, 326.384369, "2");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][2], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][2], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][2], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][2], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][2], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][2], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][2], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][2], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][2], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][2], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][2], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][2], 0);

	tuntext_p[playerid][1] = CreatePlayerTextDraw(playerid, 453.000000, 305.642853, "LD_SPAC:white");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][1], 0.480000, 1.120000);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][1], 25.000000, 27.500000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][1], 1);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][1], 0x999999FF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][1], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][1], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][1], 2);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][1], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][1], 0x333333FF);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][1], 5);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][1], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][1], 0);
	PlayerTextDrawSetPreviewModel(playerid, tuntext_p[playerid][1], 1274);
	PlayerTextDrawSetPreviewRot(playerid, tuntext_p[playerid][1], 0.000000, 0.000000, 0.000000, 0.897810);

	tuntext_p[playerid][0] = CreatePlayerTextDraw(playerid, 477.019623, 326.384369, "21");
	PlayerTextDrawLetterSize(playerid, tuntext_p[playerid][0], 0.124019, 0.582627);
	PlayerTextDrawTextSize(playerid, tuntext_p[playerid][0], 1280.000000, 1280.000000);
	PlayerTextDrawAlignment(playerid, tuntext_p[playerid][0], 3);
	PlayerTextDrawColor(playerid, tuntext_p[playerid][0], 0xAAAAAAFF);
	PlayerTextDrawUseBox(playerid, tuntext_p[playerid][0], 0);
	PlayerTextDrawBoxColor(playerid, tuntext_p[playerid][0], 0x80808080);
	PlayerTextDrawSetShadow(playerid, tuntext_p[playerid][0], 0);
	PlayerTextDrawSetOutline(playerid, tuntext_p[playerid][0], 0);
	PlayerTextDrawBackgroundColor(playerid, tuntext_p[playerid][0], 0x00000000);
	PlayerTextDrawFont(playerid, tuntext_p[playerid][0], 2);
	PlayerTextDrawSetProportional(playerid, tuntext_p[playerid][0], 1);
	PlayerTextDrawSetSelectable(playerid, tuntext_p[playerid][0], 0);*/

	Govnishe[playerid][0] = CreatePlayerTextDraw(playerid, 323.000000, 163.142853, "LD_SPAC:white");

	Govnishe[playerid][1] = CreatePlayerTextDraw(playerid, 349.000000, 163.142853, "LD_SPAC:white");

	Govnishe[playerid][2] = CreatePlayerTextDraw(playerid, 375.000000, 163.142853, "LD_SPAC:white");

	Govnishe[playerid][3] = CreatePlayerTextDraw(playerid, 401.000000, 163.142853, "LD_SPAC:white");

	Govnishe[playerid][4] = CreatePlayerTextDraw(playerid, 427.000000, 163.142853, "LD_SPAC:white");

	Govnishe[playerid][5] = CreatePlayerTextDraw(playerid, 453.000000, 163.142853, "LD_SPAC:white");

	Govnishe[playerid][6] = CreatePlayerTextDraw(playerid, 323.000000, 191.642853, "LD_SPAC:white");

	Govnishe[playerid][7] = CreatePlayerTextDraw(playerid, 349.000000, 191.642853, "LD_SPAC:white");

	Govnishe[playerid][8] = CreatePlayerTextDraw(playerid, 375.000000, 191.642853, "LD_SPAC:white");

	Govnishe[playerid][9] = CreatePlayerTextDraw(playerid, 401.000000, 191.642853, "LD_SPAC:white");

	Govnishe[playerid][10] = CreatePlayerTextDraw(playerid, 427.000000, 191.642853, "LD_SPAC:white");

	Govnishe[playerid][11] = CreatePlayerTextDraw(playerid, 453.000000, 191.642853, "LD_SPAC:white");

	Govnishe[playerid][12] = CreatePlayerTextDraw(playerid, 323.000000, 220.142853, "LD_SPAC:white");

	Govnishe[playerid][13] = CreatePlayerTextDraw(playerid, 349.000000, 220.142853, "LD_SPAC:white");

	Govnishe[playerid][14] = CreatePlayerTextDraw(playerid, 375.000000, 220.142853, "LD_SPAC:white");

	Govnishe[playerid][15] = CreatePlayerTextDraw(playerid, 401.000000, 220.142853, "LD_SPAC:white");

	Govnishe[playerid][16] = CreatePlayerTextDraw(playerid, 427.000000, 220.142853, "LD_SPAC:white");

	Govnishe[playerid][17] = CreatePlayerTextDraw(playerid, 453.000000, 220.142853, "LD_SPAC:white");

	Govnishe[playerid][18] = CreatePlayerTextDraw(playerid, 323.000000, 248.642853, "LD_SPAC:white");

	Govnishe[playerid][19] = CreatePlayerTextDraw(playerid, 349.000000, 248.642853, "LD_SPAC:white");

	Govnishe[playerid][20] = CreatePlayerTextDraw(playerid, 375.000000, 248.642853, "LD_SPAC:white");

	Govnishe[playerid][21] = CreatePlayerTextDraw(playerid, 401.000000, 248.642853, "LD_SPAC:white");

	Govnishe[playerid][22] = CreatePlayerTextDraw(playerid, 427.000000, 248.642853, "LD_SPAC:white");

	Govnishe[playerid][23] = CreatePlayerTextDraw(playerid, 453.000000, 248.642853, "LD_SPAC:white");

	Govnishe[playerid][24] = CreatePlayerTextDraw(playerid, 323.000000, 277.142853, "LD_SPAC:white");

	Govnishe[playerid][25] = CreatePlayerTextDraw(playerid, 349.000000, 277.142853, "LD_SPAC:white");

	Govnishe[playerid][26] = CreatePlayerTextDraw(playerid, 375.000000, 277.142853, "LD_SPAC:white");

	Govnishe[playerid][27] = CreatePlayerTextDraw(playerid, 401.000000, 277.142853, "LD_SPAC:white");

	Govnishe[playerid][28] = CreatePlayerTextDraw(playerid, 427.000000, 277.142853, "LD_SPAC:white");

	Govnishe[playerid][29] = CreatePlayerTextDraw(playerid, 453.000000, 277.142853, "LD_SPAC:white");

	Govnishe[playerid][30] = CreatePlayerTextDraw(playerid, 323.000000, 305.642853, "LD_SPAC:white");

	Govnishe[playerid][31] = CreatePlayerTextDraw(playerid, 349.000000, 305.642853, "LD_SPAC:white");

	Govnishe[playerid][32] = CreatePlayerTextDraw(playerid, 375.000000, 305.642853, "LD_SPAC:white");

	Govnishe[playerid][33] = CreatePlayerTextDraw(playerid, 401.000000, 305.642853, "LD_SPAC:white");

	Govnishe[playerid][34] = CreatePlayerTextDraw(playerid, 427.000000, 305.642853, "LD_SPAC:white");

	Govnishe[playerid][35] = CreatePlayerTextDraw(playerid, 453.000000, 305.642853, "LD_SPAC:white");
	for(new i = 0; i < 36; i++)
	{
		PlayerTextDrawLetterSize(playerid, Govnishe[playerid][i], 0.480000, 1.120000);
		PlayerTextDrawTextSize(playerid, Govnishe[playerid][i], 25.000000, 27.500000);
		PlayerTextDrawAlignment(playerid, Govnishe[playerid][i], 1);
		PlayerTextDrawColor(playerid, Govnishe[playerid][i], 0x999999FF);
		PlayerTextDrawUseBox(playerid, Govnishe[playerid][i], 0);
		PlayerTextDrawBoxColor(playerid, Govnishe[playerid][i], 0x80808080);
		PlayerTextDrawSetShadow(playerid, Govnishe[playerid][i], 2);
		PlayerTextDrawSetOutline(playerid, Govnishe[playerid][i], 0);
		PlayerTextDrawBackgroundColor(playerid, Govnishe[playerid][i], 0x333333FF);
		PlayerTextDrawFont(playerid, Govnishe[playerid][i], 5);
		PlayerTextDrawSetProportional(playerid, Govnishe[playerid][i], 1);
		PlayerTextDrawSetSelectable(playerid, Govnishe[playerid][i], 0);
    	}
	GovnisheKletki[playerid][0] = CreatePlayerTextDraw(playerid, 347.019623, 183.884384, "");//1

	GovnisheKletki[playerid][1] = CreatePlayerTextDraw(playerid, 373.019623, 183.884384, "");//2

	GovnisheKletki[playerid][2] = CreatePlayerTextDraw(playerid, 399.019623, 183.884384, "");//3

	GovnisheKletki[playerid][3] = CreatePlayerTextDraw(playerid, 425.019623, 183.884384, "");//4

	GovnisheKletki[playerid][4] = CreatePlayerTextDraw(playerid, 451.019623, 183.884384, "");//5

	GovnisheKletki[playerid][5] = CreatePlayerTextDraw(playerid, 477.019623, 183.884384, "");//6

	GovnisheKletki[playerid][6] = CreatePlayerTextDraw(playerid, 347.019623, 212.384384, "");//7

	GovnisheKletki[playerid][7] = CreatePlayerTextDraw(playerid, 373.019623, 212.384384, "");//8

	GovnisheKletki[playerid][8] = CreatePlayerTextDraw(playerid, 399.019623, 212.384384, "");//9

	GovnisheKletki[playerid][9] = CreatePlayerTextDraw(playerid, 425.019623, 212.384384, "");//10

	GovnisheKletki[playerid][10] = CreatePlayerTextDraw(playerid, 451.019623, 212.384384, "");//11

	GovnisheKletki[playerid][11] = CreatePlayerTextDraw(playerid, 477.019623, 212.384384, "");//12

	GovnisheKletki[playerid][12] = CreatePlayerTextDraw(playerid, 347.019623, 240.884384, "");//13

	GovnisheKletki[playerid][13] = CreatePlayerTextDraw(playerid, 373.019623, 240.884384, "");//14

	GovnisheKletki[playerid][14] = CreatePlayerTextDraw(playerid, 399.019623, 240.884384, "");//15

	GovnisheKletki[playerid][15] = CreatePlayerTextDraw(playerid, 425.019623, 240.884384, "");//16

	GovnisheKletki[playerid][16] = CreatePlayerTextDraw(playerid, 451.019623, 240.884384, "");//17

	GovnisheKletki[playerid][17] = CreatePlayerTextDraw(playerid, 477.019623, 240.884384, "");//18

	GovnisheKletki[playerid][18] = CreatePlayerTextDraw(playerid, 347.019623, 269.384369, "");//19

	GovnisheKletki[playerid][19] = CreatePlayerTextDraw(playerid, 373.019623, 269.384369, "");//20

	GovnisheKletki[playerid][20] = CreatePlayerTextDraw(playerid, 399.019623, 269.384369, "");//21

	GovnisheKletki[playerid][21] = CreatePlayerTextDraw(playerid, 425.019623, 269.384369, "");//22

	GovnisheKletki[playerid][22] = CreatePlayerTextDraw(playerid, 451.019623, 269.384369, "");//23

	GovnisheKletki[playerid][23] = CreatePlayerTextDraw(playerid, 477.019623, 269.384369, "");//24

	GovnisheKletki[playerid][24] = CreatePlayerTextDraw(playerid, 347.019623, 297.884369, "");//25

	GovnisheKletki[playerid][25] = CreatePlayerTextDraw(playerid, 373.019623, 297.884369, "");//26

	GovnisheKletki[playerid][26] = CreatePlayerTextDraw(playerid, 399.019623, 297.884369, "");//27

	GovnisheKletki[playerid][27] = CreatePlayerTextDraw(playerid, 425.019623, 297.884369, "");//28

	GovnisheKletki[playerid][28] = CreatePlayerTextDraw(playerid, 451.019623, 297.884369, "");//29


	GovnisheKletki[playerid][29] = CreatePlayerTextDraw(playerid, 477.019623, 297.884369, "");//30

	GovnisheKletki[playerid][30] = CreatePlayerTextDraw(playerid, 347.019623, 326.384369, "");//31

	GovnisheKletki[playerid][31] = CreatePlayerTextDraw(playerid, 373.019623, 326.384369, "");//32

	GovnisheKletki[playerid][32] = CreatePlayerTextDraw(playerid, 399.019623, 326.384369, "");//33

	GovnisheKletki[playerid][33] = CreatePlayerTextDraw(playerid, 425.019623, 326.384369, "");//34

	GovnisheKletki[playerid][34] = CreatePlayerTextDraw(playerid, 451.019623, 326.384369, "");//35

	GovnisheKletki[playerid][35] = CreatePlayerTextDraw(playerid, 477.019623, 326.384369, "");//36
	for(new i = 0; i < 36; i++)
	{
		PlayerTextDrawLetterSize(playerid, GovnisheKletki[playerid][i], 0.124019, 0.582627);
		PlayerTextDrawTextSize(playerid, GovnisheKletki[playerid][i], 1280.000000, 1280.000000);
		PlayerTextDrawAlignment(playerid, GovnisheKletki[playerid][i], 3);
		PlayerTextDrawColor(playerid, GovnisheKletki[playerid][i], 0xAAAAAAFF);
		PlayerTextDrawUseBox(playerid, GovnisheKletki[playerid][i], 0);
		PlayerTextDrawBoxColor(playerid, GovnisheKletki[playerid][i], 0x80808080);
		PlayerTextDrawSetShadow(playerid, GovnisheKletki[playerid][i], 0);
		PlayerTextDrawSetOutline(playerid, GovnisheKletki[playerid][i], 0);
		PlayerTextDrawBackgroundColor(playerid, GovnisheKletki[playerid][i], 0x00000000);
		PlayerTextDrawFont(playerid, GovnisheKletki[playerid][i], 2);
		PlayerTextDrawSetProportional(playerid, GovnisheKletki[playerid][i], 1);
		PlayerTextDrawSetSelectable(playerid, GovnisheKletki[playerid][i], 0);
	}