		pizdecpolniy[playerid][26] = CreatePlayerTextDraw(playerid, 320.250000, 138.642853, "usebox");
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][26], 0.000000, 26.907150);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][26], 180.000000, 0.000000);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][26], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][26], 0xE1E1E1FF);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][26], 1);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][26], 0x111111FF);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][26], 2);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][26], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][26], 0x000000FF);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][26], 0);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][26], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][26], 0);

		if(PlayerInfo[playerid][pLanguage] == 0) pizdecpolniy[playerid][25] = CreatePlayerTextDraw(playerid, 187.500000, 143.659897, "TRASH");
		else pizdecpolniy[playerid][25] = CreatePlayerTextDraw(playerid, 187.500000, 143.659897, FixText("Ã”—Œ– ¿"));
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][25], 0.188333, 1.056592);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][25], 1280.000000, 1280.000000);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][25], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][25], 0xFFFFFFFF);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][25], 0);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][25], 0x80808080);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][25], 0);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][25], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][25], 0x00000000);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][25], 2);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][25], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][25], 0);

		pizdecpolniy[playerid][24] = CreatePlayerTextDraw(playerid, 320.250000, 162.242859, "usebox");
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][24], 0.000000, -0.214150);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][24], 180.000000, 0.000000);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][24], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][24], 0xE1E1E1FF);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][24], 1);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][24], PlayerInfo[playerid][pColorInv]);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][24], 2);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][24], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][24], 0x000000FF);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][24], 0);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][24], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][24], 0);

		pizdecpolniy[playerid][23] = CreatePlayerTextDraw(playerid, 238.050003, 351.242859, "LD_BEAT:chit");
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][23], 0.480000, 1.120000);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][23], 5.100000, 5.900000);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][23], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][23], PlayerInfo[playerid][pColorInv]);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][23], 0);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][23], 0x80808080);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][23], 2);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][23], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][23], 0x000000FF);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][23], 4);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][23], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][23], 0);

		pizdecpolniy[playerid][22] = CreatePlayerTextDraw(playerid, 244.150009, 351.242859, "LD_BEAT:chit");
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][22], 0.480000, 1.120000);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][22], 5.100000, 5.900000);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][22], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][22], 0x333333FF);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][22], 0);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][22], 0x80808080);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][22], 2);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][22], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][22], 0x000000FF);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][22], 4);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][22], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][22], 0);

		pizdecpolniy[playerid][21] = CreatePlayerTextDraw(playerid, 250.250000, 351.242859, "LD_BEAT:chit");
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][21], 0.480000, 1.120000);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][21], 5.100000, 5.900000);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][21], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][21], 0x333333FF);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][21], 0);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][21], 0x80808080);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][21], 2);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][21], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][21], 0x000000FF);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][21], 4);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][21], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][21], 0);

		pizdecpolniy[playerid][20] = CreatePlayerTextDraw(playerid, 256.350006, 351.242859, "LD_BEAT:chit");
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][20], 0.480000, 1.120000);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][20], 5.100000, 5.900000);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][20], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][20], 0x333333FF);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][20], 0);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][20], 0x80808080);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][20], 2);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][20], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][20], 0x000000FF);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][20], 4);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][20], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][20], 0);

		pizdecpolniy[playerid][18] = CreatePlayerTextDraw(playerid, 185.677078, 364.693237, "");
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][18], 0.235416, 1.320740);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][18], 185.677078, 13.207399);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][18], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][18], 0x67B355FF);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][18], 0);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][18], 0x80808080);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][18], 0);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][18], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][18], 0x00000000);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][18], 2);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][18], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][18], 1);

		pizdecpolniy[playerid][17] = CreatePlayerTextDraw(playerid, 485.250000, 138.642853, "usebox");
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][17], 0.000000, 26.907150);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][17], 318.500000, 0.000000);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][17], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][17], 0xE1E1E1FF);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][17], 1);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][17], 0x111111FF);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][17], 2);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][17], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][17], 0x000000FF);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][17], 0);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][17], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][17], 0);

		if(PlayerInfo[playerid][pLanguage] == 0) pizdecpolniy[playerid][16] = CreatePlayerTextDraw(playerid, 326.000000, 143.659897, "INVENTORY");
		else pizdecpolniy[playerid][16] = CreatePlayerTextDraw(playerid, 326.000000, 143.659897, FixText("»Õ¬≈Õ“¿–‹"));
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][16], 0.188333, 1.056592);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][16], 1280.000000, 1280.000000);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][16], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][16], 0xFFFFFFFF);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][16], 0);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][16], 0x80808080);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][16], 0);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][16], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][16], 0x00000000);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][16], 2);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][16], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][16], 0);

		pizdecpolniy[playerid][15] = CreatePlayerTextDraw(playerid, 485.250000, 162.242859, "usebox");
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][15], 0.000000, -0.214150);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][15], 318.500000, 0.000000);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][15], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][15], 0xE1E1E1FF);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][15], 1);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][15], PlayerInfo[playerid][pColorInv]);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][15], 2);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][15], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][15], 0x000000FF);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][15], 0);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][15], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][15], 0);

		pizdecpolniy[playerid][14] = CreatePlayerTextDraw(playerid, 395.899994, 351.242859, "LD_BEAT:chit");
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][14], 0.480000, 1.120000);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][14], 5.100000, 5.900000);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][14], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][14], PlayerInfo[playerid][pColorInv]);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][14], 0);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][14], 0x80808080);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][14], 2);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][14], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][14], 0x000000FF);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][14], 4);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][14], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][14], 1);

		pizdecpolniy[playerid][19] = CreatePlayerTextDraw(playerid, 402.000000, 351.242859, "LD_BEAT:chit");
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][19], 0.480000, 1.120000);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][19], 5.100000, 5.900000);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][19], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][19], 0x333333FF);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][19], 0);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][19], 0x80808080);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][19], 2);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][19], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][19], 0x000000FF);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][19], 4);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][19], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][19], 1);

		pizdecpolniy[playerid][12] = CreatePlayerTextDraw(playerid, 438.500000, 360.142853, "LD_SPAC:white");
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][12], 0.480000, 1.120000);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][12], 42.500000, 19.666666);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][12], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][12], PlayerInfo[playerid][pColorInv]);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][12], 0);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][12], 0x80808080);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][12], 2);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][12], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][12], 0x000000FF);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][12], 4);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][12], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][12], 1);

		if(PlayerInfo[playerid][pLanguage] == 0) pizdecpolniy[playerid][11] = CreatePlayerTextDraw(playerid, 459.750000, 364.693237, "CLOSE");
		else pizdecpolniy[playerid][11] = CreatePlayerTextDraw(playerid, 459.750000, 364.693237, FixText("«¿ –€“‹"));
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][11], 0.188333, 1.056592);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][11], 1280.000000, 1280.000000);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][11], 2);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][11], 0xFFFFFFFF);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][11], 0);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][11], 0x80808080);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][11], 0);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][11], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][11], 0x00000000);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][11], 2);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][11], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][11], 0);

		pizdecpolniy[playerid][2] = CreatePlayerTextDraw(playerid, 323.000000, 360.142853, "LD_SPAC:white");
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][2], 0.480000, 1.120000);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][2], 42.500000, 19.666666);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][2], 1);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][2], PlayerInfo[playerid][pColorInv]);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][2], 0);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][2], 0x80808080);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][2], 2);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][2], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][2], 0x000000FF);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][2], 4);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][2], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][2], 1);

		if(PlayerInfo[playerid][pLanguage] == 0) pizdecpolniy[playerid][0] = CreatePlayerTextDraw(playerid, 344.250000, 365.749817, "INVENTORY");
		else pizdecpolniy[playerid][0] = CreatePlayerTextDraw(playerid, 344.250000, 365.749817, FixText("»Õ¬≈Õ“¿–‹"));
		PlayerTextDrawLetterSize(playerid, pizdecpolniy[playerid][0], 0.150666, 0.845274);
		PlayerTextDrawTextSize(playerid, pizdecpolniy[playerid][0], 1280.000000, 1280.000000);
		PlayerTextDrawAlignment(playerid, pizdecpolniy[playerid][0], 2);
		PlayerTextDrawColor(playerid, pizdecpolniy[playerid][0], 0xFFFFFFFF);
		PlayerTextDrawUseBox(playerid, pizdecpolniy[playerid][0], 0);
		PlayerTextDrawBoxColor(playerid, pizdecpolniy[playerid][0], 0x80808080);
		PlayerTextDrawSetShadow(playerid, pizdecpolniy[playerid][0], 0);
		PlayerTextDrawSetOutline(playerid, pizdecpolniy[playerid][0], 0);
		PlayerTextDrawBackgroundColor(playerid, pizdecpolniy[playerid][0], 0x00000000);
		PlayerTextDrawFont(playerid, pizdecpolniy[playerid][0], 2);
		PlayerTextDrawSetProportional(playerid, pizdecpolniy[playerid][0], 1);
		PlayerTextDrawSetSelectable(playerid, pizdecpolniy[playerid][0], 0);

		TrashSlot[playerid][0] = CreatePlayerTextDraw(playerid, 184.500000, 164.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][1] = CreatePlayerTextDraw(playerid, 211.000000, 164.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][2] = CreatePlayerTextDraw(playerid, 237.500000, 164.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][3] = CreatePlayerTextDraw(playerid, 264.000000, 164.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][4] = CreatePlayerTextDraw(playerid, 290.500000, 164.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][5] = CreatePlayerTextDraw(playerid, 184.500000, 195.242859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][6] = CreatePlayerTextDraw(playerid, 211.000000, 195.242859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][7] = CreatePlayerTextDraw(playerid, 237.500000, 195.242859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][8] = CreatePlayerTextDraw(playerid, 264.000000, 195.242859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][9] = CreatePlayerTextDraw(playerid, 290.500000, 195.242859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][10] = CreatePlayerTextDraw(playerid, 184.500000, 225.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][11] = CreatePlayerTextDraw(playerid, 211.000000, 225.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][12] = CreatePlayerTextDraw(playerid, 237.500000, 225.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][13] = CreatePlayerTextDraw(playerid, 264.000000, 225.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][14] = CreatePlayerTextDraw(playerid, 290.500000, 225.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][15] = CreatePlayerTextDraw(playerid, 184.500000, 256.242859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][16] = CreatePlayerTextDraw(playerid, 211.000000, 256.242859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][17] = CreatePlayerTextDraw(playerid, 237.500000, 256.242859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][18] = CreatePlayerTextDraw(playerid, 264.000000, 256.242859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][19] = CreatePlayerTextDraw(playerid, 290.500000, 256.242859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][20] = CreatePlayerTextDraw(playerid, 184.500000, 286.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][21] = CreatePlayerTextDraw(playerid, 211.000000, 286.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][22] = CreatePlayerTextDraw(playerid, 237.500000, 286.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][23] = CreatePlayerTextDraw(playerid, 264.000000, 286.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][24] = CreatePlayerTextDraw(playerid, 290.500000, 286.742859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][25] = CreatePlayerTextDraw(playerid, 184.500000, 317.242859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][26] = CreatePlayerTextDraw(playerid, 211.000000, 317.242859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][27] = CreatePlayerTextDraw(playerid, 237.500000, 317.242859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][28] = CreatePlayerTextDraw(playerid, 264.000000, 317.242859, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlot[playerid][29] = CreatePlayerTextDraw(playerid, 290.500000, 317.242859, "LD_SPAC:white");
		for(new i = 0; i < 30; i++)
		{
		    PlayerTextDrawLetterSize(playerid, TrashSlot[playerid][i], 0.480000, 1.120000);
		    PlayerTextDrawTextSize(playerid, TrashSlot[playerid][i], 25.500000, 29.500000);
		    PlayerTextDrawAlignment(playerid, TrashSlot[playerid][i], 1);
		    PlayerTextDrawColor(playerid, TrashSlot[playerid][i], 0xFFFFFFFF);
		    PlayerTextDrawUseBox(playerid, TrashSlot[playerid][i], 0);
		    PlayerTextDrawBoxColor(playerid, TrashSlot[playerid][i], 0x80808080);
		    PlayerTextDrawSetShadow(playerid, TrashSlot[playerid][i], 2);
		    PlayerTextDrawSetOutline(playerid, TrashSlot[playerid][i], 0);
		    PlayerTextDrawBackgroundColor(playerid, TrashSlot[playerid][i], 0x333333FF);
		    PlayerTextDrawFont(playerid, TrashSlot[playerid][i], 5);
		    PlayerTextDrawSetProportional(playerid, TrashSlot[playerid][i], 1);
		    PlayerTextDrawSetSelectable(playerid, TrashSlot[playerid][i], 1);
		}
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][0] = CreatePlayerTextDraw(playerid, 209.000000, 187.826187, "LD_SPAC:white");
		TrashSlotKol[playerid][1] = CreatePlayerTextDraw(playerid, 235.500000, 187.826187, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][2] = CreatePlayerTextDraw(playerid, 262.000000, 187.826187, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][3] = CreatePlayerTextDraw(playerid, 288.500000, 187.826187, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][4] = CreatePlayerTextDraw(playerid, 315.000000, 187.826187, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][5] = CreatePlayerTextDraw(playerid, 209.000000, 218.326187, "LD_SPAC:white");
		TrashSlotKol[playerid][6] = CreatePlayerTextDraw(playerid, 235.500000, 218.326187, "LD_SPAC:white");
		TrashSlotKol[playerid][7] = CreatePlayerTextDraw(playerid, 262.000000, 218.326187, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][8] = CreatePlayerTextDraw(playerid, 288.500000, 218.326187, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][9] = CreatePlayerTextDraw(playerid, 315.000000, 218.326187, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][10] = CreatePlayerTextDraw(playerid, 209.000000, 248.826187, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][11] = CreatePlayerTextDraw(playerid, 235.500000, 248.826187, "LD_SPAC:white");
		TrashSlotKol[playerid][12] = CreatePlayerTextDraw(playerid,  262.000000, 248.826187, "LD_SPAC:white");
		TrashSlotKol[playerid][13] = CreatePlayerTextDraw(playerid, 288.500000, 248.826187, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][14] = CreatePlayerTextDraw(playerid, 315.000000, 248.826187, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][15] = CreatePlayerTextDraw(playerid, 209.000000, 279.326202, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][16] = CreatePlayerTextDraw(playerid, 235.500000, 279.326202, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][17] = CreatePlayerTextDraw(playerid, 262.000000, 279.326202, "LD_SPAC:white");
		TrashSlotKol[playerid][18] = CreatePlayerTextDraw(playerid, 288.500000, 279.326202, "LD_SPAC:white");
		TrashSlotKol[playerid][19] = CreatePlayerTextDraw(playerid, 315.000000, 279.326202, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][20] = CreatePlayerTextDraw(playerid, 209.000000, 309.826202, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][21] = CreatePlayerTextDraw(playerid, 235.500000, 309.826202, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][22] = CreatePlayerTextDraw(playerid, 262.000000, 309.826202, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][23] = CreatePlayerTextDraw(playerid, 288.500000, 309.826202, "LD_SPAC:white");
		TrashSlotKol[playerid][24] = CreatePlayerTextDraw(playerid, 315.000000, 309.826202, "LD_SPAC:white");
		TrashSlotKol[playerid][25] = CreatePlayerTextDraw(playerid, 209.000000, 340.326202, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][26] = CreatePlayerTextDraw(playerid, 235.500000, 340.326202, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][27] = CreatePlayerTextDraw(playerid, 262.000000, 340.326202, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][28] = CreatePlayerTextDraw(playerid, 288.500000, 340.326202, "LD_SPAC:white");
		///////////////////////////////////////////////////////////////////////////////////////////////
		TrashSlotKol[playerid][29] = CreatePlayerTextDraw(playerid, 315.000000, 340.326202, "LD_SPAC:white");
		for(new i = 0; i < 30; i++)
		{
		    PlayerTextDrawLetterSize(playerid, TrashSlotKol[playerid][i], 0.126499, 0.625000);
			PlayerTextDrawTextSize(playerid, TrashSlotKol[playerid][i], 1280.000000, 1280.000000);
			PlayerTextDrawAlignment(playerid, TrashSlotKol[playerid][i], 3);
			PlayerTextDrawColor(playerid, TrashSlotKol[playerid][i], 0xAAAAAAFF);
			PlayerTextDrawUseBox(playerid, TrashSlotKol[playerid][i], 0);
			PlayerTextDrawBoxColor(playerid, TrashSlotKol[playerid][i], 0x80808080);
			PlayerTextDrawSetShadow(playerid, TrashSlotKol[playerid][i], 0);
			PlayerTextDrawSetOutline(playerid, TrashSlotKol[playerid][i], 1);
			PlayerTextDrawBackgroundColor(playerid, TrashSlotKol[playerid][i], 0x00000000);
			PlayerTextDrawFont(playerid, TrashSlotKol[playerid][i], 2);
			PlayerTextDrawSetProportional(playerid, TrashSlotKol[playerid][i], 1);
			PlayerTextDrawSetSelectable(playerid, TrashSlotKol[playerid][i], 0);
		}
		///////////////////////////////////////////////////////////////////////////////////////////////
		Govnishe[playerid][0] = CreatePlayerTextDraw(playerid, 323.000000, 164.742859, "LD_SPAC:white");

		Govnishe[playerid][1] = CreatePlayerTextDraw(playerid, 349.500000, 164.7428598, "LD_SPAC:white");

		Govnishe[playerid][2] = CreatePlayerTextDraw(playerid, 376.000000, 164.742859, "LD_SPAC:white");

		Govnishe[playerid][3] = CreatePlayerTextDraw(playerid, 402.500000, 164.742859, "LD_SPAC:white");

		Govnishe[playerid][4] = CreatePlayerTextDraw(playerid, 429.000000, 164.742859, "LD_SPAC:white");

		Govnishe[playerid][5] = CreatePlayerTextDraw(playerid, 455.500000, 164.742859, "LD_SPAC:white");

		Govnishe[playerid][6] = CreatePlayerTextDraw(playerid, 323.000000, 195.242859, "LD_SPAC:white");

		Govnishe[playerid][7] = CreatePlayerTextDraw(playerid, 349.500000, 195.242859, "LD_SPAC:white");

		Govnishe[playerid][8] = CreatePlayerTextDraw(playerid, 376.000000, 195.242859, "LD_SPAC:white");

		Govnishe[playerid][9] = CreatePlayerTextDraw(playerid, 402.500000, 195.242859, "LD_SPAC:white");

		Govnishe[playerid][10] = CreatePlayerTextDraw(playerid, 429.000000, 195.242859, "LD_SPAC:white");

		Govnishe[playerid][11] = CreatePlayerTextDraw(playerid, 455.500000, 195.242859, "LD_SPAC:white");

		Govnishe[playerid][12] = CreatePlayerTextDraw(playerid, 323.000000, 225.742859, "LD_SPAC:white");

		Govnishe[playerid][13] = CreatePlayerTextDraw(playerid, 349.500000, 225.742859, "LD_SPAC:white");

		Govnishe[playerid][14] = CreatePlayerTextDraw(playerid, 376.000000, 225.742859, "LD_SPAC:white");

		Govnishe[playerid][15] = CreatePlayerTextDraw(playerid, 402.500000, 225.742859, "LD_SPAC:white");

		Govnishe[playerid][16] = CreatePlayerTextDraw(playerid, 429.000000, 225.742859, "LD_SPAC:white");

		Govnishe[playerid][17] = CreatePlayerTextDraw(playerid, 455.500000, 225.742859, "LD_SPAC:white");

		Govnishe[playerid][18] = CreatePlayerTextDraw(playerid, 323.000000, 256.242859, "LD_SPAC:white");

		Govnishe[playerid][19] = CreatePlayerTextDraw(playerid, 349.500000, 256.242859, "LD_SPAC:white");



		Govnishe[playerid][20] = CreatePlayerTextDraw(playerid, 376.000000, 256.242859, "LD_SPAC:white");

		Govnishe[playerid][21] = CreatePlayerTextDraw(playerid, 402.500000, 256.242859, "LD_SPAC:white");

		Govnishe[playerid][22] = CreatePlayerTextDraw(playerid, 429.000000, 256.242859, "LD_SPAC:white");

		Govnishe[playerid][23] = CreatePlayerTextDraw(playerid, 455.500000, 256.242859, "LD_SPAC:white");

		Govnishe[playerid][24] = CreatePlayerTextDraw(playerid, 323.000000, 286.742859, "LD_SPAC:white");

		Govnishe[playerid][25] = CreatePlayerTextDraw(playerid, 349.500000, 286.742859, "LD_SPAC:white");

		Govnishe[playerid][26] = CreatePlayerTextDraw(playerid, 376.000000, 286.742859, "LD_SPAC:white");

		Govnishe[playerid][27] = CreatePlayerTextDraw(playerid, 402.500000, 286.742859, "LD_SPAC:white");

		Govnishe[playerid][28] = CreatePlayerTextDraw(playerid, 429.000000, 286.742859, "LD_SPAC:white");


		Govnishe[playerid][29] = CreatePlayerTextDraw(playerid, 455.500000, 286.742859, "LD_SPAC:white");

		Govnishe[playerid][30] = CreatePlayerTextDraw(playerid, 323.000000, 317.242859, "LD_SPAC:white");

		Govnishe[playerid][31] = CreatePlayerTextDraw(playerid, 349.500000, 317.242859, "LD_SPAC:white");

		Govnishe[playerid][32] = CreatePlayerTextDraw(playerid, 376.000000, 317.242859, "LD_SPAC:white");

		Govnishe[playerid][33] = CreatePlayerTextDraw(playerid, 402.500000, 317.242859, "LD_SPAC:white");

		Govnishe[playerid][34] = CreatePlayerTextDraw(playerid, 429.000000, 317.242859, "LD_SPAC:white");

		Govnishe[playerid][35] = CreatePlayerTextDraw(playerid, 455.500000, 317.242859, "LD_SPAC:white");

		Govnishe[playerid][36] = CreatePlayerTextDraw(playerid, 323.000000, 164.742859, "LD_SPAC:white");

		Govnishe[playerid][37] = CreatePlayerTextDraw(playerid, 349.500000, 164.7428598, "LD_SPAC:white");

		Govnishe[playerid][38] = CreatePlayerTextDraw(playerid, 376.000000, 164.742859, "LD_SPAC:white");

		Govnishe[playerid][39] = CreatePlayerTextDraw(playerid, 402.500000, 164.742859, "LD_SPAC:white");

		Govnishe[playerid][40] = CreatePlayerTextDraw(playerid, 429.000000, 164.742859, "LD_SPAC:white");

		Govnishe[playerid][41] = CreatePlayerTextDraw(playerid, 455.500000, 164.742859, "LD_SPAC:white");

		Govnishe[playerid][42] = CreatePlayerTextDraw(playerid, 323.000000, 195.242859, "LD_SPAC:white");

		Govnishe[playerid][43] = CreatePlayerTextDraw(playerid, 349.500000, 195.242859, "LD_SPAC:white");

		Govnishe[playerid][44] = CreatePlayerTextDraw(playerid, 376.000000, 195.242859, "LD_SPAC:white");

		Govnishe[playerid][45] = CreatePlayerTextDraw(playerid, 402.500000, 195.242859, "LD_SPAC:white");

		Govnishe[playerid][46] = CreatePlayerTextDraw(playerid, 429.000000, 195.242859, "LD_SPAC:white");

		Govnishe[playerid][47] = CreatePlayerTextDraw(playerid, 455.500000, 195.242859, "LD_SPAC:white");

		Govnishe[playerid][48] = CreatePlayerTextDraw(playerid, 323.000000, 225.742859, "LD_SPAC:white");

		Govnishe[playerid][49] = CreatePlayerTextDraw(playerid, 349.500000, 225.742859, "LD_SPAC:white");

		Govnishe[playerid][50] = CreatePlayerTextDraw(playerid, 376.000000, 225.742859, "LD_SPAC:white");

		Govnishe[playerid][51] = CreatePlayerTextDraw(playerid, 402.500000, 225.742859, "LD_SPAC:white");

		Govnishe[playerid][52] = CreatePlayerTextDraw(playerid, 429.000000, 225.742859, "LD_SPAC:white");

		Govnishe[playerid][53] = CreatePlayerTextDraw(playerid, 455.500000, 225.742859, "LD_SPAC:white");

		Govnishe[playerid][54] = CreatePlayerTextDraw(playerid, 323.000000, 256.242859, "LD_SPAC:white");

		Govnishe[playerid][55] = CreatePlayerTextDraw(playerid, 349.500000, 256.242859, "LD_SPAC:white");



		Govnishe[playerid][56] = CreatePlayerTextDraw(playerid, 376.000000, 256.242859, "LD_SPAC:white");

		Govnishe[playerid][57] = CreatePlayerTextDraw(playerid, 402.500000, 256.242859, "LD_SPAC:white");

		Govnishe[playerid][58] = CreatePlayerTextDraw(playerid, 429.000000, 256.242859, "LD_SPAC:white");

		Govnishe[playerid][59] = CreatePlayerTextDraw(playerid, 455.500000, 256.242859, "LD_SPAC:white");

		Govnishe[playerid][60] = CreatePlayerTextDraw(playerid, 323.000000, 286.742859, "LD_SPAC:white");

		Govnishe[playerid][61] = CreatePlayerTextDraw(playerid, 349.500000, 286.742859, "LD_SPAC:white");

		Govnishe[playerid][62] = CreatePlayerTextDraw(playerid, 376.000000, 286.742859, "LD_SPAC:white");

		Govnishe[playerid][63] = CreatePlayerTextDraw(playerid, 402.500000, 286.742859, "LD_SPAC:white");

		Govnishe[playerid][64] = CreatePlayerTextDraw(playerid, 429.000000, 286.742859, "LD_SPAC:white");


		Govnishe[playerid][65] = CreatePlayerTextDraw(playerid, 455.500000, 286.742859, "LD_SPAC:white");

		Govnishe[playerid][66] = CreatePlayerTextDraw(playerid, 323.000000, 317.242859, "LD_SPAC:white");

		Govnishe[playerid][67] = CreatePlayerTextDraw(playerid, 349.500000, 317.242859, "LD_SPAC:white");

		Govnishe[playerid][68] = CreatePlayerTextDraw(playerid, 376.000000, 317.242859, "LD_SPAC:white");

		Govnishe[playerid][69] = CreatePlayerTextDraw(playerid, 402.500000, 317.242859, "LD_SPAC:white");

		Govnishe[playerid][70] = CreatePlayerTextDraw(playerid, 429.000000, 317.242859, "LD_SPAC:white");

		Govnishe[playerid][71] = CreatePlayerTextDraw(playerid, 455.500000, 317.242859, "LD_SPAC:white");

		for(new i = 0; i < 72; i++)
		{
		    PlayerTextDrawLetterSize(playerid, Govnishe[playerid][i], 0.480000, 1.120000);
		    PlayerTextDrawTextSize(playerid, Govnishe[playerid][i], 25.500000, 29.500000);
		    PlayerTextDrawAlignment(playerid, Govnishe[playerid][i], 1);
		    PlayerTextDrawColor(playerid, Govnishe[playerid][i], 0xFFFFFFFF);
		    PlayerTextDrawUseBox(playerid, Govnishe[playerid][i], 0);
		    PlayerTextDrawBoxColor(playerid, Govnishe[playerid][i], 0x80808080);
		    PlayerTextDrawSetShadow(playerid, Govnishe[playerid][i], 2);
		    PlayerTextDrawSetOutline(playerid, Govnishe[playerid][i], 0);
		    PlayerTextDrawBackgroundColor(playerid, Govnishe[playerid][i], 0x333333FF);
		    PlayerTextDrawFont(playerid, Govnishe[playerid][i], 5);
		    PlayerTextDrawSetProportional(playerid, Govnishe[playerid][i], 1);
		    PlayerTextDrawSetSelectable(playerid, Govnishe[playerid][i], 1);
	    }
	    GovnisheKletki[playerid][0] = CreatePlayerTextDraw(playerid, 347.500000, 187.826187, "");

		GovnisheKletki[playerid][1] = CreatePlayerTextDraw(playerid, 374.000000, 187.826187, "");

		GovnisheKletki[playerid][2] = CreatePlayerTextDraw(playerid, 400.500000, 187.826187, "");

		GovnisheKletki[playerid][3] = CreatePlayerTextDraw(playerid, 427.000000, 187.826187, "");

		GovnisheKletki[playerid][4] = CreatePlayerTextDraw(playerid, 453.500000, 187.826187, "");

		GovnisheKletki[playerid][5] = CreatePlayerTextDraw(playerid, 480.000000, 187.826187, "");

		GovnisheKletki[playerid][6] = CreatePlayerTextDraw(playerid, 347.500000, 218.326187, "");

		GovnisheKletki[playerid][7] = CreatePlayerTextDraw(playerid, 374.000000, 218.326187, "");

		GovnisheKletki[playerid][8] = CreatePlayerTextDraw(playerid, 400.500000, 218.326187, "");

		GovnisheKletki[playerid][9] = CreatePlayerTextDraw(playerid, 427.000000, 218.326187, "");

		GovnisheKletki[playerid][10] = CreatePlayerTextDraw(playerid, 453.500000, 218.326187, "");

		GovnisheKletki[playerid][11] = CreatePlayerTextDraw(playerid, 480.000000, 218.326187, "");

		GovnisheKletki[playerid][12] = CreatePlayerTextDraw(playerid, 347.500000, 248.826187, "");

		GovnisheKletki[playerid][13] = CreatePlayerTextDraw(playerid, 374.000000, 248.826187, "");

		GovnisheKletki[playerid][14] = CreatePlayerTextDraw(playerid, 400.500000, 248.826187, "");

		GovnisheKletki[playerid][15] = CreatePlayerTextDraw(playerid, 427.000000, 248.826187, "");

		GovnisheKletki[playerid][16] = CreatePlayerTextDraw(playerid, 453.500000, 248.826187, "");

		GovnisheKletki[playerid][17] = CreatePlayerTextDraw(playerid, 480.000000, 248.826187, "");

		GovnisheKletki[playerid][18] = CreatePlayerTextDraw(playerid, 347.500000, 279.326202, "");

		GovnisheKletki[playerid][19] = CreatePlayerTextDraw(playerid, 374.000000, 279.326202, "");



		GovnisheKletki[playerid][20] = CreatePlayerTextDraw(playerid, 400.500000, 279.326202, "");

		GovnisheKletki[playerid][21] = CreatePlayerTextDraw(playerid, 427.000000, 279.326202, "");

		GovnisheKletki[playerid][22] = CreatePlayerTextDraw(playerid, 453.500000, 279.326202, "");

		GovnisheKletki[playerid][23] = CreatePlayerTextDraw(playerid, 480.000000, 279.326202, "");

		GovnisheKletki[playerid][24] = CreatePlayerTextDraw(playerid, 347.500000, 309.826202, "");

		GovnisheKletki[playerid][25] = CreatePlayerTextDraw(playerid, 374.000000, 309.826202, "");

		GovnisheKletki[playerid][26] = CreatePlayerTextDraw(playerid, 400.500000, 309.826202, "");

		GovnisheKletki[playerid][27] = CreatePlayerTextDraw(playerid, 427.000000, 309.826202, "");

		GovnisheKletki[playerid][28] = CreatePlayerTextDraw(playerid, 453.500000, 309.826202, "");


		GovnisheKletki[playerid][29] = CreatePlayerTextDraw(playerid, 480.000000, 309.826202, "");

		GovnisheKletki[playerid][30] = CreatePlayerTextDraw(playerid, 347.500000, 340.326202, "");

		GovnisheKletki[playerid][31] = CreatePlayerTextDraw(playerid, 374.000000, 340.326202, "");

		GovnisheKletki[playerid][32] = CreatePlayerTextDraw(playerid, 400.500000, 340.326202, "");

		GovnisheKletki[playerid][33] = CreatePlayerTextDraw(playerid, 427.000000, 340.326202, "");

		GovnisheKletki[playerid][34] = CreatePlayerTextDraw(playerid, 453.500000, 340.326202, "");

		GovnisheKletki[playerid][35] = CreatePlayerTextDraw(playerid, 480.000000, 340.326202, "");

		GovnisheKletki[playerid][36] = CreatePlayerTextDraw(playerid, 347.500000, 187.826187, "");

		GovnisheKletki[playerid][37] = CreatePlayerTextDraw(playerid, 374.000000, 187.826187, "");

		GovnisheKletki[playerid][38] = CreatePlayerTextDraw(playerid, 400.500000, 187.826187, "");

		GovnisheKletki[playerid][39] = CreatePlayerTextDraw(playerid, 427.000000, 187.826187, "");

		GovnisheKletki[playerid][40] = CreatePlayerTextDraw(playerid, 453.500000, 187.826187, "");

		GovnisheKletki[playerid][41] = CreatePlayerTextDraw(playerid, 480.000000, 187.826187, "");

		GovnisheKletki[playerid][42] = CreatePlayerTextDraw(playerid, 347.500000, 218.326187, "");

		GovnisheKletki[playerid][43] = CreatePlayerTextDraw(playerid, 374.000000, 218.326187, "");

		GovnisheKletki[playerid][44] = CreatePlayerTextDraw(playerid, 400.500000, 218.326187, "");

		GovnisheKletki[playerid][45] = CreatePlayerTextDraw(playerid, 427.000000, 218.326187, "");

		GovnisheKletki[playerid][46] = CreatePlayerTextDraw(playerid, 453.500000, 218.326187, "");

		GovnisheKletki[playerid][47] = CreatePlayerTextDraw(playerid, 480.000000, 218.326187, "");

		GovnisheKletki[playerid][48] = CreatePlayerTextDraw(playerid, 347.500000, 248.826187, "");

		GovnisheKletki[playerid][49] = CreatePlayerTextDraw(playerid, 374.000000, 248.826187, "");

		GovnisheKletki[playerid][50] = CreatePlayerTextDraw(playerid, 400.500000, 248.826187, "");

		GovnisheKletki[playerid][51] = CreatePlayerTextDraw(playerid, 427.000000, 248.826187, "");

		GovnisheKletki[playerid][52] = CreatePlayerTextDraw(playerid, 453.500000, 248.826187, "");

		GovnisheKletki[playerid][53] = CreatePlayerTextDraw(playerid, 480.000000, 248.826187, "");

		GovnisheKletki[playerid][54] = CreatePlayerTextDraw(playerid, 347.500000, 279.326202, "");

		GovnisheKletki[playerid][55] = CreatePlayerTextDraw(playerid, 374.000000, 279.326202, "");



		GovnisheKletki[playerid][56] = CreatePlayerTextDraw(playerid, 400.500000, 279.326202, "");

		GovnisheKletki[playerid][57] = CreatePlayerTextDraw(playerid, 427.000000, 279.326202, "");

		GovnisheKletki[playerid][58] = CreatePlayerTextDraw(playerid, 453.500000, 279.326202, "");

		GovnisheKletki[playerid][59] = CreatePlayerTextDraw(playerid, 480.000000, 279.326202, "");

		GovnisheKletki[playerid][60] = CreatePlayerTextDraw(playerid, 347.500000, 309.826202, "");

		GovnisheKletki[playerid][61] = CreatePlayerTextDraw(playerid, 374.000000, 309.826202, "");

		GovnisheKletki[playerid][62] = CreatePlayerTextDraw(playerid, 400.500000, 309.826202, "");

		GovnisheKletki[playerid][63] = CreatePlayerTextDraw(playerid, 427.000000, 309.826202, "");

		GovnisheKletki[playerid][64] = CreatePlayerTextDraw(playerid, 453.500000, 309.826202, "");


		GovnisheKletki[playerid][65] = CreatePlayerTextDraw(playerid, 480.000000, 309.826202, "");

		GovnisheKletki[playerid][66] = CreatePlayerTextDraw(playerid, 347.500000, 340.326202, "");

		GovnisheKletki[playerid][67] = CreatePlayerTextDraw(playerid, 374.000000, 340.326202, "");

		GovnisheKletki[playerid][68] = CreatePlayerTextDraw(playerid, 400.500000, 340.326202, "");

		GovnisheKletki[playerid][69] = CreatePlayerTextDraw(playerid, 427.000000, 340.326202, "");

		GovnisheKletki[playerid][70] = CreatePlayerTextDraw(playerid, 453.500000, 340.326202, "");

		GovnisheKletki[playerid][71] = CreatePlayerTextDraw(playerid, 480.000000, 340.326202, "");
		for(new i = 0; i < 72; i++)
		{
	        PlayerTextDrawLetterSize(playerid, GovnisheKletki[playerid][i], 0.126499, 0.625000);
			PlayerTextDrawTextSize(playerid, GovnisheKletki[playerid][i], 1280.000000, 1280.000000);
			PlayerTextDrawAlignment(playerid, GovnisheKletki[playerid][i], 3);
			PlayerTextDrawColor(playerid, GovnisheKletki[playerid][i], 0xAAAAAAFF);
			PlayerTextDrawUseBox(playerid, GovnisheKletki[playerid][i], 0);
			PlayerTextDrawBoxColor(playerid, GovnisheKletki[playerid][i], 0x80808080);
			PlayerTextDrawSetShadow(playerid, GovnisheKletki[playerid][i], 0);
			PlayerTextDrawSetOutline(playerid, GovnisheKletki[playerid][i], 1);
			PlayerTextDrawBackgroundColor(playerid, GovnisheKletki[playerid][i], 0x00000000);
			PlayerTextDrawFont(playerid, GovnisheKletki[playerid][i], 2);
			PlayerTextDrawSetProportional(playerid, GovnisheKletki[playerid][i], 1);
			PlayerTextDrawSetSelectable(playerid, GovnisheKletki[playerid][i], 0);
		}
