	reconmenu[0] = TextDrawCreate(562.5639, 293.0972, "LD_SPAC:white"); // ?????
	TextDrawTextSize(reconmenu[0], 55.7993, 9.0000);
	TextDrawAlignment(reconmenu[0], 1);
	TextDrawColor(reconmenu[0], -1321653761);
	TextDrawBackgroundColor(reconmenu[0], 255);
	TextDrawFont(reconmenu[0], 4);
	TextDrawSetProportional(reconmenu[0], 0);
	TextDrawSetShadow(reconmenu[0], 0);

	reconmenu[1] = TextDrawCreate(548.4987, 279.0340, "LD_BEAT:chit"); // ?????
	TextDrawTextSize(reconmenu[1], 29.0000, 27.6898);
	TextDrawAlignment(reconmenu[1], 1);
	TextDrawColor(reconmenu[1], -1321653761);
	TextDrawBackgroundColor(reconmenu[1], 255);
	TextDrawFont(reconmenu[1], 4);
	TextDrawSetProportional(reconmenu[1], 0);
	TextDrawSetShadow(reconmenu[1], 0);

	reconmenu[2] = TextDrawCreate(606.1315, 278.6191, "LD_BEAT:chit"); // ?????
	TextDrawTextSize(reconmenu[2], 29.0000, 28.0000);
	TextDrawAlignment(reconmenu[2], 1);
	TextDrawColor(reconmenu[2], -1321653761);
	TextDrawBackgroundColor(reconmenu[2], 255);
	TextDrawFont(reconmenu[2], 4);
	TextDrawSetProportional(reconmenu[2], 0);
	TextDrawSetShadow(reconmenu[2], 0);

	reconmenu[3] = TextDrawCreate(562.3646, 172.0740, "LD_SPAC:white"); // ?????
	TextDrawTextSize(reconmenu[3], 57.4696, 18.0000);
	TextDrawAlignment(reconmenu[3], 1);
	TextDrawColor(reconmenu[3], -1321653761);
	TextDrawBackgroundColor(reconmenu[3], 255);
	TextDrawFont(reconmenu[3], 4);
	TextDrawSetProportional(reconmenu[3], 0);
	TextDrawSetShadow(reconmenu[3], 0);

	reconmenu[4] = TextDrawCreate(548.4487, 167.5072, "LD_BEAT:chit"); // ?????
	TextDrawTextSize(reconmenu[4], 29.0000, 27.6898);
	TextDrawAlignment(reconmenu[4], 1);
	TextDrawColor(reconmenu[4], -1321653761);
	TextDrawBackgroundColor(reconmenu[4], 255);
	TextDrawFont(reconmenu[4], 4);
	TextDrawSetProportional(reconmenu[4], 0);
	TextDrawSetShadow(reconmenu[4], 0);

	reconmenu[5] = TextDrawCreate(606.0645, 167.3518, "LD_BEAT:chit"); // ?????
	TextDrawTextSize(reconmenu[5], 29.0000, 27.6898);
	TextDrawAlignment(reconmenu[5], 1);
	TextDrawColor(reconmenu[5], -1321653761);
	TextDrawBackgroundColor(reconmenu[5], 255);
	TextDrawFont(reconmenu[5], 4);
	TextDrawSetProportional(reconmenu[5], 0);
	TextDrawSetShadow(reconmenu[5], 0);

	reconmenu[6] = TextDrawCreate(553.3175, 181.2149, "LD_SPAC:white"); // ?????
	TextDrawTextSize(reconmenu[6], 77.0000, 15.0000);
	TextDrawAlignment(reconmenu[6], 1);
	TextDrawColor(reconmenu[6], -1321653761);
	TextDrawBackgroundColor(reconmenu[6], 255);
	TextDrawFont(reconmenu[6], 4);
	TextDrawSetProportional(reconmenu[6], 0);
	TextDrawSetShadow(reconmenu[6], 0);

	reconmenu[7] = TextDrawCreate(553.0955, 195.9669, "LD_SPAC:white"); // ?????
	TextDrawTextSize(reconmenu[7], 77.1299, 98.0000);
	TextDrawAlignment(reconmenu[7], 1);
	TextDrawColor(reconmenu[7], 404232447);
	TextDrawBackgroundColor(reconmenu[7], 255);
	TextDrawFont(reconmenu[7], 4);
	TextDrawSetProportional(reconmenu[7], 0);
	TextDrawSetShadow(reconmenu[7], 0);

	reconmenu[8] = TextDrawCreate(549.3798, 147.6004, "LD_BEAT:chit"); // ?????
	TextDrawTextSize(reconmenu[8], 89.0000, 174.1893);
	TextDrawAlignment(reconmenu[8], 1);
	TextDrawColor(reconmenu[8], -253);
	TextDrawBackgroundColor(reconmenu[8], 255);
	TextDrawFont(reconmenu[8], 4);
	TextDrawSetProportional(reconmenu[8], 0);
	TextDrawSetShadow(reconmenu[8], 0);

	reconmenu[9] = TextDrawCreate(7.9166, 164.0514, "LD_SPAC:white"); // ?????
	TextDrawTextSize(reconmenu[9], 46.0000, 111.3908);
	TextDrawAlignment(reconmenu[9], 1);
	TextDrawColor(reconmenu[9], 404232447);
	TextDrawBackgroundColor(reconmenu[9], 255);
	TextDrawFont(reconmenu[9], 4);
	TextDrawSetProportional(reconmenu[9], 0);
	TextDrawSetShadow(reconmenu[9], 0);

	reconmenu[10] = TextDrawCreate(52.8334, 164.4884, "LD_SPAC:white"); // ?????
	TextDrawTextSize(reconmenu[10], 1.6296, 110.9589);
	TextDrawAlignment(reconmenu[10], 1);
	TextDrawColor(reconmenu[10], -1321653761);
	TextDrawBackgroundColor(reconmenu[10], 255);
	TextDrawFont(reconmenu[10], 4);
	TextDrawSetProportional(reconmenu[10], 0);
	TextDrawSetShadow(reconmenu[10], 0);

	reconmenu[11] = TextDrawCreate(560.1170, 179.7259, "~w~Name"); // ?????
	TextDrawLetterSize(reconmenu[11], 0.1712, 0.6509);
	TextDrawAlignment(reconmenu[11], 1);
	TextDrawColor(reconmenu[11], 255);
	TextDrawBackgroundColor(reconmenu[11], 255);
	TextDrawFont(reconmenu[11], 1);
	TextDrawSetProportional(reconmenu[11], 1);
	TextDrawSetShadow(reconmenu[11], 0);

	reconmenu[12] = TextDrawCreate(559.6959, 201.0558, "Level:~n~Warns:~n~Armour:~n~Health:~n~Car_HP:~n~Speed:~n~NetStat:~n~Ammo:~n~Shot:~n~Time_Shot:~n~AFK_Time:~n~Engine:"); // ?????
	TextDrawLetterSize(reconmenu[12], 0.1699, 0.7961);
	TextDrawAlignment(reconmenu[12], 1);
	TextDrawColor(reconmenu[12], -1);
	TextDrawBackgroundColor(reconmenu[12], 255);
	TextDrawFont(reconmenu[12], 1);
	TextDrawSetProportional(reconmenu[12], 1);
	TextDrawSetShadow(reconmenu[12], 0);
	////////
    spec_PTD[playerid][0] = CreatePlayerTextDraw(playerid, 579.8861, 179.5520, "Donatello_Blade~n~999"); // ?????
	PlayerTextDrawLetterSize(playerid, spec_PTD[playerid][0], 0.1502, 0.6924);
	PlayerTextDrawAlignment(playerid, spec_PTD[playerid][0], 1);
	PlayerTextDrawColor(playerid, spec_PTD[playerid][0], -1);
	PlayerTextDrawBackgroundColor(playerid, spec_PTD[playerid][0], 255);
	PlayerTextDrawFont(playerid, spec_PTD[playerid][0], 1);
	PlayerTextDrawSetProportional(playerid, spec_PTD[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, spec_PTD[playerid][0], 0);

	spec_PTD[playerid][1] = CreatePlayerTextDraw(playerid, 532.0640, 188.4774, ""); // ?????
	PlayerTextDrawTextSize(playerid, spec_PTD[playerid][1], 125.0000, 105.0000);
	PlayerTextDrawAlignment(playerid, spec_PTD[playerid][1], 1);
	PlayerTextDrawColor(playerid, spec_PTD[playerid][1], 48);
	PlayerTextDrawBackgroundColor(playerid, spec_PTD[playerid][1], 0);
	PlayerTextDrawFont(playerid, spec_PTD[playerid][1], 5);
	PlayerTextDrawSetProportional(playerid, spec_PTD[playerid][1], 0);
	PlayerTextDrawSetShadow(playerid, spec_PTD[playerid][1], 0);
	PlayerTextDrawSetPreviewModel(playerid, spec_PTD[playerid][1], 252);
	PlayerTextDrawSetPreviewRot(playerid, spec_PTD[playerid][1], 0.0000, 0.0000, 0.0000, 1.0000);

	spec_PTD[playerid][2] = CreatePlayerTextDraw(playerid, 597.3869, 201.0558, "1:1/8~n~0~n~0~n~100~n~-~n~0_/_100~n~0(0.00)~n~0.0~n~0/0~n~0/0~n~0~n~-"); // ?????
	PlayerTextDrawLetterSize(playerid, spec_PTD[playerid][2], 0.1849, 0.8065);
	PlayerTextDrawAlignment(playerid, spec_PTD[playerid][2], 1);
	PlayerTextDrawColor(playerid, spec_PTD[playerid][2], -1321653761);
	PlayerTextDrawBackgroundColor(playerid, spec_PTD[playerid][2], 255);
	PlayerTextDrawFont(playerid, spec_PTD[playerid][2], 1);
	PlayerTextDrawSetProportional(playerid, spec_PTD[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, spec_PTD[playerid][2], 0);
	//------------------------------
	testpanel[playerid][0] = CreatePlayerTextDraw(playerid, 11.8499, 167.4035, "update"); // ?????
	PlayerTextDrawLetterSize(playerid, testpanel[playerid][0], 0.2319, 1.0967);
	PlayerTextDrawTextSize(playerid, testpanel[playerid][0], 48.0000, 20.0000);
	PlayerTextDrawAlignment(playerid, testpanel[playerid][0], 1);
	PlayerTextDrawColor(playerid, testpanel[playerid][0], -1321653761);
	PlayerTextDrawUseBox(playerid, testpanel[playerid][0], 1);
	PlayerTextDrawBoxColor(playerid, testpanel[playerid][0], 0xFFFFFF00);
	PlayerTextDrawBackgroundColor(playerid, testpanel[playerid][0], 255);
	PlayerTextDrawFont(playerid, testpanel[playerid][0], 2);
	PlayerTextDrawSetProportional(playerid, testpanel[playerid][0], 1);
	PlayerTextDrawSetShadow(playerid, testpanel[playerid][0], 0);
	PlayerTextDrawSetSelectable(playerid, testpanel[playerid][0], true);

	testpanel[playerid][1] = CreatePlayerTextDraw(playerid, 11.8499, 180.1042, "stats"); // ?????
	PlayerTextDrawLetterSize(playerid, testpanel[playerid][1], 0.2319, 1.0864);
	PlayerTextDrawTextSize(playerid, testpanel[playerid][1], 48.0000, 20.0000);
	PlayerTextDrawAlignment(playerid, testpanel[playerid][1], 1);
	PlayerTextDrawColor(playerid, testpanel[playerid][1], -1321653761);
	PlayerTextDrawUseBox(playerid, testpanel[playerid][1], 1);
	PlayerTextDrawBoxColor(playerid, testpanel[playerid][1], 0xFFFFFF00);
	PlayerTextDrawBackgroundColor(playerid, testpanel[playerid][1], 255);
	PlayerTextDrawFont(playerid, testpanel[playerid][1], 2);
	PlayerTextDrawSetProportional(playerid, testpanel[playerid][1], 1);
	PlayerTextDrawSetShadow(playerid, testpanel[playerid][1], 0);
	PlayerTextDrawSetSelectable(playerid, testpanel[playerid][1], true);

	testpanel[playerid][2] = CreatePlayerTextDraw(playerid, 11.8499, 192.2050, "gmtest"); // ?????
	PlayerTextDrawLetterSize(playerid, testpanel[playerid][2], 0.2319, 1.0864);
	PlayerTextDrawTextSize(playerid, testpanel[playerid][2], 48.0000, 20.0000);
	PlayerTextDrawAlignment(playerid, testpanel[playerid][2], 1);
	PlayerTextDrawColor(playerid, testpanel[playerid][2], -1321653761);
	PlayerTextDrawUseBox(playerid, testpanel[playerid][2], 1);
	PlayerTextDrawBoxColor(playerid, testpanel[playerid][2], 0xFFFFFF00);
	PlayerTextDrawBackgroundColor(playerid, testpanel[playerid][2], 255);
	PlayerTextDrawFont(playerid, testpanel[playerid][2], 2);
	PlayerTextDrawSetProportional(playerid, testpanel[playerid][2], 1);
	PlayerTextDrawSetShadow(playerid, testpanel[playerid][2], 0);
	PlayerTextDrawSetSelectable(playerid, testpanel[playerid][2], true);

	testpanel[playerid][3] = CreatePlayerTextDraw(playerid, 11.8499, 204.0057, "slap"); // ?????
	PlayerTextDrawLetterSize(playerid, testpanel[playerid][3], 0.2419, 1.0864);
	PlayerTextDrawTextSize(playerid, testpanel[playerid][3], 48.0000, 20.0000);
	PlayerTextDrawAlignment(playerid, testpanel[playerid][3], 1);
	PlayerTextDrawColor(playerid, testpanel[playerid][3], -1321653761);
	PlayerTextDrawUseBox(playerid, testpanel[playerid][3], 1);
	PlayerTextDrawBoxColor(playerid, testpanel[playerid][3], 0xFFFFFF00);
	PlayerTextDrawBackgroundColor(playerid, testpanel[playerid][3], 255);
	PlayerTextDrawFont(playerid, testpanel[playerid][3], 2);
	PlayerTextDrawSetProportional(playerid, testpanel[playerid][3], 1);
	PlayerTextDrawSetShadow(playerid, testpanel[playerid][3], 0);
	PlayerTextDrawSetSelectable(playerid, testpanel[playerid][3], true);

	testpanel[playerid][4] = CreatePlayerTextDraw(playerid, 11.8499, 216.0065, "spawn"); // ?????
	PlayerTextDrawLetterSize(playerid, testpanel[playerid][4], 0.2419, 1.0864);
	PlayerTextDrawTextSize(playerid, testpanel[playerid][4], 48.0000, 20.0000);
	PlayerTextDrawAlignment(playerid, testpanel[playerid][4], 1);
	PlayerTextDrawColor(playerid, testpanel[playerid][4], -1321653761);
	PlayerTextDrawUseBox(playerid, testpanel[playerid][4], 1);
	PlayerTextDrawBoxColor(playerid, testpanel[playerid][4], 0xFFFFFF00);
	PlayerTextDrawBackgroundColor(playerid, testpanel[playerid][4], 255);
	PlayerTextDrawFont(playerid, testpanel[playerid][4], 2);
	PlayerTextDrawSetProportional(playerid, testpanel[playerid][4], 1);
	PlayerTextDrawSetShadow(playerid, testpanel[playerid][4], 0);
	PlayerTextDrawSetSelectable(playerid, testpanel[playerid][4], true);

	testpanel[playerid][5] = CreatePlayerTextDraw(playerid, 11.7498, 228.0072, "weap"); // ?????
	PlayerTextDrawLetterSize(playerid, testpanel[playerid][5], 0.2419, 1.0864);
	PlayerTextDrawTextSize(playerid, testpanel[playerid][5], 47.9000, 20.0000);
	PlayerTextDrawAlignment(playerid, testpanel[playerid][5], 1);
	PlayerTextDrawColor(playerid, testpanel[playerid][5], -1321653761);
	PlayerTextDrawUseBox(playerid, testpanel[playerid][5], 1);
	PlayerTextDrawBoxColor(playerid, testpanel[playerid][5], 0xFFFFFF00);
	PlayerTextDrawBackgroundColor(playerid, testpanel[playerid][5], 255);
	PlayerTextDrawFont(playerid, testpanel[playerid][5], 2);
	PlayerTextDrawSetProportional(playerid, testpanel[playerid][5], 1);
	PlayerTextDrawSetShadow(playerid, testpanel[playerid][5], 0);
	PlayerTextDrawSetSelectable(playerid, testpanel[playerid][5], true);

	testpanel[playerid][6] = CreatePlayerTextDraw(playerid, 11.7498, 239.6078, "check"); // ?????
	PlayerTextDrawLetterSize(playerid, testpanel[playerid][6], 0.2419, 1.0864);
	PlayerTextDrawTextSize(playerid, testpanel[playerid][6], 47.9000, 20.0000);
	PlayerTextDrawAlignment(playerid, testpanel[playerid][6], 1);
	PlayerTextDrawColor(playerid, testpanel[playerid][6], -1321653761);
	PlayerTextDrawUseBox(playerid, testpanel[playerid][6], 1);
	PlayerTextDrawBoxColor(playerid, testpanel[playerid][6], 0xFFFFFF00);
	PlayerTextDrawBackgroundColor(playerid, testpanel[playerid][6], 255);
	PlayerTextDrawFont(playerid, testpanel[playerid][6], 2);
	PlayerTextDrawSetProportional(playerid, testpanel[playerid][6], 1);
	PlayerTextDrawSetShadow(playerid, testpanel[playerid][6], 0);
	PlayerTextDrawSetSelectable(playerid, testpanel[playerid][6], true);

	testpanel[playerid][7] = CreatePlayerTextDraw(playerid, 11.8664, 251.0975, "get"); // ?????
	PlayerTextDrawLetterSize(playerid, testpanel[playerid][7], 0.2419, 1.1164);
	PlayerTextDrawTextSize(playerid, testpanel[playerid][7], 47.9000, 20.0000);
	PlayerTextDrawAlignment(playerid, testpanel[playerid][7], 1);
	PlayerTextDrawColor(playerid, testpanel[playerid][7], -1321653761);
	PlayerTextDrawUseBox(playerid, testpanel[playerid][7], 1);
	PlayerTextDrawBoxColor(playerid, testpanel[playerid][7], 0xFFFFFF00);
	PlayerTextDrawBackgroundColor(playerid, testpanel[playerid][7], 255);
	PlayerTextDrawFont(playerid, testpanel[playerid][7], 2);
	PlayerTextDrawSetProportional(playerid, testpanel[playerid][7], 1);
	PlayerTextDrawSetShadow(playerid, testpanel[playerid][7], 0);
	PlayerTextDrawSetSelectable(playerid, testpanel[playerid][7], true);

	testpanel[playerid][8] = CreatePlayerTextDraw(playerid, 11.9666, 262.9093, "exit"); // ?????
	PlayerTextDrawLetterSize(playerid, testpanel[playerid][8], 0.2419, 1.0864);
	PlayerTextDrawTextSize(playerid, testpanel[playerid][8], 47.7200, 20.0000);
	PlayerTextDrawAlignment(playerid, testpanel[playerid][8], 1);
	PlayerTextDrawColor(playerid, testpanel[playerid][8], -1321653761);
	PlayerTextDrawUseBox(playerid, testpanel[playerid][8], 1);
	PlayerTextDrawBoxColor(playerid, testpanel[playerid][8], 0xFFFFFF00);
	PlayerTextDrawBackgroundColor(playerid, testpanel[playerid][8], 255);
	PlayerTextDrawFont(playerid, testpanel[playerid][8], 2);
	PlayerTextDrawSetProportional(playerid, testpanel[playerid][8], 1);
	PlayerTextDrawSetShadow(playerid, testpanel[playerid][8], 0);
	PlayerTextDrawSetSelectable(playerid, testpanel[playerid][8], true);